// Generated by scripts/generate_bindings.py; do not edit.

use hmac::{Hmac, KeyInit, Mac};
use serde_json::{json, Value};
use sha2::Sha256;
use std::collections::BTreeMap;

pub const C3_SIGNATURE_ALGORITHM: &str = "hmac-sha256";
pub const C3_SIGNATURE_PREFIX: &str = "hmac-sha256:";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VerifierKey {
    pub key_id: String,
    pub secret: Vec<u8>,
    pub revoked: bool,
}

impl VerifierKey {
    pub fn new(key_id: impl Into<String>, secret: impl Into<Vec<u8>>) -> Self {
        Self {
            key_id: key_id.into(),
            secret: secret.into(),
            revoked: false,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct C3SignatureVerification {
    pub valid: bool,
    pub reason: Option<String>,
    pub error_code: Option<String>,
    pub key_id: Option<String>,
    pub claim_tier: Option<String>,
    pub aggregate_passed: Option<bool>,
}

pub trait VerifierTrustStore {
    fn get_key(&self, key_id: &str) -> Option<&VerifierKey>;

    fn verify_signature_value(
        &self,
        _key_id: &str,
        _report_with_empty_signature: &Value,
        _signature_value: &str,
    ) -> Option<Result<(), String>> {
        None
    }
}

#[derive(Debug, Default)]
pub struct InMemoryVerifierTrustStore {
    keys: BTreeMap<String, VerifierKey>,
}

impl InMemoryVerifierTrustStore {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn register_key(&mut self, key_id: impl Into<String>, secret: impl Into<Vec<u8>>) {
        let key_id = key_id.into();
        self.keys
            .insert(key_id.clone(), VerifierKey::new(key_id, secret.into()));
    }

    pub fn revoke_key(&mut self, key_id: &str) -> Result<(), String> {
        let key = self
            .keys
            .get_mut(key_id)
            .ok_or_else(|| format!("unknown verifier key: {key_id}"))?;
        key.revoked = true;
        Ok(())
    }
}

impl VerifierTrustStore for InMemoryVerifierTrustStore {
    fn get_key(&self, key_id: &str) -> Option<&VerifierKey> {
        self.keys.get(key_id)
    }
}

pub fn sign_report(report: &Value, key_id: &str, secret: &[u8]) -> Result<Value, String> {
    let mut signed = report.clone();
    let object = signed
        .as_object_mut()
        .ok_or_else(|| "C3 report must be a JSON object".to_string())?;
    object.insert(
        "signature".to_string(),
        json!({
            "algorithm": C3_SIGNATURE_ALGORITHM,
            "key_id": key_id,
            "value": "",
        }),
    );
    let signature = signature_value(&signed, secret)?;
    signed["signature"]["value"] = Value::String(signature);
    Ok(signed)
}

pub fn verify_report(report: &Value, trust_store: &impl VerifierTrustStore) -> C3SignatureVerification {
    let Some(signature) = report.get("signature").and_then(Value::as_object) else {
        return invalid("signature_missing", None);
    };
    let algorithm = signature.get("algorithm").and_then(Value::as_str);
    let key_id = signature.get("key_id").and_then(Value::as_str);
    let value = signature.get("value").and_then(Value::as_str);
    if algorithm != Some(C3_SIGNATURE_ALGORITHM) {
        return invalid("algorithm_unsupported", key_id);
    }
    let Some(key_id) = key_id else {
        return invalid("key_missing", None);
    };
    let Some(key) = trust_store.get_key(key_id) else {
        return invalid("unknown_key", Some(key_id));
    };
    if key.revoked {
        return invalid("revoked_key", Some(key_id));
    }
    let Some(value) = value else {
        return invalid("signature_value_missing", Some(key_id));
    };

    let mut unsigned = report.clone();
    unsigned["signature"] = json!({
        "algorithm": C3_SIGNATURE_ALGORITHM,
        "key_id": key_id,
        "value": "",
    });
    if let Some(delegated) = trust_store.verify_signature_value(key_id, &unsigned, value) {
        if let Err(reason) = delegated {
            return invalid(&reason, Some(key_id));
        }
    } else {
        let Ok(expected) = signature_value(&unsigned, &key.secret) else {
            return invalid("signature_invalid", Some(key_id));
        };
        if !constant_time_eq(value.as_bytes(), expected.as_bytes()) {
            return invalid("signature_invalid", Some(key_id));
        }
    }

    C3SignatureVerification {
        valid: true,
        reason: None,
        error_code: None,
        key_id: Some(key_id.to_string()),
        claim_tier: report
            .get("claim_tier")
            .and_then(Value::as_str)
            .map(str::to_string),
        aggregate_passed: report
            .get("aggregate")
            .and_then(|aggregate| aggregate.get("passed"))
            .and_then(Value::as_bool),
    }
}

fn invalid(reason: &str, key_id: Option<&str>) -> C3SignatureVerification {
    C3SignatureVerification {
        valid: false,
        reason: Some(reason.to_string()),
        error_code: Some(error_code(reason).to_string()),
        key_id: key_id.map(str::to_string),
        claim_tier: None,
        aggregate_passed: None,
    }
}

fn error_code(reason: &str) -> &'static str {
    match reason {
        "signature_missing" => "UNSIGNED",
        "algorithm_unsupported" => "ALGORITHM_UNSUPPORTED",
        "key_missing" => "KEY_MISSING",
        "unknown_key" => "UNKNOWN_KEY",
        "revoked_key" => "REVOKED_KEY",
        "signature_value_missing" => "SIGNATURE_VALUE_MISSING",
        "signature_invalid" => "SIGNATURE_INVALID",
        _ => "SIGNATURE_INVALID",
    }
}

fn signature_value(report_with_empty_signature: &Value, secret: &[u8]) -> Result<String, String> {
    let mut mac = Hmac::<Sha256>::new_from_slice(secret).map_err(|error| error.to_string())?;
    mac.update(canonical_json(report_with_empty_signature)?.as_bytes());
    Ok(C3_SIGNATURE_PREFIX.to_string() + &hex_lower(&mac.finalize().into_bytes()))
}

fn canonical_json(value: &Value) -> Result<String, String> {
    match value {
        Value::Null => Ok("null".to_string()),
        Value::Bool(value) => Ok(if *value { "true" } else { "false" }.to_string()),
        Value::Number(value) => Ok(value.to_string()),
        Value::String(value) => serde_json::to_string(value).map_err(|error| error.to_string()),
        Value::Array(values) => {
            let rendered = values
                .iter()
                .map(canonical_json)
                .collect::<Result<Vec<_>, _>>()?;
            let mut output = String::from("[");
            output.push_str(&rendered.join(","));
            output.push(']');
            Ok(output)
        }
        Value::Object(map) => {
            let mut keys = map.keys().collect::<Vec<_>>();
            keys.sort();
            let rendered = keys
                .into_iter()
                .map(|key| {
                    let mut output = serde_json::to_string(key).map_err(|error| error.to_string())?;
                    output.push(':');
                    output.push_str(&canonical_json(&map[key])?);
                    Ok(output)
                })
                .collect::<Result<Vec<String>, String>>()?;
            let mut output = String::from("{");
            output.push_str(&rendered.join(","));
            output.push('}');
            Ok(output)
        }
    }
}

fn hex_lower(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut output = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        output.push(HEX[(byte >> 4) as usize] as char);
        output.push(HEX[(byte & 0x0f) as usize] as char);
    }
    output
}

fn constant_time_eq(left: &[u8], right: &[u8]) -> bool {
    if left.len() != right.len() {
        return false;
    }
    left.iter()
        .zip(right.iter())
        .fold(0u8, |acc, (left, right)| acc | (left ^ right))
        == 0
}

#[cfg(test)]
mod tests {
    use super::*;

    fn vector_report() -> Value {
        serde_json::from_str(r#"{
            "report_id": "33333333-3333-4333-8333-333333333333",
            "profile_ref": "c4://profile/ewpt-toy/v1",
            "frozen_pipeline_ref": "c4://pipeline/ewpt-toy/baseline",
            "checks": [
                        {
                                    "check": "INJECTION",
                                    "status": "PASS",
                                    "metrics": {
                                                "recovery_rate": 0.98
                                    },
                                    "evidence_refs": [
                                                "c4://evidence/injection/example"
                                    ]
                        }
            ],
            "aggregate": {
                        "passed": true,
                        "score": 0.98
            },
            "claim_tier": "recapitulated-known",
            "claim_tier_is_candidate": false,
            "perturbation_pairs": [],
            "insensitivity_flags": [],
            "challenger_panel": {
                        "challenger_ids": [
                                    "challenger-a",
                                    "challenger-b"
                        ],
                        "min_required": 2
            },
            "independence_attestation_debate": {
                        "min_independent_challengers": 2,
                        "lineage_disjoint": true,
                        "correlation_warning": false
            },
            "referee": {
                        "referee_id": "s3-referee",
                        "non_gameable": true,
                        "signed_by": "s3-key",
                        "distinct_from_proponent": true
            },
            "debate_ref": "c4://debate/ewpt-toy/example"
}"#).expect("vector report JSON")
    }

    #[test]
    fn argusverify_accepts_valid_vector_and_rejects_tamper_unsigned_and_revoked() {
        let mut trust_store = InMemoryVerifierTrustStore::new();
        trust_store.register_key("s3-key", "s3-secret".as_bytes().to_vec());

        let signed = sign_report(
            &vector_report(),
            "s3-key",
            "s3-secret".as_bytes(),
        )
        .expect("sign vector");
        assert_eq!(signed["signature"]["value"], "hmac-sha256:923abc6bc8e3f4c574f1f338b73deecbab51716f79bac62588b38b6b83f311d0");

        let valid = verify_report(&signed, &trust_store);
        assert!(valid.valid);
        assert_eq!(valid.claim_tier.as_deref(), Some("recapitulated-known"));
        assert_eq!(valid.aggregate_passed, Some(true));

        trust_store.register_key("s3-key-v2", "s3-secret-v2".as_bytes().to_vec());
        assert!(verify_report(&signed, &trust_store).valid);
        let signed_v2 = sign_report(
            &vector_report(),
            "s3-key-v2",
            "s3-secret-v2".as_bytes(),
        )
        .expect("sign rotated vector");
        assert_eq!(
            verify_report(&signed_v2, &trust_store).key_id.as_deref(),
            Some("s3-key-v2")
        );

        let mut tampered = signed.clone();
        tampered["aggregate"]["score"] = json!(0.99);
        let tampered_verification = verify_report(&tampered, &trust_store);
        assert!(!tampered_verification.valid);
        assert_eq!(
            tampered_verification.error_code.as_deref(),
            Some("SIGNATURE_INVALID")
        );

        let mut unsigned = signed.clone();
        unsigned.as_object_mut().expect("object").remove("signature");
        let unsigned_verification = verify_report(&unsigned, &trust_store);
        assert!(!unsigned_verification.valid);
        assert_eq!(unsigned_verification.error_code.as_deref(), Some("UNSIGNED"));

        trust_store
            .revoke_key("s3-key")
            .expect("revoke key");
        let revoked_verification = verify_report(&signed, &trust_store);
        assert!(!revoked_verification.valid);
        assert_eq!(revoked_verification.error_code.as_deref(), Some("REVOKED_KEY"));
    }

    struct DelegatingTrustStore {
        key: VerifierKey,
        accepted_signature: String,
    }

    impl VerifierTrustStore for DelegatingTrustStore {
        fn get_key(&self, key_id: &str) -> Option<&VerifierKey> {
            if key_id == self.key.key_id {
                Some(&self.key)
            } else {
                None
            }
        }

        fn verify_signature_value(
            &self,
            key_id: &str,
            report_with_empty_signature: &Value,
            signature_value: &str,
        ) -> Option<Result<(), String>> {
            assert_eq!(key_id, self.key.key_id);
            assert_eq!(report_with_empty_signature["signature"]["value"], "");
            if signature_value == self.accepted_signature {
                Some(Ok(()))
            } else {
                Some(Err("signature_invalid".to_string()))
            }
        }
    }

    #[test]
    fn argusverify_delegates_signature_value_for_secretless_trust_store() {
        let signed = sign_report(
            &vector_report(),
            "s3-key",
            "s3-secret".as_bytes(),
        )
        .expect("sign vector");
        let accepted_signature = signed["signature"]["value"]
            .as_str()
            .expect("signature string")
            .to_string();
        let trust_store = DelegatingTrustStore {
            key: VerifierKey::new("s3-key", Vec::<u8>::new()),
            accepted_signature,
        };

        let valid = verify_report(&signed, &trust_store);
        assert!(valid.valid);

        let mut bad_signature = signed.clone();
        bad_signature["signature"]["value"] = Value::String("hmac-sha256:bad".to_string());
        let invalid = verify_report(&bad_signature, &trust_store);
        assert!(!invalid.valid);
        assert_eq!(invalid.error_code.as_deref(), Some("SIGNATURE_INVALID"));
    }
}
