// Generated by scripts/generate_bindings.py; do not edit.

use serde::{Deserialize, Serialize};
use serde_json::Value;

pub const C1_SCHEMA_SHA256: &str = "sha256:70de039b4c9687e9ce83ed5dc0ff444c681dd068cf79b8c1d6138bfd9c4b56d5";

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum LifecycleState {
    Registered,
    Accepted,
    Planning,
    Building,
    Validating,
    Reported,
    Failed,
    Rejected,
    Cancelled,
    Quarantined,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LifecycleMethod {
    Register,
    Accept,
    Refuse,
    Plan,
    Build,
    Validate,
    Report,
    Heartbeat,
    Cancel,
    Fail,
    Quarantine,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ClaimTier {
    RanToy,
    RecapitulatedKnown,
    NovelNeedsHuman,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum AcceptanceReason {
    OutOfScope,
    MissingAdapter,
    BudgetTooSmall,
    NoVerifier,
    VersionUnsupported,
    Policy,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CostEstimate {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub compute_units: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gpu_seconds: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model_tokens: Option<f64>,
    pub cost_usd: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SubagentEnvelope {
    pub contract_version: String,
    pub method: LifecycleMethod,
    pub job_id: String,
    pub trace_id: String,
    pub state: LifecycleState,
    pub idempotency_key: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub capability_descriptor_ref: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub job_envelope_ref: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payload: Option<Value>,
}

impl SubagentEnvelope {
    pub fn validate(&self) -> Result<(), &'static str> {
        if !self.contract_version.starts_with("1.") {
            return Err("contract_version must be C1 major 1");
        }
        if self.idempotency_key.is_empty() {
            return Err("idempotency_key must be non-empty");
        }
        Ok(())
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Acceptance {
    pub job_id: String,
    pub accepted: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<AcceptanceReason>,
    pub state: LifecycleState,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub estimated_cost: Option<CostEstimate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plan_eta_seconds: Option<u64>,
    pub idempotency_key: String,
}

impl Acceptance {
    pub fn validate(&self) -> Result<(), &'static str> {
        match (self.accepted, &self.state, self.reason.is_some()) {
            (true, LifecycleState::Accepted, false) => Ok(()),
            (false, LifecycleState::Rejected, true) => Ok(()),
            _ => Err("Acceptance accepted/state/reason fields are inconsistent"),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ErrorCategory {
    Retryable,
    Permanent,
    Budget,
    Policy,
    VerifierUnavailable,
    Sandbox,
    Validation,
    VersionUnsupported,
    Quarantine,
    NotFound,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TypedError {
    pub category: ErrorCategory,
    pub code: String,
    pub message: String,
    pub retryable: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub retry_after_seconds: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provenance_ref: Option<String>,
}

impl TypedError {
    pub fn validate(&self) -> Result<(), &'static str> {
        if self.retryable && self.retry_after_seconds.is_none() {
            return Err("retryable errors require retry_after_seconds");
        }
        Ok(())
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LifecycleEvent {
    pub event_id: String,
    pub job_id: String,
    pub root_request_id: String,
    pub seq: u64,
    pub from_state: LifecycleState,
    pub to_state: LifecycleState,
    pub method: LifecycleMethod,
    pub trigger: String,
    pub payload_hash: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub spend_delta: Option<CostEstimate>,
    pub trace_id: String,
    pub idempotency_key: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ledger_ref: Option<String>,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn envelope_json() -> &'static str {
        r#"{
            "contract_version": "1.0.0",
            "method": "accept",
            "job_id": "11111111-1111-4111-8111-111111111111",
            "trace_id": "trace-c1-example",
            "state": "ACCEPTED",
            "idempotency_key": "accept-11111111",
            "payload": {
                        "accepted": true
            }
}"#
    }

    #[test]
    fn c1_schema_digest_is_generated() {
        assert!(C1_SCHEMA_SHA256.starts_with("sha256:"));
    }

    #[test]
    fn serde_round_trips_c1_subagent_envelope_golden_sample() {
        let envelope: SubagentEnvelope =
            serde_json::from_str(envelope_json()).expect("deserialize C1 envelope");
        envelope.validate().expect("C1 envelope validates");
        let encoded = serde_json::to_string(&envelope).expect("serialize C1 envelope");
        let decoded: SubagentEnvelope = serde_json::from_str(&encoded).expect("deserialize roundtrip");
        assert_eq!(decoded, envelope);
    }

    #[test]
    fn c1_acceptance_rejects_inconsistent_refusals() {
        let accepted = Acceptance {
            job_id: "11111111-1111-4111-8111-111111111111".to_string(),
            accepted: true,
            reason: None,
            state: LifecycleState::Accepted,
            estimated_cost: Some(CostEstimate {
                compute_units: None,
                gpu_seconds: None,
                model_tokens: None,
                cost_usd: 0.01,
            }),
            plan_eta_seconds: None,
            idempotency_key: "accept-11111111".to_string(),
        };
        accepted.validate().expect("accepted shape validates");

        let invalid = Acceptance {
            accepted: false,
            state: LifecycleState::Accepted,
            ..accepted
        };
        assert_eq!(
            invalid.validate(),
            Err("Acceptance accepted/state/reason fields are inconsistent")
        );
    }
}
