// Generated by scripts/generate_bindings.py; do not edit.

use serde::{Deserialize, Serialize};

pub const C4_SCHEMA_SHA256: &str = "sha256:32d5caf1f5f57b4c1da2eb7dc81e31f7423c834f6945e3839ffc6356fc4d35de";

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ClaimTier {
    RanToy,
    RecapitulatedKnown,
    NovelNeedsHuman,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Producer {
    pub subsystem: String,
    pub version: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Lineage {
    pub input_refs: Vec<String>,
    pub code_ref: String,
    pub environment_digest: String,
    pub seeds: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RetentionPolicy {
    #[serde(rename = "class", skip_serializing_if = "Option::is_none")]
    pub class_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub retain_until: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hold_id: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ArtifactRecord {
    pub artifact_ref: String,
    pub kind: String,
    pub content_hash: String,
    pub hash_algorithm: String,
    pub size_bytes: u64,
    pub created_at: String,
    pub producer: Producer,
    pub lineage: Lineage,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub claim_tier: Option<ClaimTier>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub validation_report_ref: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub schema_ref: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub retention: Option<RetentionPolicy>,
}

impl ArtifactRecord {
    pub fn validate_promoted_tier(&self) -> Result<(), &'static str> {
        if matches!(
            self.claim_tier,
            Some(ClaimTier::RecapitulatedKnown | ClaimTier::NovelNeedsHuman)
        ) && self.validation_report_ref.is_none()
        {
            return Err("promoted claim_tier requires validation_report_ref");
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn example_record() -> ArtifactRecord {
        ArtifactRecord {
            artifact_ref: "c4://artifact/example".to_string(),
            kind: "dataset".to_string(),
            content_hash: "blake3:af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262".to_string(),
            hash_algorithm: "BLAKE3".to_string(),
            size_bytes: 0,
            created_at: "2026-01-01T00:00:00Z".to_string(),
            producer: Producer {
                subsystem: "S8".to_string(),
                version: "1.0.0".to_string(),
            },
            lineage: Lineage {
                input_refs: Vec::new(),
                code_ref: "git:project-argus@example".to_string(),
                environment_digest: "oci:sha256-example".to_string(),
                seeds: Vec::new(),
            },
            claim_tier: None,
            validation_report_ref: None,
            schema_ref: None,
            retention: None,
        }
    }

    #[test]
    fn c4_schema_digest_is_generated() {
        assert!(C4_SCHEMA_SHA256.starts_with("sha256:"));
    }

    #[test]
    fn promoted_tier_requires_validation_report_ref() {
        let mut record = example_record();
        assert_eq!(record.validate_promoted_tier(), Ok(()));

        record.claim_tier = Some(ClaimTier::NovelNeedsHuman);
        assert_eq!(
            record.validate_promoted_tier(),
            Err("promoted claim_tier requires validation_report_ref")
        );

        record.validation_report_ref = Some("c4://report/example".to_string());
        assert_eq!(record.validate_promoted_tier(), Ok(()));
    }

    #[test]
    fn serde_round_trips_c4_artifact_record() {
        let record = example_record();
        let json = serde_json::to_string(&record).expect("serialize record");
        let decoded: ArtifactRecord = serde_json::from_str(&json).expect("deserialize record");

        assert_eq!(decoded, record);
    }
}
