// Generated by scripts/generate_bindings.py; do not edit.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Contract {
    pub id: &'static str,
    pub name: &'static str,
    pub owner: &'static str,
    pub version: &'static str,
    pub schema: &'static str,
    pub consumers: &'static [&'static str],
}

pub const CONTRACTS: &[Contract] = &[
    Contract { id: "C1", name: "Subagent Contract", owner: "S1", version: "1.0.0", schema: "c1.subagent.schema.json", consumers: &["S2", "S3", "S4", "S5", "S11", "S12"] },
    Contract { id: "C2", name: "Task Job Envelope", owner: "S5", version: "1.0.0", schema: "c2.job-envelope.schema.json", consumers: &["S1", "S2", "S3", "S4", "S7", "S9", "S10", "S11", "S12"] },
    Contract { id: "C3", name: "Verifier Interface and Validation Report", owner: "S3", version: "1.1.0", schema: "c3.validation-report.schema.json", consumers: &["S1", "S2", "S4", "S5", "S7", "S8", "S9", "S11", "S12"] },
    Contract { id: "C4", name: "Artifact and Provenance Record", owner: "S8", version: "1.0.0", schema: "c4.artifact-record.schema.json", consumers: &["S1", "S2", "S3", "S4", "S5", "S6", "S7", "S9", "S10", "S11", "S12"] },
    Contract { id: "C5", name: "Registry Capability Descriptor", owner: "S6/S12", version: "1.0.0", schema: "c5.capability-descriptor.schema.json", consumers: &["S1", "S2", "S3", "S4", "S5", "S7", "S9", "S10", "S11"] },
    Contract { id: "C6", name: "Compute Adapter Tool Interface", owner: "S7", version: "1.0.0", schema: "c6.compute-adapter.schema.json", consumers: &["S1", "S2", "S3", "S5", "S6", "S10", "S11", "S12"] },
];

pub fn contract_by_id(id: &str) -> Option<&'static Contract> {
    CONTRACTS.iter().find(|contract| contract.id == id)
}
