// Generated by scripts/generate_bindings.py; do not edit.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

pub const C10_SCHEMA_SHA256: &str = "sha256:9024e26bed52046bf608ea972937683e796d79220fbdce5b4933c479ae7f044f";

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuntimeClass {
    Auto,
    Gvisor,
    Firecracker,
    Docker,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RiskClass {
    Standard,
    Federated,
    High,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum SandboxState {
    Admitted,
    Running,
    Succeeded,
    Failed,
    TimedOut,
    Frozen,
    Terminated,
    Quarantined,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BudgetCaps {
    pub max_compute_units: f64,
    pub max_gpu_seconds: f64,
    pub max_model_tokens: f64,
    pub max_wallclock_s: f64,
    pub max_cost_usd: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BudgetUsage {
    pub compute_units: f64,
    pub gpu_seconds: f64,
    pub model_tokens: f64,
    pub wallclock_s: f64,
    pub cost_usd: f64,
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct EgressRule {
    pub host: String,
    pub port: u16,
    pub proto: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ScopeGrant {
    pub allowed_adapters: Vec<String>,
    pub allowed_datasets: Vec<String>,
    pub egress_allowlist: Vec<EgressRule>,
    pub broker_audiences: Vec<String>,
    pub capabilities: Vec<String>,
    pub producer_subsystems: Vec<String>,
    pub sandbox_risk_class: RiskClass,
    pub disallowed_actions: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BudgetToken {
    pub budget_id: String,
    pub job_id: String,
    pub root_request_id: String,
    pub budget_epoch: u64,
    pub caps: BudgetCaps,
    pub risk_class: RiskClass,
    pub issued_at: u64,
    pub expires_at: u64,
    pub ttl_s: u64,
    pub parent_budget_id: Option<String>,
    pub signer_key_id: String,
    pub signature: String,
}

impl BudgetToken {
    pub fn validate(&self) -> Result<(), &'static str> {
        if self.budget_epoch == 0 {
            return Err("budget_epoch must be positive");
        }
        if !is_token_signature(&self.signature) {
            return Err("budget signature must be hmac-sha256 or ed25519");
        }
        Ok(())
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ScopeToken {
    pub scope_id: String,
    pub job_id: String,
    pub scopes: ScopeGrant,
    pub issued_at: u64,
    pub expires_at: u64,
    pub ttl_s: u64,
    pub parent_scope_id: Option<String>,
    pub signer_key_id: String,
    pub signature: String,
}

impl ScopeToken {
    pub fn validate(&self) -> Result<(), &'static str> {
        if !is_token_signature(&self.signature) {
            return Err("scope signature must be hmac-sha256 or ed25519");
        }
        Ok(())
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ResourceCeilings {
    pub cpu_m: u64,
    pub mem_bytes: u64,
    pub gpu_count: u64,
    pub wallclock_s: u64,
    pub max_cost_usd: f64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExfilThresholds {
    pub soft_bytes: u64,
    pub hard_bytes: u64,
}

impl ExfilThresholds {
    pub fn validate(&self) -> Result<(), &'static str> {
        if self.soft_bytes == 0 || self.hard_bytes <= self.soft_bytes {
            return Err("exfil hard_bytes must be greater than positive soft_bytes");
        }
        Ok(())
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PolicyBundle {
    pub bundle_version: String,
    pub egress_allowlist: Vec<EgressRule>,
    pub exfil_thresholds: ExfilThresholds,
    pub resource_ceilings: ResourceCeilings,
    pub risk_to_runtime: BTreeMap<String, RuntimeClass>,
    pub seccomp_profile_hash: String,
    pub signer_key_id: String,
    pub signature: String,
}

impl PolicyBundle {
    pub fn validate(&self) -> Result<(), &'static str> {
        if !is_blake3_hash(&self.seccomp_profile_hash) {
            return Err("seccomp_profile_hash must be a BLAKE3 hash");
        }
        if !is_hmac_sha256_signature(&self.signature) {
            return Err("policy signature must be hmac-sha256");
        }
        if self.risk_to_runtime.is_empty() {
            return Err("risk_to_runtime must not be empty");
        }
        self.exfil_thresholds.validate()?;
        Ok(())
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LaunchEnvelope {
    pub cpu_m: u64,
    pub mem_bytes: u64,
    pub gpu_count: u64,
    pub wallclock_s: u64,
    pub scratch_bytes: u64,
    pub pids: u64,
    pub estimated_cost_usd: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LaunchRequest {
    pub job_id: String,
    pub subagent_id: String,
    pub trace_id: String,
    pub budget_token: BudgetToken,
    pub scope_token: ScopeToken,
    pub image: String,
    pub entrypoint: Vec<String>,
    pub args: Vec<String>,
    pub env: BTreeMap<String, String>,
    pub env_allowlist: Vec<String>,
    pub requested_envelope: LaunchEnvelope,
    pub runtime_class_hint: RuntimeClass,
    pub policy_pin: Option<String>,
}

impl LaunchRequest {
    pub fn validate(&self) -> Result<(), &'static str> {
        if !is_digest_pinned_image(&self.image) {
            return Err("image must be digest pinned");
        }
        self.budget_token.validate()?;
        self.scope_token.validate()?;
        if self.budget_token.job_id != self.job_id || self.scope_token.job_id != self.job_id {
            return Err("tokens must be bound to launch job_id");
        }
        Ok(())
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PolicyVerdict {
    pub allowed: bool,
    pub runtime_class: Option<RuntimeClass>,
    pub egress_acl: Vec<EgressRule>,
    pub deny_reason: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SandboxHandle {
    pub sandbox_id: String,
    pub job_id: String,
    pub runtime_class: RuntimeClass,
    pub budget_epoch: u64,
    pub policy_bundle_version: String,
    pub state: SandboxState,
    pub launch_provenance_ref: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SandboxPartialResult {
    pub reason: String,
    pub stdout: String,
    pub stderr: String,
    pub captured_after_freeze: bool,
    pub freeze_succeeded: bool,
    pub terminate_succeeded: bool,
    pub stdout_bytes: u64,
    pub stderr_bytes: u64,
    pub log_capture_limit_bytes: u64,
    pub logs_truncated: bool,
    pub frozen_state: SandboxState,
    pub terminated_state: SandboxState,
    pub capture_error: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SandboxExecutionResult {
    pub handle: SandboxHandle,
    pub exit_code: Option<i32>,
    pub stdout: String,
    pub stderr: String,
    pub timed_out: bool,
    pub duration_s: f64,
    pub budget_usage: BudgetUsage,
    pub partial_result: Option<SandboxPartialResult>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct QuotaState {
    pub caps: BudgetCaps,
    pub reserved: BudgetUsage,
    pub actual: BudgetUsage,
    pub halted: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AuditEvent {
    pub sequence: u64,
    pub event_type: String,
    pub payload: serde_json::Value,
    pub previous_hash: String,
    pub event_hash: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EgressDecision {
    pub allowed: bool,
    pub reason: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StoreBrokerHandle {
    pub handle_id: String,
    pub scope_id: String,
    pub expires_at: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct S8CheckpointSignature {
    pub sequence: u64,
    pub root: String,
    pub signature: String,
    pub signer_key_id: String,
}

pub fn is_digest_pinned_image(image: &str) -> bool {
    let digest = if let Some(value) = image.strip_prefix("sha256:") {
        value
    } else if let Some((_, value)) = image.rsplit_once("@sha256:") {
        value
    } else {
        return false;
    };
    is_lower_hex_digest(digest, 64)
}

pub fn is_hmac_sha256_signature(signature: &str) -> bool {
    signature
        .strip_prefix("hmac-sha256:")
        .is_some_and(|digest| is_lower_hex_digest(digest, 64))
}

pub fn is_token_signature(signature: &str) -> bool {
    is_hmac_sha256_signature(signature)
        || signature
            .strip_prefix("ed25519:")
            .is_some_and(|digest| is_lower_hex_digest(digest, 128))
}

pub fn is_blake3_hash(value: &str) -> bool {
    value
        .strip_prefix("blake3:")
        .is_some_and(|digest| is_lower_hex_digest(digest, 64))
}

fn is_lower_hex_digest(value: &str, expected_len: usize) -> bool {
    value.len() == expected_len
        && value
            .as_bytes()
            .iter()
            .all(|byte| matches!(byte, b'0'..=b'9' | b'a'..=b'f'))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn launch_request_json() -> &'static str {
        r#"{
            "job_id": "job-s10-golden",
            "subagent_id": "subagent-s10-golden",
            "trace_id": "trace-s10-golden",
            "budget_token": {
                        "budget_id": "budget-s10-golden",
                        "job_id": "job-s10-golden",
                        "root_request_id": "root-s10-golden",
                        "budget_epoch": 1,
                        "caps": {
                                    "max_compute_units": 10,
                                    "max_gpu_seconds": 0,
                                    "max_model_tokens": 1000,
                                    "max_wallclock_s": 60,
                                    "max_cost_usd": 1.5
                        },
                        "risk_class": "standard",
                        "issued_at": 1782921600,
                        "expires_at": 1782925200,
                        "ttl_s": 3600,
                        "parent_budget_id": null,
                        "signer_key_id": "s10-key",
                        "signature": "hmac-sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
            },
            "scope_token": {
                        "scope_id": "scope-s10-golden",
                        "job_id": "job-s10-golden",
                        "scopes": {
                                    "allowed_adapters": [
                                                "adapter:toy-solver"
                                    ],
                                    "allowed_datasets": [
                                                "c4://dataset/golden"
                                    ],
                                    "egress_allowlist": [
                                                {
                                                            "host": "store.local",
                                                            "port": 443,
                                                            "proto": "https"
                                                }
                                    ],
                                    "broker_audiences": [
                                                "store",
                                                "adapter:toy-solver"
                                    ],
                                    "capabilities": [
                                                "s8.read"
                                    ],
                                    "producer_subsystems": [
                                                "S2"
                                    ],
                                    "sandbox_risk_class": "standard",
                                    "disallowed_actions": [
                                                "direct_store_write"
                                    ]
                        },
                        "issued_at": 1782921600,
                        "expires_at": 1782925200,
                        "ttl_s": 3600,
                        "parent_scope_id": null,
                        "signer_key_id": "s10-key",
                        "signature": "hmac-sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
            },
            "image": "ghcr.io/project-argus/sandbox@sha256:1111111111111111111111111111111111111111111111111111111111111111",
            "entrypoint": [
                        "/bin/sh"
            ],
            "args": [
                        "-lc",
                        "echo argus"
            ],
            "env": {
                        "ARGUS_MODE": "golden"
            },
            "env_allowlist": [
                        "ARGUS_MODE"
            ],
            "requested_envelope": {
                        "cpu_m": 250,
                        "mem_bytes": 134217728,
                        "gpu_count": 0,
                        "wallclock_s": 30,
                        "scratch_bytes": 1048576,
                        "pids": 32,
                        "estimated_cost_usd": 0.01
            },
            "runtime_class_hint": "auto",
            "policy_pin": null
}"#
    }

    fn policy_bundle_json() -> &'static str {
        r#"{
            "bundle_version": "1.0.0",
            "egress_allowlist": [
                        {
                                    "host": "store.local",
                                    "port": 443,
                                    "proto": "https"
                        }
            ],
            "exfil_thresholds": {
                        "soft_bytes": 67108864,
                        "hard_bytes": 134217728
            },
            "resource_ceilings": {
                        "cpu_m": 1000,
                        "mem_bytes": 536870912,
                        "gpu_count": 0,
                        "wallclock_s": 120,
                        "max_cost_usd": 2.0
            },
            "risk_to_runtime": {
                        "standard": "gvisor",
                        "federated": "firecracker",
                        "high": "firecracker"
            },
            "seccomp_profile_hash": "blake3:af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
            "signer_key_id": "s10-policy-key",
            "signature": "hmac-sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
}"#
    }

    #[test]
    fn c10_schema_digest_is_generated() {
        assert!(C10_SCHEMA_SHA256.starts_with("sha256:"));
    }

    #[test]
    fn serde_round_trips_s10_launch_request_golden_sample() {
        let request: LaunchRequest =
            serde_json::from_str(launch_request_json()).expect("deserialize launch request");
        request.validate().expect("launch request validates");
        let encoded = serde_json::to_string(&request).expect("serialize launch request");
        let decoded: LaunchRequest = serde_json::from_str(&encoded).expect("deserialize roundtrip");
        assert_eq!(decoded, request);
    }

    #[test]
    fn serde_round_trips_s10_policy_bundle_golden_sample() {
        let bundle: PolicyBundle =
            serde_json::from_str(policy_bundle_json()).expect("deserialize policy bundle");
        bundle.validate().expect("policy bundle validates");
        assert_eq!(
            bundle.risk_to_runtime.get("standard"),
            Some(&RuntimeClass::Gvisor)
        );
    }

    #[test]
    fn digest_pinned_image_validation_rejects_tag_only_images() {
        assert!(is_digest_pinned_image(
            "ghcr.io/project-argus/sandbox@sha256:1111111111111111111111111111111111111111111111111111111111111111"
        ));
        assert!(!is_digest_pinned_image("busybox:latest"));
    }
}
