"""Generated by scripts/generate_bindings.py; do not edit."""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Any, Literal, Mapping

from pydantic import BaseModel, ConfigDict, Field, ValidationError, field_validator, model_validator


C1_SCHEMA_SHA256 = "sha256:70de039b4c9687e9ce83ed5dc0ff444c681dd068cf79b8c1d6138bfd9c4b56d5"

Uuid = Annotated[
    str,
    Field(
        pattern=r"^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    ),
]
ArtifactRef = Annotated[str, Field(pattern=r"^c4://[A-Za-z0-9._:/-]+$")]
HashRef = Annotated[str, Field(pattern=r"^(blake3|c4):[A-Za-z0-9._:/-]+$")]
LifecycleState = Literal[
    "REGISTERED",
    "ACCEPTED",
    "PLANNING",
    "BUILDING",
    "VALIDATING",
    "REPORTED",
    "FAILED",
    "REJECTED",
    "CANCELLED",
    "QUARANTINED",
]
LifecycleMethod = Literal[
    "register",
    "accept",
    "refuse",
    "plan",
    "build",
    "validate",
    "report",
    "heartbeat",
    "cancel",
    "fail",
    "quarantine",
]
ClaimTier = Literal["ran-toy", "recapitulated-known", "novel-needs-human"]
ErrorCategory = Literal[
    "RETRYABLE",
    "PERMANENT",
    "BUDGET",
    "POLICY",
    "VERIFIER_UNAVAILABLE",
    "SANDBOX",
    "VALIDATION",
    "VERSION_UNSUPPORTED",
    "QUARANTINE",
    "NOT_FOUND",
]


class CostEstimate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    compute_units: float | None = Field(default=None, ge=0)
    gpu_seconds: float | None = Field(default=None, ge=0)
    model_tokens: float | None = Field(default=None, ge=0)
    cost_usd: float = Field(ge=0)


class UncertaintySummary(BaseModel):
    model_config = ConfigDict(extra="forbid")

    representation: Literal["covariance", "interval", "samples", "conformal", "ensemble", "none"]
    value: dict[str, Any]


class SelfCheck(BaseModel):
    model_config = ConfigDict(extra="forbid")

    type: str = Field(min_length=1)
    status: Literal["PASS", "FAIL", "INCONCLUSIVE"]
    advisory: bool
    evidence_ref: ArtifactRef | None = None


class TypedError(BaseModel):
    model_config = ConfigDict(extra="forbid")

    category: ErrorCategory
    code: str = Field(min_length=1)
    message: str = Field(min_length=1)
    retryable: bool
    retry_after_seconds: int | None = Field(default=None, ge=0)
    provenance_ref: ArtifactRef | None = None

    @model_validator(mode="after")
    def _retryable_requires_retry_after(self) -> TypedError:
        if self.retryable and self.retry_after_seconds is None:
            raise ValueError("retryable errors require retry_after_seconds")
        return self


class SubagentEnvelope(BaseModel):
    model_config = ConfigDict(extra="forbid")

    contract_version: Annotated[str, Field(pattern=r"^1\.\d+\.\d+$")]
    method: LifecycleMethod
    job_id: Uuid
    trace_id: str = Field(min_length=1)
    state: LifecycleState
    idempotency_key: str = Field(min_length=1)
    capability_descriptor_ref: ArtifactRef | None = None
    job_envelope_ref: ArtifactRef | None = None
    payload: dict[str, Any] | None = None


class Acceptance(BaseModel):
    model_config = ConfigDict(extra="forbid")

    job_id: Uuid
    accepted: bool
    reason: Literal[
        "OUT_OF_SCOPE",
        "MISSING_ADAPTER",
        "BUDGET_TOO_SMALL",
        "NO_VERIFIER",
        "VERSION_UNSUPPORTED",
        "POLICY",
    ] | None = None
    state: Literal["ACCEPTED", "REJECTED"]
    estimated_cost: CostEstimate | None = None
    plan_eta_seconds: int | None = Field(default=None, ge=0)
    idempotency_key: str = Field(min_length=1)

    @model_validator(mode="after")
    def _state_and_reason_match_acceptance(self) -> Acceptance:
        if self.accepted:
            if self.state != "ACCEPTED" or self.reason is not None:
                raise ValueError("accepted Acceptance must have state ACCEPTED and reason null")
        else:
            if self.state != "REJECTED" or self.reason is None:
                raise ValueError("refused Acceptance must have state REJECTED and a reason")
        return self


class PlanStep(BaseModel):
    model_config = ConfigDict(extra="forbid")

    step_id: str = Field(min_length=1)
    kind: Literal["feature", "train", "eval", "selfcheck", "freeze"]
    description: str = Field(min_length=1)
    est_cost: CostEstimate


class BudgetBreakdown(BaseModel):
    model_config = ConfigDict(extra="forbid")

    per_step: list[CostEstimate] | None = None
    total: CostEstimate


class Plan(BaseModel):
    model_config = ConfigDict(extra="forbid")

    job_id: Uuid
    steps: list[PlanStep] = Field(min_length=1)
    adapters_required: list[str]
    datasets_required: list[ArtifactRef]
    verifier_profile_ref: ArtifactRef
    budget_breakdown: BudgetBreakdown
    risk_notes: list[str]
    plan_hash: HashRef


class BuildResult(BaseModel):
    model_config = ConfigDict(extra="forbid")

    job_id: Uuid
    artifact_refs: list[ArtifactRef] = Field(min_length=1)
    training_log_ref: ArtifactRef | None = None
    diagnostics: dict[str, Any]
    self_checks: list[SelfCheck]
    uncertainty_summary: UncertaintySummary


class ValidationRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    job_id: Uuid
    frozen_pipeline_ref: ArtifactRef
    artifact_refs: list[ArtifactRef]
    profile_ref: ArtifactRef
    blind_dataset_handle: str = Field(min_length=1)
    budget_token_ref: str = Field(min_length=1)
    trace_id: str = Field(min_length=1)


class ReproducibilityManifest(BaseModel):
    model_config = ConfigDict(extra="allow")

    lineage_ref: ArtifactRef
    environment_digest: str = Field(min_length=1)
    code_ref: str = Field(min_length=1)
    seeds: list[str]


class SubagentReport(BaseModel):
    model_config = ConfigDict(extra="forbid")

    job_id: Uuid
    subagent_id: str = Field(min_length=1)
    status: Literal["REPORTED", "FAILED", "REJECTED", "CANCELLED", "QUARANTINED"]
    claim_tier: ClaimTier
    artifact_refs: list[ArtifactRef]
    validation_report_ref: ArtifactRef | None = None
    uncertainty_summary: UncertaintySummary | None = None
    cost_actual: CostEstimate
    reproducibility_manifest: ReproducibilityManifest
    error: TypedError | None = None

    @model_validator(mode="after")
    def _promoted_tier_requires_validation_report(self) -> SubagentReport:
        if self.claim_tier in {"recapitulated-known", "novel-needs-human"} and self.validation_report_ref is None:
            raise ValueError("promoted claim_tier requires validation_report_ref")
        return self


class LifecycleEvent(BaseModel):
    model_config = ConfigDict(extra="forbid")

    event_id: Uuid
    job_id: Uuid
    root_request_id: Uuid
    seq: int = Field(ge=1)
    from_state: LifecycleState
    to_state: LifecycleState
    method: LifecycleMethod
    trigger: Literal["S5", "S4", "internal", "cancel"]
    payload_hash: HashRef
    spend_delta: CostEstimate | None = None
    trace_id: str = Field(min_length=1)
    idempotency_key: str = Field(min_length=1)
    ledger_ref: ArtifactRef | None = None


class Heartbeat(BaseModel):
    model_config = ConfigDict(extra="forbid")

    job_id: Uuid
    status: LifecycleState
    progress: float = Field(ge=0, le=1)
    spend_so_far: CostEstimate
    last_heartbeat_at: datetime


class ExecContext(BaseModel):
    model_config = ConfigDict(extra="forbid")

    job_id: Uuid
    capabilities: list[
        Literal["submit_sandbox_job", "emit_artifact", "call_adapter", "read_dataset", "log", "span"]
    ]

    @field_validator("capabilities")
    @classmethod
    def _capabilities_are_unique(cls, value: list[str]) -> list[str]:
        if len(value) != len(set(value)):
            raise ValueError("capabilities must be unique")
        return value


C1_PAYLOAD_MODELS: tuple[type[BaseModel], ...] = (
    SubagentEnvelope,
    Acceptance,
    Plan,
    BuildResult,
    ValidationRequest,
    SubagentReport,
    LifecycleEvent,
    Heartbeat,
    TypedError,
)


def validate_subagent_envelope(payload: Mapping[str, Any]) -> SubagentEnvelope:
    return SubagentEnvelope.model_validate(payload)


def validate_acceptance(payload: Mapping[str, Any]) -> Acceptance:
    return Acceptance.model_validate(payload)


def validate_c1_payload(payload: Mapping[str, Any]) -> BaseModel:
    errors: list[ValidationError] = []
    for model in C1_PAYLOAD_MODELS:
        try:
            return model.model_validate(payload)
        except ValidationError as exc:
            errors.append(exc)
    raise ValueError(f"payload did not match any C1 public model ({len(errors)} validation attempts)")
