"""Generated by scripts/generate_bindings.py; do not edit."""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Any, Literal, Mapping

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


C4_SCHEMA_SHA256 = "sha256:32d5caf1f5f57b4c1da2eb7dc81e31f7423c834f6945e3839ffc6356fc4d35de"

ArtifactRef = Annotated[str, Field(pattern=r"^c4://[A-Za-z0-9._:/-]+$")]
HashRef = Annotated[str, Field(pattern=r"^blake3:[a-f0-9]{64}$")]
ClaimTier = Literal["ran-toy", "recapitulated-known", "novel-needs-human"]


class Producer(BaseModel):
    model_config = ConfigDict(extra="forbid")

    subsystem: str = Field(pattern=r"^S\d+$")
    version: str = Field(pattern=r"^\d+\.\d+\.\d+$")


class Lineage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    input_refs: list[ArtifactRef]
    code_ref: str = Field(min_length=1)
    environment_digest: str = Field(min_length=1)
    seeds: list[str]

    @field_validator("input_refs")
    @classmethod
    def _input_refs_are_unique(cls, value: list[str]) -> list[str]:
        if len(value) != len(set(value)):
            raise ValueError("input_refs must be unique")
        return value

    @field_validator("seeds")
    @classmethod
    def _seeds_are_unique(cls, value: list[str]) -> list[str]:
        if len(value) != len(set(value)):
            raise ValueError("seeds must be unique")
        return value


class RetentionPolicy(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    class_: Literal["write_once", "scratch", "hold"] | None = Field(default=None, alias="class")
    retain_until: datetime | None = None
    hold_id: str | None = Field(default=None, min_length=1)


class ArtifactRecord(BaseModel):
    model_config = ConfigDict(extra="forbid")

    artifact_ref: ArtifactRef
    kind: str = Field(min_length=1)
    content_hash: HashRef
    hash_algorithm: Literal["BLAKE3"]
    size_bytes: int = Field(ge=0)
    created_at: datetime
    producer: Producer
    lineage: Lineage
    claim_tier: ClaimTier | None = None
    validation_report_ref: ArtifactRef | None = None
    schema_ref: str | None = None
    retention: RetentionPolicy | None = None

    @model_validator(mode="after")
    def _promoted_tier_requires_validation_report(self) -> ArtifactRecord:
        if self.claim_tier in {"recapitulated-known", "novel-needs-human"} and self.validation_report_ref is None:
            raise ValueError("promoted claim_tier requires validation_report_ref")
        return self


def validate_artifact_record(payload: Mapping[str, Any]) -> ArtifactRecord:
    return ArtifactRecord.model_validate(payload)
