"""Generated by scripts/generate_bindings.py; do not edit."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Contract:
    id: str
    name: str
    owner: str
    version: str
    schema: str
    schema_sha256: str
    consumers: list[str]


CONTRACTS: tuple[Contract, ...] = (
    Contract(id="C1", name="Subagent Contract", owner="S1", version="1.0.0", schema="c1.subagent.schema.json", schema_sha256="sha256:bec647eec1f70625af766a1dd67f6bf81990d80d1b414b4c74f4254ca62ff7ab", consumers=["S2", "S3", "S4", "S5", "S11", "S12"]),
    Contract(id="C2", name="Task Job Envelope", owner="S5", version="1.0.0", schema="c2.job-envelope.schema.json", schema_sha256="sha256:62695e9f6e4cda8ab9f9089d595f36ca3cf395e0f40100be35938a838b334360", consumers=["S1", "S2", "S3", "S4", "S7", "S9", "S10", "S11", "S12"]),
    Contract(id="C3", name="Verifier Interface and Validation Report", owner="S3", version="1.1.0", schema="c3.validation-report.schema.json", schema_sha256="sha256:e0c8cd14a6bf287c75c5fb5999b425b76e020569ef47da4a0991043737bfd123", consumers=["S1", "S2", "S4", "S5", "S7", "S8", "S9", "S11", "S12"]),
    Contract(id="C4", name="Artifact and Provenance Record", owner="S8", version="1.0.0", schema="c4.artifact-record.schema.json", schema_sha256="sha256:32d5caf1f5f57b4c1da2eb7dc81e31f7423c834f6945e3839ffc6356fc4d35de", consumers=["S1", "S2", "S3", "S4", "S5", "S6", "S7", "S9", "S10", "S11", "S12"]),
    Contract(id="C5", name="Registry Capability Descriptor", owner="S6/S12", version="1.0.0", schema="c5.capability-descriptor.schema.json", schema_sha256="sha256:250713686bbebeb2ee5b146678a97bfabf9170b953a3368209f5cc40c2bef2c8", consumers=["S1", "S2", "S3", "S4", "S5", "S7", "S9", "S10", "S11"]),
    Contract(id="C6", name="Compute Adapter Tool Interface", owner="S7", version="1.0.0", schema="c6.compute-adapter.schema.json", schema_sha256="sha256:f8146179c942b7c4c7b984785c32b2cb2f896eed71207ea19fcf3424bdd8f102", consumers=["S1", "S2", "S3", "S5", "S6", "S10", "S11", "S12"])
)

CONTRACT_BY_ID: dict[str, Contract] = {contract.id: contract for contract in CONTRACTS}
