"""Generated by scripts/generate_bindings.py; do not edit."""

from __future__ import annotations

from typing import Annotated, Any, Literal, Mapping

from pydantic import BaseModel, ConfigDict, Field, field_validator


C10_SCHEMA_SHA256 = "sha256:6d3ec4964f831f9fd2e281248080f30630d2b3e75d1ffd8d1a0a7009d74c5506"

ArtifactRef = Annotated[str, Field(pattern=r"^c4://[A-Za-z0-9._:/-]+$")]
HashRef = Annotated[str, Field(pattern=r"^blake3:[a-f0-9]{64}$")]
Signature = Annotated[str, Field(pattern=r"^hmac-sha256:[a-f0-9]{64}$")]
DigestPinnedImage = Annotated[str, Field(pattern=r"^(?:[^\s@]+@)?sha256:[0-9a-f]{64}$")]
RuntimeClass = Literal["auto", "gvisor", "firecracker", "docker"]
RiskClass = Literal["standard", "federated", "high"]
SandboxState = Literal[
    "ADMITTED",
    "RUNNING",
    "SUCCEEDED",
    "FAILED",
    "TIMED_OUT",
    "FROZEN",
    "TERMINATED",
    "QUARANTINED",
]


class BudgetCaps(BaseModel):
    model_config = ConfigDict(extra="forbid")

    max_compute_units: float = Field(ge=0)
    max_gpu_seconds: float = Field(ge=0)
    max_model_tokens: float = Field(ge=0)
    max_wallclock_s: float = Field(ge=0)
    max_cost_usd: float = Field(ge=0)


class BudgetUsage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    compute_units: float = Field(ge=0)
    gpu_seconds: float = Field(ge=0)
    model_tokens: float = Field(ge=0)
    wallclock_s: float = Field(ge=0)
    cost_usd: float = Field(ge=0)


class EgressRule(BaseModel):
    model_config = ConfigDict(extra="forbid")

    host: str = Field(min_length=1)
    port: int = Field(ge=1, le=65535)
    proto: Literal["https", "grpc", "tcp"]


class ScopeGrant(BaseModel):
    model_config = ConfigDict(extra="forbid")

    allowed_adapters: list[str]
    allowed_datasets: list[ArtifactRef]
    egress_allowlist: list[EgressRule]
    broker_audiences: list[str]
    producer_subsystems: list[Annotated[str, Field(pattern=r"^S\d+$")]]
    sandbox_risk_class: RiskClass
    disallowed_actions: list[str]

    @field_validator(
        "allowed_adapters",
        "allowed_datasets",
        "egress_allowlist",
        "broker_audiences",
        "producer_subsystems",
        "disallowed_actions",
    )
    @classmethod
    def _items_are_unique(cls, value: list[Any]) -> list[Any]:
        normalized = [item.model_dump_json() if isinstance(item, BaseModel) else str(item) for item in value]
        if len(normalized) != len(set(normalized)):
            raise ValueError("array items must be unique")
        return value


class BudgetToken(BaseModel):
    model_config = ConfigDict(extra="forbid")

    budget_id: str = Field(min_length=1)
    job_id: str = Field(min_length=1)
    root_request_id: str = Field(min_length=1)
    budget_epoch: int = Field(ge=1)
    caps: BudgetCaps
    risk_class: RiskClass
    issued_at: int = Field(ge=0)
    expires_at: int = Field(ge=0)
    ttl_s: int = Field(ge=1)
    parent_budget_id: str | None
    signer_key_id: str = Field(min_length=1)
    signature: Signature


class ScopeToken(BaseModel):
    model_config = ConfigDict(extra="forbid")

    scope_id: str = Field(min_length=1)
    job_id: str = Field(min_length=1)
    scopes: ScopeGrant
    issued_at: int = Field(ge=0)
    expires_at: int = Field(ge=0)
    ttl_s: int = Field(ge=1)
    parent_scope_id: str | None
    signer_key_id: str = Field(min_length=1)
    signature: Signature


class ResourceCeilings(BaseModel):
    model_config = ConfigDict(extra="forbid")

    cpu_m: int = Field(ge=1)
    mem_bytes: int = Field(ge=1)
    gpu_count: int = Field(ge=0)
    wallclock_s: int = Field(ge=1)
    max_cost_usd: float = Field(ge=0)


class PolicyBundle(BaseModel):
    model_config = ConfigDict(extra="forbid")

    bundle_version: Annotated[str, Field(pattern=r"^\d+\.\d+\.\d+$")]
    egress_allowlist: list[EgressRule]
    resource_ceilings: ResourceCeilings
    risk_to_runtime: dict[RiskClass, RuntimeClass]
    seccomp_profile_hash: HashRef
    signer_key_id: str = Field(min_length=1)
    signature: Signature


class LaunchEnvelope(BaseModel):
    model_config = ConfigDict(extra="forbid")

    cpu_m: int = Field(ge=1)
    mem_bytes: int = Field(ge=1)
    gpu_count: int = Field(ge=0)
    wallclock_s: int = Field(ge=1)
    scratch_bytes: int = Field(ge=0)
    pids: int = Field(ge=1)
    estimated_cost_usd: float = Field(ge=0)


class LaunchRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    job_id: str = Field(min_length=1)
    subagent_id: str = Field(min_length=1)
    trace_id: str = Field(min_length=1)
    budget_token: BudgetToken
    scope_token: ScopeToken
    image: DigestPinnedImage
    entrypoint: list[str]
    args: list[str]
    env: dict[str, str]
    env_allowlist: list[Annotated[str, Field(pattern=r"^[A-Z_][A-Z0-9_]*$")]]
    requested_envelope: LaunchEnvelope
    runtime_class_hint: RuntimeClass
    policy_pin: str | None

    @field_validator("env_allowlist")
    @classmethod
    def _env_allowlist_is_unique(cls, value: list[str]) -> list[str]:
        if len(value) != len(set(value)):
            raise ValueError("env_allowlist must contain unique values")
        return value


class PolicyVerdict(BaseModel):
    model_config = ConfigDict(extra="forbid")

    allowed: bool
    runtime_class: RuntimeClass | None
    egress_acl: list[EgressRule]
    deny_reason: str | None


class SandboxHandle(BaseModel):
    model_config = ConfigDict(extra="forbid")

    sandbox_id: str = Field(min_length=1)
    job_id: str = Field(min_length=1)
    runtime_class: RuntimeClass
    budget_epoch: int = Field(ge=1)
    policy_bundle_version: Annotated[str, Field(pattern=r"^\d+\.\d+\.\d+$")]
    state: SandboxState
    launch_provenance_ref: ArtifactRef | None


class SandboxExecutionResult(BaseModel):
    model_config = ConfigDict(extra="forbid")

    handle: SandboxHandle
    exit_code: int | None
    stdout: str
    stderr: str
    timed_out: bool
    duration_s: float = Field(ge=0)
    budget_usage: BudgetUsage


class QuotaState(BaseModel):
    model_config = ConfigDict(extra="forbid")

    caps: BudgetCaps
    reserved: BudgetUsage
    actual: BudgetUsage
    halted: bool


class AuditEvent(BaseModel):
    model_config = ConfigDict(extra="forbid")

    sequence: int = Field(ge=1)
    event_type: str = Field(min_length=1)
    payload: dict[str, Any]
    previous_hash: HashRef
    event_hash: HashRef


class EgressDecision(BaseModel):
    model_config = ConfigDict(extra="forbid")

    allowed: bool
    reason: str


class StoreBrokerHandle(BaseModel):
    model_config = ConfigDict(extra="forbid")

    handle_id: str = Field(min_length=1)
    scope_id: str = Field(min_length=1)
    expires_at: int = Field(ge=0)


class S8CheckpointSignature(BaseModel):
    model_config = ConfigDict(extra="forbid")

    sequence: int = Field(ge=1)
    root: HashRef
    signature: Signature
    signer_key_id: str = Field(min_length=1)


def validate_launch_request(payload: Mapping[str, Any]) -> LaunchRequest:
    return LaunchRequest.model_validate(payload)


def validate_policy_bundle(payload: Mapping[str, Any]) -> PolicyBundle:
    return PolicyBundle.model_validate(payload)
