// Generated by scripts/generate_bindings.py; do not edit.

import assert from "node:assert/strict";

import {
  InMemoryVerifierTrustStore,
  SIGNATURE_VERIFICATION_ABSTAIN,
  SIGNATURE_VERIFICATION_ACCEPTED,
  type SignatureVerificationDelegationResult,
  type VerifierKey,
  signReport,
  verifyReport,
} from "../src/argusverify.js";

const report = {
  "report_id": "33333333-3333-4333-8333-333333333333",
  "profile_ref": "c4://profile/ewpt-toy/v1",
  "frozen_pipeline_ref": "c4://pipeline/ewpt-toy/baseline",
  "checks": [
    {
      "check": "INJECTION",
      "status": "PASS",
      "metrics": {
        "recovery_rate": 0.98,
        "integer_float": 1.0,
        "zero_float": 0.0,
        "z_max": 3.0,
        "tiny_signal": 1e-07,
        "micro_signal": 1e-06,
        "large_fixed": 1e+20,
        "large_exponent": 1e+21
      },
      "evidence_refs": [
        "c4://evidence/injection/example"
      ]
    }
  ],
  "aggregate": {
    "passed": true,
    "score": 1.0
  },
  "claim_tier": "recapitulated-known",
  "claim_tier_is_candidate": false,
  "perturbation_pairs": [],
  "insensitivity_flags": [],
  "challenger_panel": {
    "challenger_ids": [
      "challenger-a",
      "challenger-b"
    ],
    "min_required": 2
  },
  "independence_attestation_debate": {
    "min_independent_challengers": 2,
    "lineage_disjoint": true,
    "correlation_warning": false
  },
  "referee": {
    "referee_id": "s3-referee",
    "non_gameable": true,
    "signed_by": "s3-key",
    "distinct_from_proponent": true
  },
  "debate_ref": "c4://debate/ewpt-toy/example"
} as Record<string, unknown>;
const expectedSignature = "hmac-sha256:49bb4f2abf5cf349d510031b6838e527f663c7b7c844cccf2487609c1da9cc54";

const trustStore = new InMemoryVerifierTrustStore();
trustStore.registerKey("s3-key", "s3-secret");

const signed = signReport(report, { keyId: "s3-key", secret: "s3-secret" });
assert.equal((signed.signature as Record<string, unknown>).value, expectedSignature);

const valid = verifyReport(signed, trustStore);
assert.equal(valid.valid, true);
assert.equal(valid.claim_tier, "recapitulated-known");
assert.equal(valid.aggregate_passed, true);

trustStore.registerKey("s3-key-v2", "s3-secret-v2");
const archivedAfterRotation = verifyReport(signed, trustStore);
assert.equal(archivedAfterRotation.valid, true);
const signedV2 = signReport(report, { keyId: "s3-key-v2", secret: "s3-secret-v2" });
assert.equal(verifyReport(signedV2, trustStore).key_id, "s3-key-v2");

const tampered = JSON.parse(JSON.stringify(signed)) as Record<string, unknown>;
(tampered.aggregate as Record<string, unknown>).score = 0.99;
const tamperedVerification = verifyReport(tampered, trustStore);
assert.equal(tamperedVerification.valid, false);
assert.equal(tamperedVerification.error_code, "SIGNATURE_INVALID");

class SecretlessDelegatingTrustStore {
  getKey(keyId: string): VerifierKey | undefined {
    if (keyId !== "s3-key") {
      return undefined;
    }
    return { key_id: keyId, secret: "" };
  }

  verifySignatureValue(args: {
    key_id: string;
    report_with_empty_signature: Record<string, unknown>;
    signature_value: string;
  }): SignatureVerificationDelegationResult {
    assert.equal(args.key_id, "s3-key");
    assert.equal((args.report_with_empty_signature.signature as Record<string, unknown>).value, "");
    if (args.signature_value === (signed.signature as Record<string, unknown>).value) {
      return SIGNATURE_VERIFICATION_ACCEPTED;
    }
    return "signature_invalid";
  }
}

const delegatedValid = verifyReport(signed, new SecretlessDelegatingTrustStore());
assert.equal(delegatedValid.valid, true);
const forgedSignature = JSON.parse(JSON.stringify(signed)) as Record<string, unknown>;
(forgedSignature.signature as Record<string, unknown>).value = "hmac-sha256:bad";
const delegatedInvalid = verifyReport(forgedSignature, new SecretlessDelegatingTrustStore());
assert.equal(delegatedInvalid.valid, false);
assert.equal(delegatedInvalid.error_code, "SIGNATURE_INVALID");

class AbstainingTrustStore {
  constructor(private readonly delegation: SignatureVerificationDelegationResult) {}

  getKey(keyId: string): VerifierKey | undefined {
    if (keyId !== "s3-key") {
      return undefined;
    }
    return { key_id: keyId, secret: "" };
  }

  verifySignatureValue(args: {
    key_id: string;
    report_with_empty_signature: Record<string, unknown>;
    signature_value: string;
  }): SignatureVerificationDelegationResult {
    assert.equal(args.key_id, "s3-key");
    assert.equal((args.report_with_empty_signature.signature as Record<string, unknown>).value, "");
    assert.equal(args.signature_value, (signed.signature as Record<string, unknown>).value);
    return this.delegation;
  }
}

for (const delegation of [undefined, SIGNATURE_VERIFICATION_ABSTAIN]) {
  const abstained = verifyReport(signed, new AbstainingTrustStore(delegation));
  assert.equal(abstained.valid, false);
  assert.equal(abstained.error_code, "SIGNATURE_INVALID");
}

const unsigned = JSON.parse(JSON.stringify(signed)) as Record<string, unknown>;
delete unsigned.signature;
const unsignedVerification = verifyReport(unsigned, trustStore);
assert.equal(unsignedVerification.valid, false);
assert.equal(unsignedVerification.error_code, "UNSIGNED");

trustStore.revokeKey("s3-key");
const revokedVerification = verifyReport(signed, trustStore);
assert.equal(revokedVerification.valid, false);
assert.equal(revokedVerification.error_code, "REVOKED_KEY");
