// Generated by scripts/generate_bindings.py; do not edit.

import assert from "node:assert/strict";

import {
  C1_SCHEMA_SHA256,
  assertAcceptance,
  assertSubagentEnvelope,
  type Acceptance,
  type SubagentEnvelope,
} from "../src/c1.js";

const envelope = {
  "contract_version": "1.0.0",
  "method": "accept",
  "job_id": "11111111-1111-4111-8111-111111111111",
  "trace_id": "trace-c1-example",
  "state": "ACCEPTED",
  "idempotency_key": "accept-11111111",
  "payload": {
    "accepted": true
  }
} satisfies SubagentEnvelope;
const acceptance: Acceptance = {
  job_id: envelope.job_id,
  accepted: true,
  reason: null,
  state: "ACCEPTED",
  idempotency_key: envelope.idempotency_key,
  estimated_cost: { cost_usd: 0.01 },
};

assert.equal(C1_SCHEMA_SHA256, "sha256:bec647eec1f70625af766a1dd67f6bf81990d80d1b414b4c74f4254ca62ff7ab");
assert.doesNotThrow(() => assertSubagentEnvelope(envelope));
assert.doesNotThrow(() => assertAcceptance(acceptance));

assert.throws(
  () => assertSubagentEnvelope({
    ...envelope,
    idempotency_key: "",
  }),
  /idempotency_key/,
);

assert.throws(
  () => assertAcceptance({
    ...acceptance,
    accepted: false,
    state: "ACCEPTED",
  }),
  /refused Acceptance/,
);
