// Generated by scripts/generate_bindings.py; do not edit.

import assert from "node:assert/strict";

import {
  ArtifactRecord,
  C4_SCHEMA_SHA256,
  CANON_VERSION,
  assertArtifactRecord,
  hashBlob,
} from "../src/c4.js";

const emptyHash = "blake3:af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262";
const vectorHash = "blake3:7e2fc64a9cc052211dfe7f54f2432c35588950f43d92bb08c87bbd182823d8d1";

const example: ArtifactRecord = {
  artifact_ref: "c4://artifact/example",
  kind: "dataset",
  content_hash: emptyHash,
  hash_algorithm: "BLAKE3",
  size_bytes: 0,
  created_at: "2026-01-01T00:00:00Z",
  producer: {
    subsystem: "S8",
    version: "1.0.0",
  },
  lineage: {
    input_refs: [],
    code_ref: "git:project-argus@example",
    environment_digest: "oci:sha256-example",
    seeds: [],
  },
};

assert.equal(C4_SCHEMA_SHA256, "sha256:32d5caf1f5f57b4c1da2eb7dc81e31f7423c834f6945e3839ffc6356fc4d35de");
assert.equal(hashBlob(new Uint8Array()).content_hash, emptyHash);
assert.equal(hashBlob(new TextEncoder().encode("argus-s8-binding-vector")).content_hash, vectorHash);
assert.equal(hashBlob(new TextEncoder().encode("argus-s8-binding-vector")).size_bytes, 23);
assert.equal(hashBlob(new Uint8Array()).canon_version, CANON_VERSION);
assert.doesNotThrow(() => assertArtifactRecord(example));

assert.throws(
  () => assertArtifactRecord({
    ...example,
    lineage: {
      input_refs: [],
      code_ref: "git:project-argus@example",
      seeds: [],
    },
  }),
  /environment_digest/,
);

assert.throws(
  () => assertArtifactRecord({
    ...example,
    claim_tier: "novel-needs-human",
  }),
  /validation_report_ref/,
);
