#!/usr/bin/env python3
"""Generate lightweight contract binding metadata from the schema manifest."""

from __future__ import annotations

import argparse
import hashlib
import hmac
import json
import math
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTRACTS_DIR = ROOT / "schemas" / "contracts"
MANIFEST_PATH = CONTRACTS_DIR / "manifest.json"
PYTHON_CONTRACTS = ROOT / "bindings" / "python" / "argus_contracts" / "contracts.py"
PYTHON_C4 = ROOT / "bindings" / "python" / "argus_contracts" / "c4.py"
PYTHON_INIT = ROOT / "bindings" / "python" / "argus_contracts" / "__init__.py"
TYPESCRIPT_PACKAGE = ROOT / "bindings" / "typescript" / "package.json"
TYPESCRIPT_CONTRACTS = ROOT / "bindings" / "typescript" / "src" / "contracts.ts"
TYPESCRIPT_C4 = ROOT / "bindings" / "typescript" / "src" / "c4.ts"
TYPESCRIPT_ARGUSVERIFY = ROOT / "bindings" / "typescript" / "src" / "argusverify.ts"
TYPESCRIPT_TSCONFIG = ROOT / "bindings" / "typescript" / "tsconfig.json"
TYPESCRIPT_C4_SMOKE = ROOT / "bindings" / "typescript" / "test" / "c4-smoke.ts"
TYPESCRIPT_ARGUSVERIFY_SMOKE = ROOT / "bindings" / "typescript" / "test" / "argusverify-smoke.ts"
RUST_MANIFEST = ROOT / "bindings" / "rust" / "Cargo.toml"
RUST_LIB = ROOT / "bindings" / "rust" / "src" / "lib.rs"
RUST_C4 = ROOT / "bindings" / "rust" / "src" / "c4.rs"
RUST_ARGUSVERIFY = ROOT / "bindings" / "rust" / "src" / "argusverify.rs"

HEADER = "Generated by scripts/generate_bindings.py; do not edit."
C3_ARGUSVERIFY_KEY_ID = "s3-key"
C3_ARGUSVERIFY_SECRET = "s3-secret"
C3_ARGUSVERIFY_VECTOR_REPORT = {
    "report_id": "33333333-3333-4333-8333-333333333333",
    "profile_ref": "c4://profile/ewpt-toy/v1",
    "frozen_pipeline_ref": "c4://pipeline/ewpt-toy/baseline",
    "checks": [
        {
            "check": "INJECTION",
            "status": "PASS",
            "metrics": {
                "recovery_rate": 0.98,
                "integer_float": 1.0,
                "zero_float": 0.0,
                "z_max": 3.0,
                "tiny_signal": 0.0000001,
                "micro_signal": 0.000001,
                "large_fixed": 1e20,
                "large_exponent": 1e21,
            },
            "evidence_refs": ["c4://evidence/injection/example"],
        }
    ],
    "aggregate": {"passed": True, "score": 1.0},
    "claim_tier": "recapitulated-known",
    "claim_tier_is_candidate": False,
    "perturbation_pairs": [],
    "insensitivity_flags": [],
    "challenger_panel": {"challenger_ids": ["challenger-a", "challenger-b"], "min_required": 2},
    "independence_attestation_debate": {
        "min_independent_challengers": 2,
        "lineage_disjoint": True,
        "correlation_warning": False,
    },
    "referee": {
        "referee_id": "s3-referee",
        "non_gameable": True,
        "signed_by": C3_ARGUSVERIFY_KEY_ID,
        "distinct_from_proponent": True,
    },
    "debate_ref": "c4://debate/ewpt-toy/example",
}


def load_manifest() -> dict:
    with MANIFEST_PATH.open(encoding="utf-8") as handle:
        return json.load(handle)


def contracts() -> list[dict]:
    items = []
    for raw in load_manifest()["contracts"]:
        item = dict(raw)
        item["schema_sha256"] = schema_sha256(CONTRACTS_DIR / item["schema"])
        items.append(item)
    return sorted(items, key=lambda item: item["id"])


def schema_sha256(path: Path) -> str:
    with path.open(encoding="utf-8") as handle:
        value = json.load(handle)
    canonical = json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return "sha256:" + hashlib.sha256(canonical).hexdigest()


def canonical_json_text(value: object) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False, separators=(",", ":"))
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return canonical_number(value)
    if isinstance(value, list):
        return "[" + ",".join(canonical_json_text(item) for item in value) + "]"
    if isinstance(value, dict):
        return (
            "{"
            + ",".join(
                f"{json.dumps(key, ensure_ascii=False, separators=(',', ':'))}:{canonical_json_text(value[key])}"
                for key in sorted(value)
            )
            + "}"
        )
    raise TypeError("canonical JSON only accepts JSON-compatible values")


def canonical_number(value: float) -> str:
    if not math.isfinite(value):
        raise ValueError("canonical JSON rejects non-finite numbers")
    if value == 0:
        return "0"
    text = json.dumps(value, allow_nan=False, separators=(",", ":")).replace("E", "e")
    if "e" in text:
        mantissa, exponent = text.split("e", 1)
        normalized_exponent = normalize_exponent(exponent)
        fixed = exponent_to_fixed_if_javascript_decimal(mantissa, normalized_exponent)
        if fixed is not None:
            return fixed
        return f"{trim_decimal_text(mantissa)}e{normalized_exponent}"
    return trim_decimal_text(text)


def trim_decimal_text(text: str) -> str:
    if "." in text:
        text = text.rstrip("0").rstrip(".")
    return "0" if text == "-0" else text


def normalize_exponent(exponent: str) -> str:
    sign = ""
    digits = exponent
    if digits.startswith(("+", "-")):
        sign = "-" if digits[0] == "-" else ""
        digits = digits[1:]
    digits = digits.lstrip("0") or "0"
    return f"{sign}{digits}"


def exponent_to_fixed_if_javascript_decimal(mantissa: str, exponent: str) -> str | None:
    exponent_value = int(exponent)
    sign = ""
    body = mantissa
    if body.startswith("-"):
        sign = "-"
        body = body[1:]
    integer, dot, fraction = body.partition(".")
    digits = integer + (fraction if dot else "")
    if not digits or set(digits) == {"0"}:
        return "0"
    decimal_exponent = exponent_value + len(digits) - len(fraction) - 1
    if decimal_exponent < -6 or decimal_exponent >= 21:
        return None
    scale = exponent_value - len(fraction)
    if scale >= 0:
        return sign + digits + ("0" * scale)
    decimal_position = len(digits) + scale
    if decimal_position > 0:
        fixed = sign + digits[:decimal_position] + "." + digits[decimal_position:]
    else:
        fixed = sign + "0." + ("0" * abs(decimal_position)) + digits
    return trim_decimal_text(fixed)


def c3_argusverify_vector_signature() -> str:
    signed = json.loads(canonical_json_text(C3_ARGUSVERIFY_VECTOR_REPORT))
    signed["signature"] = {
        "algorithm": "hmac-sha256",
        "key_id": C3_ARGUSVERIFY_KEY_ID,
        "value": "",
    }
    digest = hmac.new(
        C3_ARGUSVERIFY_SECRET.encode("utf-8"),
        canonical_json_text(signed).encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()
    return f"hmac-sha256:{digest}"


def py_repr(value: object) -> str:
    return repr(value).replace("'", '"')


def render_python_contracts(items: list[dict]) -> str:
    rows = []
    for item in items:
        rows.append(
            "    Contract("
            f'id="{item["id"]}", '
            f'name="{item["name"]}", '
            f'owner="{item["owner"]}", '
            f'version="{item["version"]}", '
            f'schema="{item["schema"]}", '
            f'schema_sha256="{item["schema_sha256"]}", '
            f"consumers={py_repr(item['consumers'])}"
            ")"
        )
    return "\n".join(
        [
            f'"""{HEADER}"""',
            "",
            "from __future__ import annotations",
            "",
            "from dataclasses import dataclass",
            "",
            "",
            "@dataclass(frozen=True)",
            "class Contract:",
            "    id: str",
            "    name: str",
            "    owner: str",
            "    version: str",
            "    schema: str",
            "    schema_sha256: str",
            "    consumers: list[str]",
            "",
            "",
            "CONTRACTS: tuple[Contract, ...] = (",
            ",\n".join(rows),
            ")",
            "",
            "CONTRACT_BY_ID: dict[str, Contract] = {contract.id: contract for contract in CONTRACTS}",
            "",
        ]
    )


def render_python_init() -> str:
    return "\n".join(
        [
            f'"""{HEADER}"""',
            "",
            "from .c4 import (",
            "    ArtifactRecord,",
            "    ArtifactRef,",
            "    C4_SCHEMA_SHA256,",
            "    ClaimTier,",
            "    HashRef,",
            "    Lineage,",
            "    Producer,",
            "    RetentionPolicy,",
            "    validate_artifact_record,",
            ")",
            "from .contracts import CONTRACT_BY_ID, CONTRACTS, Contract",
            "",
            "__all__ = [",
            '    "ArtifactRecord",',
            '    "ArtifactRef",',
            '    "C4_SCHEMA_SHA256",',
            '    "ClaimTier",',
            '    "CONTRACTS",',
            '    "CONTRACT_BY_ID",',
            '    "Contract",',
            '    "HashRef",',
            '    "Lineage",',
            '    "Producer",',
            '    "RetentionPolicy",',
            '    "validate_artifact_record",',
            "]",
            "",
        ]
    )


def render_typescript_package() -> str:
    package = {
        "name": "@project-argus/contracts",
        "version": "0.0.0",
        "private": True,
        "type": "module",
        "scripts": {
            "build": "tsc --project tsconfig.json",
            "test": "npm run build && node dist/test/c4-smoke.js && node dist/test/argusverify-smoke.js",
        },
        "exports": {
            ".": "./src/contracts.ts",
            "./argusverify": "./src/argusverify.ts",
            "./c4": "./src/c4.ts",
        },
        "dependencies": {
            "@noble/hashes": "1.8.0",
        },
        "devDependencies": {
            "@types/node": "20.10.8",
            "typescript": "6.0.3",
        },
    }
    return json.dumps(package, indent=2, sort_keys=False) + "\n"


def render_typescript_tsconfig() -> str:
    config = {
        "compilerOptions": {
            "target": "ES2022",
            "module": "NodeNext",
            "moduleResolution": "NodeNext",
            "strict": True,
            "noEmitOnError": True,
            "esModuleInterop": True,
            "skipLibCheck": True,
            "types": ["node"],
            "outDir": "dist",
            "rootDir": ".",
        },
        "include": ["src/**/*.ts", "test/**/*.ts"],
    }
    return json.dumps(config, indent=2, sort_keys=False) + "\n"


def render_typescript_contracts(items: list[dict]) -> str:
    ids = " | ".join(json.dumps(item["id"]) for item in items)
    payload = json.dumps(items, indent=2)
    lookup = "\n".join(f"  {json.dumps(item['id'])}: contracts[{index}]," for index, item in enumerate(items))
    return "\n".join(
        [
            f"// {HEADER}",
            "",
            f"export type ContractId = {ids};",
            "",
            "export interface Contract {",
            "  id: ContractId;",
            "  name: string;",
            "  owner: string;",
            "  version: string;",
            "  schema: string;",
            "  schema_sha256: string;",
            "  consumers: readonly string[];",
            "}",
            "",
            f"export const contracts = {payload} as const satisfies readonly Contract[];",
            "",
            "export const contractById = {",
            lookup,
            "} satisfies Record<ContractId, Contract>;",
            "",
        ]
    )


def render_python_c4(c4_schema_sha256: str) -> str:
    return f'''"""{HEADER}"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Any, Literal, Mapping

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


C4_SCHEMA_SHA256 = "{c4_schema_sha256}"

ArtifactRef = Annotated[str, Field(pattern=r"^c4://[A-Za-z0-9._:/-]+$")]
HashRef = Annotated[str, Field(pattern=r"^blake3:[a-f0-9]{{64}}$")]
ClaimTier = Literal["ran-toy", "recapitulated-known", "novel-needs-human"]


class Producer(BaseModel):
    model_config = ConfigDict(extra="forbid")

    subsystem: str = Field(pattern=r"^S\\d+$")
    version: str = Field(pattern=r"^\\d+\\.\\d+\\.\\d+$")


class Lineage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    input_refs: list[ArtifactRef]
    code_ref: str = Field(min_length=1)
    environment_digest: str = Field(min_length=1)
    seeds: list[str]

    @field_validator("input_refs")
    @classmethod
    def _input_refs_are_unique(cls, value: list[str]) -> list[str]:
        if len(value) != len(set(value)):
            raise ValueError("input_refs must be unique")
        return value

    @field_validator("seeds")
    @classmethod
    def _seeds_are_unique(cls, value: list[str]) -> list[str]:
        if len(value) != len(set(value)):
            raise ValueError("seeds must be unique")
        return value


class RetentionPolicy(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    class_: Literal["write_once", "scratch", "hold"] | None = Field(default=None, alias="class")
    retain_until: datetime | None = None
    hold_id: str | None = Field(default=None, min_length=1)


class ArtifactRecord(BaseModel):
    model_config = ConfigDict(extra="forbid")

    artifact_ref: ArtifactRef
    kind: str = Field(min_length=1)
    content_hash: HashRef
    hash_algorithm: Literal["BLAKE3"]
    size_bytes: int = Field(ge=0)
    created_at: datetime
    producer: Producer
    lineage: Lineage
    claim_tier: ClaimTier | None = None
    validation_report_ref: ArtifactRef | None = None
    schema_ref: str | None = None
    retention: RetentionPolicy | None = None

    @model_validator(mode="after")
    def _promoted_tier_requires_validation_report(self) -> ArtifactRecord:
        if self.claim_tier in {{"recapitulated-known", "novel-needs-human"}} and self.validation_report_ref is None:
            raise ValueError("promoted claim_tier requires validation_report_ref")
        return self


def validate_artifact_record(payload: Mapping[str, Any]) -> ArtifactRecord:
    return ArtifactRecord.model_validate(payload)
'''


def render_typescript_c4(c4_schema_sha256: str) -> str:
    return f'''// {HEADER}

import {{ blake3 }} from "@noble/hashes/blake3.js";
import {{ bytesToHex }} from "@noble/hashes/utils.js";

export const C4_SCHEMA_SHA256 = "{c4_schema_sha256}";
export const BLAKE3_PREFIX = "blake3:";
export const CANON_VERSION = "argus-jcs-v1";

export type ArtifactRef = `c4://${{string}}`;
export type HashRef = `blake3:${{string}}`;
export type ClaimTier = "ran-toy" | "recapitulated-known" | "novel-needs-human";

export interface Producer {{
  subsystem: string;
  version: string;
}}

export interface Lineage {{
  input_refs: readonly ArtifactRef[];
  code_ref: string;
  environment_digest: string;
  seeds: readonly string[];
}}

export interface RetentionPolicy {{
  class?: "write_once" | "scratch" | "hold";
  retain_until?: string;
  hold_id?: string;
}}

export interface ArtifactRecord {{
  artifact_ref: ArtifactRef;
  kind: string;
  content_hash: HashRef;
  hash_algorithm: "BLAKE3";
  size_bytes: number;
  created_at: string;
  producer: Producer;
  lineage: Lineage;
  claim_tier?: ClaimTier;
  validation_report_ref?: ArtifactRef;
  schema_ref?: string;
  retention?: RetentionPolicy;
}}

export interface HashBlob {{
  content_hash: HashRef;
  size_bytes: number;
  canon_version: typeof CANON_VERSION;
}}

const artifactRefPattern = /^c4:\\/\\/[A-Za-z0-9._:/-]+$/;
const hashRefPattern = /^blake3:[a-f0-9]{{64}}$/;
const subsystemPattern = /^S\\d+$/;
const versionPattern = /^\\d+\\.\\d+\\.\\d+$/;

export function hashBlob(payload: Uint8Array): HashBlob {{
  return {{
    content_hash: `${{BLAKE3_PREFIX}}${{bytesToHex(blake3(payload))}}` as HashRef,
    size_bytes: payload.byteLength,
    canon_version: CANON_VERSION,
  }};
}}

export function assertArtifactRecord(payload: unknown): asserts payload is ArtifactRecord {{
  const record = assertRecord(payload, "artifact");
  assertKeys(record, [
    "artifact_ref",
    "kind",
    "content_hash",
    "hash_algorithm",
    "size_bytes",
    "created_at",
    "producer",
    "lineage",
    "claim_tier",
    "validation_report_ref",
    "schema_ref",
    "retention",
  ], "artifact");
  assertPattern(record.artifact_ref, artifactRefPattern, "artifact.artifact_ref");
  assertMinString(record.kind, 1, "artifact.kind");
  assertPattern(record.content_hash, hashRefPattern, "artifact.content_hash");
  assertLiteral(record.hash_algorithm, "BLAKE3", "artifact.hash_algorithm");
  assertNonNegativeInteger(record.size_bytes, "artifact.size_bytes");
  assertDateTime(record.created_at, "artifact.created_at");
  assertProducer(record.producer, "artifact.producer");
  assertLineage(record.lineage, "artifact.lineage");

  if (record.claim_tier !== undefined) {{
    assertOneOf(record.claim_tier, ["ran-toy", "recapitulated-known", "novel-needs-human"], "artifact.claim_tier");
  }}
  if (record.validation_report_ref !== undefined) {{
    assertPattern(record.validation_report_ref, artifactRefPattern, "artifact.validation_report_ref");
  }}
  if (record.schema_ref !== undefined) {{
    assertMinString(record.schema_ref, 0, "artifact.schema_ref");
  }}
  if (record.retention !== undefined) {{
    assertRetention(record.retention, "artifact.retention");
  }}
  if (
    (record.claim_tier === "recapitulated-known" || record.claim_tier === "novel-needs-human") &&
    record.validation_report_ref === undefined
  ) {{
    throw new TypeError("artifact.validation_report_ref is required for promoted claim_tier");
  }}
}}

function assertProducer(value: unknown, path: string): asserts value is Producer {{
  const record = assertRecord(value, path);
  assertKeys(record, ["subsystem", "version"], path);
  assertPattern(record.subsystem, subsystemPattern, `${{path}}.subsystem`);
  assertPattern(record.version, versionPattern, `${{path}}.version`);
}}

function assertLineage(value: unknown, path: string): asserts value is Lineage {{
  const record = assertRecord(value, path);
  assertKeys(record, ["input_refs", "code_ref", "environment_digest", "seeds"], path);
  assertStringArray(record.input_refs, `${{path}}.input_refs`, artifactRefPattern);
  assertMinString(record.code_ref, 1, `${{path}}.code_ref`);
  assertMinString(record.environment_digest, 1, `${{path}}.environment_digest`);
  assertStringArray(record.seeds, `${{path}}.seeds`);
}}

function assertRetention(value: unknown, path: string): asserts value is RetentionPolicy {{
  const record = assertRecord(value, path);
  assertKeys(record, ["class", "retain_until", "hold_id"], path);
  if (record.class !== undefined) {{
    assertOneOf(record.class, ["write_once", "scratch", "hold"], `${{path}}.class`);
  }}
  if (record.retain_until !== undefined) {{
    assertDateTime(record.retain_until, `${{path}}.retain_until`);
  }}
  if (record.hold_id !== undefined) {{
    assertMinString(record.hold_id, 1, `${{path}}.hold_id`);
  }}
}}

function assertRecord(value: unknown, path: string): Record<string, unknown> {{
  if (typeof value !== "object" || value === null || Array.isArray(value)) {{
    throw new TypeError(`${{path}} must be an object`);
  }}
  return value as Record<string, unknown>;
}}

function assertKeys(record: Record<string, unknown>, allowedKeys: readonly string[], path: string): void {{
  const allowed = new Set(allowedKeys);
  for (const key of Object.keys(record)) {{
    if (!allowed.has(key)) {{
      throw new TypeError(`${{path}}.${{key}} is not allowed`);
    }}
  }}
  for (const key of allowedKeys) {{
    if (!(key in record) && requiredKeys(path).has(key)) {{
      throw new TypeError(`${{path}}.${{key}} is required`);
    }}
  }}
}}

function requiredKeys(path: string): Set<string> {{
  if (path === "artifact") {{
    return new Set(["artifact_ref", "kind", "content_hash", "hash_algorithm", "size_bytes", "created_at", "producer", "lineage"]);
  }}
  if (path.endsWith(".producer")) {{
    return new Set(["subsystem", "version"]);
  }}
  if (path.endsWith(".lineage")) {{
    return new Set(["input_refs", "code_ref", "environment_digest", "seeds"]);
  }}
  return new Set();
}}

function assertPattern(value: unknown, pattern: RegExp, path: string): asserts value is string {{
  assertMinString(value, 0, path);
  if (!pattern.test(value)) {{
    throw new TypeError(`${{path}} does not match required pattern`);
  }}
}}

function assertMinString(value: unknown, minLength: number, path: string): asserts value is string {{
  if (typeof value !== "string" || value.length < minLength) {{
    throw new TypeError(`${{path}} must be a string with length >= ${{minLength}}`);
  }}
}}

function assertLiteral<T extends string>(value: unknown, expected: T, path: string): asserts value is T {{
  if (value !== expected) {{
    throw new TypeError(`${{path}} must equal ${{expected}}`);
  }}
}}

function assertOneOf<T extends string>(value: unknown, allowed: readonly T[], path: string): asserts value is T {{
  if (typeof value !== "string" || !allowed.includes(value as T)) {{
    throw new TypeError(`${{path}} must be one of ${{allowed.join(", ")}}`);
  }}
}}

function assertNonNegativeInteger(value: unknown, path: string): asserts value is number {{
  if (!Number.isSafeInteger(value) || (value as number) < 0) {{
    throw new TypeError(`${{path}} must be a non-negative integer`);
  }}
}}

function assertDateTime(value: unknown, path: string): asserts value is string {{
  assertMinString(value, 1, path);
  if (Number.isNaN(Date.parse(value))) {{
    throw new TypeError(`${{path}} must be an RFC3339 date-time string`);
  }}
}}

function assertStringArray(value: unknown, path: string, pattern?: RegExp): asserts value is readonly string[] {{
  if (!Array.isArray(value)) {{
    throw new TypeError(`${{path}} must be an array`);
  }}
  const seen = new Set<string>();
  for (const [index, item] of value.entries()) {{
    if (typeof item !== "string") {{
      throw new TypeError(`${{path}}[${{index}}] must be a string`);
    }}
    if (pattern !== undefined && !pattern.test(item)) {{
      throw new TypeError(`${{path}}[${{index}}] does not match required pattern`);
    }}
    if (seen.has(item)) {{
      throw new TypeError(`${{path}} must contain unique values`);
    }}
    seen.add(item);
  }}
}}
'''


def render_typescript_c4_smoke(c4_schema_sha256: str) -> str:
    return f'''// {HEADER}

import assert from "node:assert/strict";

import {{
  ArtifactRecord,
  C4_SCHEMA_SHA256,
  CANON_VERSION,
  assertArtifactRecord,
  hashBlob,
}} from "../src/c4.js";

const emptyHash = "blake3:af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262";
const vectorHash = "blake3:7e2fc64a9cc052211dfe7f54f2432c35588950f43d92bb08c87bbd182823d8d1";

const example: ArtifactRecord = {{
  artifact_ref: "c4://artifact/example",
  kind: "dataset",
  content_hash: emptyHash,
  hash_algorithm: "BLAKE3",
  size_bytes: 0,
  created_at: "2026-01-01T00:00:00Z",
  producer: {{
    subsystem: "S8",
    version: "1.0.0",
  }},
  lineage: {{
    input_refs: [],
    code_ref: "git:project-argus@example",
    environment_digest: "oci:sha256-example",
    seeds: [],
  }},
}};

assert.equal(C4_SCHEMA_SHA256, "{c4_schema_sha256}");
assert.equal(hashBlob(new Uint8Array()).content_hash, emptyHash);
assert.equal(hashBlob(new TextEncoder().encode("argus-s8-binding-vector")).content_hash, vectorHash);
assert.equal(hashBlob(new TextEncoder().encode("argus-s8-binding-vector")).size_bytes, 23);
assert.equal(hashBlob(new Uint8Array()).canon_version, CANON_VERSION);
assert.doesNotThrow(() => assertArtifactRecord(example));

assert.throws(
  () => assertArtifactRecord({{
    ...example,
    lineage: {{
      input_refs: [],
      code_ref: "git:project-argus@example",
      seeds: [],
    }},
  }}),
  /environment_digest/,
);

assert.throws(
  () => assertArtifactRecord({{
    ...example,
    claim_tier: "novel-needs-human",
  }}),
  /validation_report_ref/,
);
'''


def render_typescript_argusverify() -> str:
    return f'''// {HEADER}

import {{ createHmac, type BinaryLike }} from "node:crypto";

export const C3_SIGNATURE_ALGORITHM = "hmac-sha256";
export const C3_SIGNATURE_PREFIX = "hmac-sha256:";
export const SIGNATURE_VERIFICATION_ACCEPTED = "signature_accepted";
export const SIGNATURE_VERIFICATION_ABSTAIN = "signature_abstain";
export type SignatureVerificationDelegationResult =
  | typeof SIGNATURE_VERIFICATION_ACCEPTED
  | typeof SIGNATURE_VERIFICATION_ABSTAIN
  | string
  | undefined;

export interface VerifierKey {{
  key_id: string;
  secret: Uint8Array | string;
  revoked?: boolean;
}}

export interface C3SignatureVerification {{
  valid: boolean;
  reason?: string;
  error_code?: string;
  key_id?: string;
  claim_tier?: string;
  aggregate_passed?: boolean;
}}

export interface VerifierTrustStore {{
  getKey(keyId: string): VerifierKey | undefined;
  verifySignatureValue?(args: {{
    key_id: string;
    report_with_empty_signature: Record<string, unknown>;
    signature_value: string;
  }}): SignatureVerificationDelegationResult;
}}

export class InMemoryVerifierTrustStore implements VerifierTrustStore {{
  private readonly keys = new Map<string, VerifierKey>();

  registerKey(keyId: string, secret: Uint8Array | string): void {{
    this.keys.set(keyId, {{ key_id: keyId, secret }});
  }}

  revokeKey(keyId: string): void {{
    const key = this.keys.get(keyId);
    if (key === undefined) {{
      throw new Error(`unknown verifier key: ${{keyId}}`);
    }}
    this.keys.set(keyId, {{ ...key, revoked: true }});
  }}

  getKey(keyId: string): VerifierKey | undefined {{
    return this.keys.get(keyId);
  }}

  verifySignatureValue(): SignatureVerificationDelegationResult {{
    return SIGNATURE_VERIFICATION_ABSTAIN;
  }}
}}

const errorCodes: Record<string, string> = {{
  signature_missing: "UNSIGNED",
  algorithm_unsupported: "ALGORITHM_UNSUPPORTED",
  key_missing: "KEY_MISSING",
  unknown_key: "UNKNOWN_KEY",
  revoked_key: "REVOKED_KEY",
  signature_value_missing: "SIGNATURE_VALUE_MISSING",
  signature_invalid: "SIGNATURE_INVALID",
}};

export function signReport(
  report: Record<string, unknown>,
  options: {{ keyId: string; secret: Uint8Array | string }},
): Record<string, unknown> {{
  const signed = cloneJsonObject(report);
  signed.signature = {{
    algorithm: C3_SIGNATURE_ALGORITHM,
    key_id: options.keyId,
    value: "",
  }};
  (signed.signature as Record<string, unknown>).value = signatureValue(signed, options.secret);
  return signed;
}}

export function verifyReport(
  report: Record<string, unknown>,
  trustStore: VerifierTrustStore,
): C3SignatureVerification {{
  const signature = report.signature;
  if (!isRecord(signature)) {{
    return invalid("signature_missing");
  }}
  const algorithm = signature.algorithm;
  const keyId = signature.key_id;
  const value = signature.value;
  if (algorithm !== C3_SIGNATURE_ALGORITHM) {{
    return invalid("algorithm_unsupported", typeof keyId === "string" ? keyId : undefined);
  }}
  if (typeof keyId !== "string") {{
    return invalid("key_missing");
  }}
  const key = trustStore.getKey(keyId);
  if (key === undefined) {{
    return invalid("unknown_key", keyId);
  }}
  if (key.revoked === true) {{
    return invalid("revoked_key", keyId);
  }}
  if (typeof value !== "string") {{
    return invalid("signature_value_missing", keyId);
  }}

  const unsigned = cloneJsonObject(report);
  unsigned.signature = {{
    algorithm,
    key_id: keyId,
    value: "",
  }};
  const delegation = trustStore.verifySignatureValue?.({{
    key_id: keyId,
    report_with_empty_signature: unsigned,
    signature_value: value,
  }});
  if (delegation === SIGNATURE_VERIFICATION_ACCEPTED) {{
    return validVerification(report, keyId);
  }}
  if (delegation !== undefined && delegation !== SIGNATURE_VERIFICATION_ABSTAIN) {{
    return invalid(delegation, keyId);
  }}
  if (!constantTimeStringEqual(value, signatureValue(unsigned, key.secret))) {{
    return invalid("signature_invalid", keyId);
  }}

  return validVerification(report, keyId);
}}

function validVerification(report: Record<string, unknown>, keyId: string): C3SignatureVerification {{
  return {{
    valid: true,
    key_id: keyId,
    claim_tier: typeof report.claim_tier === "string" ? report.claim_tier : undefined,
    aggregate_passed: aggregatePassed(report),
  }};
}}

function invalid(reason: string, keyId?: string): C3SignatureVerification {{
  return {{
    valid: false,
    reason,
    error_code: errorCodes[reason] ?? reason.toUpperCase(),
    key_id: keyId,
  }};
}}

function signatureValue(reportWithEmptySignature: Record<string, unknown>, secret: Uint8Array | string): string {{
  const digest = createHmac("sha256", secretBytes(secret) as unknown as BinaryLike)
    .update(canonicalJson(reportWithEmptySignature), "utf8")
    .digest("hex");
  return `${{C3_SIGNATURE_PREFIX}}${{digest}}`;
}}

function aggregatePassed(report: Record<string, unknown>): boolean | undefined {{
  const aggregate = report.aggregate;
  if (!isRecord(aggregate)) {{
    return undefined;
  }}
  return typeof aggregate.passed === "boolean" ? aggregate.passed : undefined;
}}

function canonicalJson(value: unknown): string {{
  if (value === null) {{
    return "null";
  }}
  if (typeof value === "string") {{
    return JSON.stringify(value);
  }}
  if (typeof value === "number") {{
    return canonicalNumber(value);
  }}
  if (typeof value === "boolean") {{
    return value ? "true" : "false";
  }}
  if (Array.isArray(value)) {{
    return `[${{value.map((item) => canonicalJson(item)).join(",")}}]`;
  }}
  if (isRecord(value)) {{
    return `{{${{Object.keys(value)
      .sort()
      .map((key) => `${{JSON.stringify(key)}}:${{canonicalJson(value[key])}}`)
      .join(",")}}}}`;
  }}
  throw new TypeError("canonical JSON only accepts JSON-compatible values");
}}

function canonicalNumber(value: number): string {{
  if (!Number.isFinite(value)) {{
    throw new TypeError("canonical JSON rejects non-finite numbers");
  }}
  if (value === 0) {{
    return "0";
  }}
  const text = JSON.stringify(value).replace("E", "e");
  if (text.includes("e")) {{
    const [mantissa, exponent] = text.split("e", 2);
    return `${{trimDecimalText(mantissa)}}e${{normalizeExponent(exponent)}}`;
  }}
  return trimDecimalText(text);
}}

function trimDecimalText(text: string): string {{
  if (text.includes(".")) {{
    text = text.replace(/0+$/, "").replace(/\\.$/, "");
  }}
  return text === "-0" ? "0" : text;
}}

function normalizeExponent(exponent: string): string {{
  let sign = "";
  let digits = exponent;
  if (digits.startsWith("+") || digits.startsWith("-")) {{
    sign = digits.startsWith("-") ? "-" : "";
    digits = digits.slice(1);
  }}
  digits = digits.replace(/^0+/, "") || "0";
  return `${{sign}}${{digits}}`;
}}

function isRecord(value: unknown): value is Record<string, unknown> {{
  return typeof value === "object" && value !== null && !Array.isArray(value);
}}

function cloneJsonObject(value: Record<string, unknown>): Record<string, unknown> {{
  return JSON.parse(JSON.stringify(value)) as Record<string, unknown>;
}}

function secretBytes(secret: Uint8Array | string): Uint8Array {{
  return typeof secret === "string" ? new TextEncoder().encode(secret) : secret;
}}

function constantTimeStringEqual(left: string, right: string): boolean {{
  const leftBytes = new TextEncoder().encode(left);
  const rightBytes = new TextEncoder().encode(right);
  if (leftBytes.length !== rightBytes.length) {{
    return false;
  }}
  let diff = 0;
  for (let index = 0; index < leftBytes.length; index += 1) {{
    diff |= leftBytes[index] ^ rightBytes[index];
  }}
  return diff === 0;
}}
'''


def render_typescript_argusverify_smoke() -> str:
    report = json.dumps(C3_ARGUSVERIFY_VECTOR_REPORT, indent=2)
    expected_signature = c3_argusverify_vector_signature()
    return f'''// {HEADER}

import assert from "node:assert/strict";

import {{
  InMemoryVerifierTrustStore,
  SIGNATURE_VERIFICATION_ABSTAIN,
  SIGNATURE_VERIFICATION_ACCEPTED,
  type SignatureVerificationDelegationResult,
  type VerifierKey,
  signReport,
  verifyReport,
}} from "../src/argusverify.js";

const report = {report} as Record<string, unknown>;
const expectedSignature = "{expected_signature}";

const trustStore = new InMemoryVerifierTrustStore();
trustStore.registerKey("{C3_ARGUSVERIFY_KEY_ID}", "{C3_ARGUSVERIFY_SECRET}");

const signed = signReport(report, {{ keyId: "{C3_ARGUSVERIFY_KEY_ID}", secret: "{C3_ARGUSVERIFY_SECRET}" }});
assert.equal((signed.signature as Record<string, unknown>).value, expectedSignature);

const valid = verifyReport(signed, trustStore);
assert.equal(valid.valid, true);
assert.equal(valid.claim_tier, "recapitulated-known");
assert.equal(valid.aggregate_passed, true);

trustStore.registerKey("s3-key-v2", "s3-secret-v2");
const archivedAfterRotation = verifyReport(signed, trustStore);
assert.equal(archivedAfterRotation.valid, true);
const signedV2 = signReport(report, {{ keyId: "s3-key-v2", secret: "s3-secret-v2" }});
assert.equal(verifyReport(signedV2, trustStore).key_id, "s3-key-v2");

const tampered = JSON.parse(JSON.stringify(signed)) as Record<string, unknown>;
(tampered.aggregate as Record<string, unknown>).score = 0.99;
const tamperedVerification = verifyReport(tampered, trustStore);
assert.equal(tamperedVerification.valid, false);
assert.equal(tamperedVerification.error_code, "SIGNATURE_INVALID");

class SecretlessDelegatingTrustStore {{
  getKey(keyId: string): VerifierKey | undefined {{
    if (keyId !== "{C3_ARGUSVERIFY_KEY_ID}") {{
      return undefined;
    }}
    return {{ key_id: keyId, secret: "" }};
  }}

  verifySignatureValue(args: {{
    key_id: string;
    report_with_empty_signature: Record<string, unknown>;
    signature_value: string;
  }}): SignatureVerificationDelegationResult {{
    assert.equal(args.key_id, "{C3_ARGUSVERIFY_KEY_ID}");
    assert.equal((args.report_with_empty_signature.signature as Record<string, unknown>).value, "");
    if (args.signature_value === (signed.signature as Record<string, unknown>).value) {{
      return SIGNATURE_VERIFICATION_ACCEPTED;
    }}
    return "signature_invalid";
  }}
}}

const delegatedValid = verifyReport(signed, new SecretlessDelegatingTrustStore());
assert.equal(delegatedValid.valid, true);
const forgedSignature = JSON.parse(JSON.stringify(signed)) as Record<string, unknown>;
(forgedSignature.signature as Record<string, unknown>).value = "hmac-sha256:bad";
const delegatedInvalid = verifyReport(forgedSignature, new SecretlessDelegatingTrustStore());
assert.equal(delegatedInvalid.valid, false);
assert.equal(delegatedInvalid.error_code, "SIGNATURE_INVALID");

class AbstainingTrustStore {{
  constructor(private readonly delegation: SignatureVerificationDelegationResult) {{}}

  getKey(keyId: string): VerifierKey | undefined {{
    if (keyId !== "{C3_ARGUSVERIFY_KEY_ID}") {{
      return undefined;
    }}
    return {{ key_id: keyId, secret: "" }};
  }}

  verifySignatureValue(args: {{
    key_id: string;
    report_with_empty_signature: Record<string, unknown>;
    signature_value: string;
  }}): SignatureVerificationDelegationResult {{
    assert.equal(args.key_id, "{C3_ARGUSVERIFY_KEY_ID}");
    assert.equal((args.report_with_empty_signature.signature as Record<string, unknown>).value, "");
    assert.equal(args.signature_value, (signed.signature as Record<string, unknown>).value);
    return this.delegation;
  }}
}}

for (const delegation of [undefined, SIGNATURE_VERIFICATION_ABSTAIN]) {{
  const abstained = verifyReport(signed, new AbstainingTrustStore(delegation));
  assert.equal(abstained.valid, false);
  assert.equal(abstained.error_code, "SIGNATURE_INVALID");
}}

const unsigned = JSON.parse(JSON.stringify(signed)) as Record<string, unknown>;
delete unsigned.signature;
const unsignedVerification = verifyReport(unsigned, trustStore);
assert.equal(unsignedVerification.valid, false);
assert.equal(unsignedVerification.error_code, "UNSIGNED");

trustStore.revokeKey("{C3_ARGUSVERIFY_KEY_ID}");
const revokedVerification = verifyReport(signed, trustStore);
assert.equal(revokedVerification.valid, false);
assert.equal(revokedVerification.error_code, "REVOKED_KEY");
'''


def rust_array(values: list[str]) -> str:
    return "&[" + ", ".join(json.dumps(value) for value in values) + "]"


def render_rust_manifest() -> str:
    return "\n".join(
        [
            "[package]",
            'name = "argus-contracts"',
            'version = "0.0.0"',
            'edition = "2021"',
            'publish = false',
            "",
            "[lib]",
            'path = "src/lib.rs"',
            "",
            "[dependencies]",
            'blake3 = "1"',
            'chrono = { version = "0.4", features = ["serde"] }',
            'hmac = "0.13"',
            'postgres = { version = "0.19", features = ["with-chrono-0_4", "with-serde_json-1"] }',
            'serde = { version = "1", features = ["derive"] }',
            'serde_json = "1"',
            'sha2 = "0.11"',
            "",
            "[[bin]]",
            'name = "argus-s8-ledger-writer"',
            'path = "src/bin/s8_ledger_writer.rs"',
            "",
        ]
    )


def render_rust_lib(items: list[dict]) -> str:
    rows = []
    for item in items:
        rows.append(
            "    Contract { "
            f'id: "{item["id"]}", '
            f'name: "{item["name"]}", '
            f'owner: "{item["owner"]}", '
            f'version: "{item["version"]}", '
            f'schema: "{item["schema"]}", '
            f'schema_sha256: "{item["schema_sha256"]}", '
            f"consumers: {rust_array(item['consumers'])} "
            "},"
        )
    return "\n".join(
        [
            f"// {HEADER}",
            "",
            "pub mod argusverify;",
            "pub mod c4;",
            "pub mod hash;",
            "pub mod ledger;",
            "",
            "pub use argusverify::{sign_report, verify_report, C3SignatureVerification, InMemoryVerifierTrustStore, VerifierKey, VerifierTrustStore, C3_SIGNATURE_ALGORITHM, C3_SIGNATURE_PREFIX, SIGNATURE_VERIFICATION_ABSTAIN, SIGNATURE_VERIFICATION_ACCEPTED};",
            "pub use c4::{ArtifactRecord, ClaimTier, Lineage, Producer, RetentionPolicy, C4_SCHEMA_SHA256};",
            "pub use hash::{hash_blob, hash_blob_stream, hash_bytes, BlobHasher, HashBlob, HashBlobError, BLAKE3_PREFIX, CANON_VERSION};",
            "pub use ledger::{ArtifactRecordDraft, CheckpointSigner, MerkleCheckpoint, PostgresLedgerWriter};",
            "",
            "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
            "pub struct Contract {",
            "    pub id: &'static str,",
            "    pub name: &'static str,",
            "    pub owner: &'static str,",
            "    pub version: &'static str,",
            "    pub schema: &'static str,",
            "    pub schema_sha256: &'static str,",
            "    pub consumers: &'static [&'static str],",
            "}",
            "",
            "pub const CONTRACTS: &[Contract] = &[",
            "\n".join(rows),
            "];",
            "",
            "pub fn contract_by_id(id: &str) -> Option<&'static Contract> {",
            "    CONTRACTS.iter().find(|contract| contract.id == id)",
            "}",
            "",
        ]
    )


def render_rust_c4(c4_schema_sha256: str) -> str:
    return f'''// {HEADER}

use serde::{{Deserialize, Serialize}};

pub const C4_SCHEMA_SHA256: &str = "{c4_schema_sha256}";

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ClaimTier {{
    RanToy,
    RecapitulatedKnown,
    NovelNeedsHuman,
}}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Producer {{
    pub subsystem: String,
    pub version: String,
}}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Lineage {{
    pub input_refs: Vec<String>,
    pub code_ref: String,
    pub environment_digest: String,
    pub seeds: Vec<String>,
}}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RetentionPolicy {{
    #[serde(rename = "class", skip_serializing_if = "Option::is_none")]
    pub class_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub retain_until: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hold_id: Option<String>,
}}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ArtifactRecord {{
    pub artifact_ref: String,
    pub kind: String,
    pub content_hash: String,
    pub hash_algorithm: String,
    pub size_bytes: u64,
    pub created_at: String,
    pub producer: Producer,
    pub lineage: Lineage,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub claim_tier: Option<ClaimTier>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub validation_report_ref: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub schema_ref: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub retention: Option<RetentionPolicy>,
}}

impl ArtifactRecord {{
    pub fn validate_promoted_tier(&self) -> Result<(), &'static str> {{
        if matches!(
            self.claim_tier,
            Some(ClaimTier::RecapitulatedKnown | ClaimTier::NovelNeedsHuman)
        ) && self.validation_report_ref.is_none()
        {{
            return Err("promoted claim_tier requires validation_report_ref");
        }}
        Ok(())
    }}
}}

#[cfg(test)]
mod tests {{
    use super::*;

    fn example_record() -> ArtifactRecord {{
        ArtifactRecord {{
            artifact_ref: "c4://artifact/example".to_string(),
            kind: "dataset".to_string(),
            content_hash: "blake3:af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262".to_string(),
            hash_algorithm: "BLAKE3".to_string(),
            size_bytes: 0,
            created_at: "2026-01-01T00:00:00Z".to_string(),
            producer: Producer {{
                subsystem: "S8".to_string(),
                version: "1.0.0".to_string(),
            }},
            lineage: Lineage {{
                input_refs: Vec::new(),
                code_ref: "git:project-argus@example".to_string(),
                environment_digest: "oci:sha256-example".to_string(),
                seeds: Vec::new(),
            }},
            claim_tier: None,
            validation_report_ref: None,
            schema_ref: None,
            retention: None,
        }}
    }}

    #[test]
    fn c4_schema_digest_is_generated() {{
        assert!(C4_SCHEMA_SHA256.starts_with("sha256:"));
    }}

    #[test]
    fn promoted_tier_requires_validation_report_ref() {{
        let mut record = example_record();
        assert_eq!(record.validate_promoted_tier(), Ok(()));

        record.claim_tier = Some(ClaimTier::NovelNeedsHuman);
        assert_eq!(
            record.validate_promoted_tier(),
            Err("promoted claim_tier requires validation_report_ref")
        );

        record.validation_report_ref = Some("c4://report/example".to_string());
        assert_eq!(record.validate_promoted_tier(), Ok(()));
    }}

    #[test]
    fn serde_round_trips_c4_artifact_record() {{
        let record = example_record();
        let json = serde_json::to_string(&record).expect("serialize record");
        let decoded: ArtifactRecord = serde_json::from_str(&json).expect("deserialize record");

        assert_eq!(decoded, record);
    }}
}}
'''


def render_rust_argusverify() -> str:
    report = json.dumps(C3_ARGUSVERIFY_VECTOR_REPORT, indent=12)
    expected_signature = c3_argusverify_vector_signature()
    return f'''// {HEADER}

use hmac::{{Hmac, KeyInit, Mac}};
use serde_json::{{json, Value}};
use sha2::Sha256;
use std::collections::BTreeMap;

pub const C3_SIGNATURE_ALGORITHM: &str = "hmac-sha256";
pub const C3_SIGNATURE_PREFIX: &str = "hmac-sha256:";
pub const SIGNATURE_VERIFICATION_ACCEPTED: &str = "signature_accepted";
pub const SIGNATURE_VERIFICATION_ABSTAIN: &str = "signature_abstain";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VerifierKey {{
    pub key_id: String,
    pub secret: Vec<u8>,
    pub revoked: bool,
}}

impl VerifierKey {{
    pub fn new(key_id: impl Into<String>, secret: impl Into<Vec<u8>>) -> Self {{
        Self {{
            key_id: key_id.into(),
            secret: secret.into(),
            revoked: false,
        }}
    }}
}}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct C3SignatureVerification {{
    pub valid: bool,
    pub reason: Option<String>,
    pub error_code: Option<String>,
    pub key_id: Option<String>,
    pub claim_tier: Option<String>,
    pub aggregate_passed: Option<bool>,
}}

pub trait VerifierTrustStore {{
    fn get_key(&self, key_id: &str) -> Option<&VerifierKey>;

    /// Return Some(Ok(())) to accept, Some(Err(reason)) to reject, or None to abstain.
    fn verify_signature_value(
        &self,
        _key_id: &str,
        _report_with_empty_signature: &Value,
        _signature_value: &str,
    ) -> Option<Result<(), String>> {{
        None
    }}
}}

#[derive(Debug, Default)]
pub struct InMemoryVerifierTrustStore {{
    keys: BTreeMap<String, VerifierKey>,
}}

impl InMemoryVerifierTrustStore {{
    pub fn new() -> Self {{
        Self::default()
    }}

    pub fn register_key(&mut self, key_id: impl Into<String>, secret: impl Into<Vec<u8>>) {{
        let key_id = key_id.into();
        self.keys
            .insert(key_id.clone(), VerifierKey::new(key_id, secret.into()));
    }}

    pub fn revoke_key(&mut self, key_id: &str) -> Result<(), String> {{
        let key = self
            .keys
            .get_mut(key_id)
            .ok_or_else(|| format!("unknown verifier key: {{key_id}}"))?;
        key.revoked = true;
        Ok(())
    }}
}}

impl VerifierTrustStore for InMemoryVerifierTrustStore {{
    fn get_key(&self, key_id: &str) -> Option<&VerifierKey> {{
        self.keys.get(key_id)
    }}
}}

pub fn sign_report(report: &Value, key_id: &str, secret: &[u8]) -> Result<Value, String> {{
    let mut signed = report.clone();
    let object = signed
        .as_object_mut()
        .ok_or_else(|| "C3 report must be a JSON object".to_string())?;
    object.insert(
        "signature".to_string(),
        json!({{
            "algorithm": C3_SIGNATURE_ALGORITHM,
            "key_id": key_id,
            "value": "",
        }}),
    );
    let signature = signature_value(&signed, secret)?;
    signed["signature"]["value"] = Value::String(signature);
    Ok(signed)
}}

pub fn verify_report(report: &Value, trust_store: &impl VerifierTrustStore) -> C3SignatureVerification {{
    let Some(signature) = report.get("signature").and_then(Value::as_object) else {{
        return invalid("signature_missing", None);
    }};
    let algorithm = signature.get("algorithm").and_then(Value::as_str);
    let key_id = signature.get("key_id").and_then(Value::as_str);
    let value = signature.get("value").and_then(Value::as_str);
    if algorithm != Some(C3_SIGNATURE_ALGORITHM) {{
        return invalid("algorithm_unsupported", key_id);
    }}
    let Some(key_id) = key_id else {{
        return invalid("key_missing", None);
    }};
    let Some(key) = trust_store.get_key(key_id) else {{
        return invalid("unknown_key", Some(key_id));
    }};
    if key.revoked {{
        return invalid("revoked_key", Some(key_id));
    }}
    let Some(value) = value else {{
        return invalid("signature_value_missing", Some(key_id));
    }};

    let mut unsigned = report.clone();
    unsigned["signature"] = json!({{
        "algorithm": C3_SIGNATURE_ALGORITHM,
        "key_id": key_id,
        "value": "",
    }});
    if let Some(delegated) = trust_store.verify_signature_value(key_id, &unsigned, value) {{
        if let Err(reason) = delegated {{
            return invalid(&reason, Some(key_id));
        }}
    }} else {{
        let Ok(expected) = signature_value(&unsigned, &key.secret) else {{
            return invalid("signature_invalid", Some(key_id));
        }};
        if !constant_time_eq(value.as_bytes(), expected.as_bytes()) {{
            return invalid("signature_invalid", Some(key_id));
        }}
    }}

    C3SignatureVerification {{
        valid: true,
        reason: None,
        error_code: None,
        key_id: Some(key_id.to_string()),
        claim_tier: report
            .get("claim_tier")
            .and_then(Value::as_str)
            .map(str::to_string),
        aggregate_passed: report
            .get("aggregate")
            .and_then(|aggregate| aggregate.get("passed"))
            .and_then(Value::as_bool),
    }}
}}

fn invalid(reason: &str, key_id: Option<&str>) -> C3SignatureVerification {{
    C3SignatureVerification {{
        valid: false,
        reason: Some(reason.to_string()),
        error_code: Some(error_code(reason).to_string()),
        key_id: key_id.map(str::to_string),
        claim_tier: None,
        aggregate_passed: None,
    }}
}}

fn error_code(reason: &str) -> &'static str {{
    match reason {{
        "signature_missing" => "UNSIGNED",
        "algorithm_unsupported" => "ALGORITHM_UNSUPPORTED",
        "key_missing" => "KEY_MISSING",
        "unknown_key" => "UNKNOWN_KEY",
        "revoked_key" => "REVOKED_KEY",
        "signature_value_missing" => "SIGNATURE_VALUE_MISSING",
        "signature_invalid" => "SIGNATURE_INVALID",
        _ => "SIGNATURE_INVALID",
    }}
}}

fn signature_value(report_with_empty_signature: &Value, secret: &[u8]) -> Result<String, String> {{
    let mut mac = Hmac::<Sha256>::new_from_slice(secret).map_err(|error| error.to_string())?;
    mac.update(canonical_json(report_with_empty_signature)?.as_bytes());
    Ok(C3_SIGNATURE_PREFIX.to_string() + &hex_lower(&mac.finalize().into_bytes()))
}}

fn canonical_json(value: &Value) -> Result<String, String> {{
    match value {{
        Value::Null => Ok("null".to_string()),
        Value::Bool(value) => Ok(if *value {{ "true" }} else {{ "false" }}.to_string()),
        Value::Number(value) => Ok(canonical_number(value)),
        Value::String(value) => serde_json::to_string(value).map_err(|error| error.to_string()),
        Value::Array(values) => {{
            let rendered = values
                .iter()
                .map(canonical_json)
                .collect::<Result<Vec<_>, _>>()?;
            let mut output = String::from("[");
            output.push_str(&rendered.join(","));
            output.push(']');
            Ok(output)
        }}
        Value::Object(map) => {{
            let mut keys = map.keys().collect::<Vec<_>>();
            keys.sort();
            let rendered = keys
                .into_iter()
                .map(|key| {{
                    let mut output = serde_json::to_string(key).map_err(|error| error.to_string())?;
                    output.push(':');
                    output.push_str(&canonical_json(&map[key])?);
                    Ok(output)
                }})
                .collect::<Result<Vec<String>, String>>()?;
            let mut output = String::from("{{");
            output.push_str(&rendered.join(","));
            output.push('}}');
            Ok(output)
        }}
    }}
}}

fn canonical_number(value: &serde_json::Number) -> String {{
    let text = value.to_string().replace('E', "e");
    if let Some((mantissa, exponent)) = text.split_once('e') {{
        let normalized_exponent = normalize_exponent(exponent);
        if let Some(fixed) = exponent_to_fixed_if_javascript_decimal(mantissa, &normalized_exponent) {{
            return fixed;
        }}
        return format!(
            "{{}}e{{}}",
            trim_decimal_text(mantissa),
            normalized_exponent
        );
    }}
    trim_decimal_text(&text)
}}

fn trim_decimal_text(text: &str) -> String {{
    let mut trimmed = text;
    if text.contains('.') {{
        trimmed = trimmed.trim_end_matches('0').trim_end_matches('.');
    }}
    if trimmed == "-0" {{
        "0".to_string()
    }} else {{
        trimmed.to_string()
    }}
}}

fn normalize_exponent(exponent: &str) -> String {{
    let (sign, digits) = match exponent.as_bytes().first().copied() {{
        Some(b'+') => ("", &exponent[1..]),
        Some(b'-') => ("-", &exponent[1..]),
        _ => ("", exponent),
    }};
    let digits = digits.trim_start_matches('0');
    let digits = if digits.is_empty() {{ "0" }} else {{ digits }};
    format!("{{sign}}{{digits}}")
}}

fn exponent_to_fixed_if_javascript_decimal(mantissa: &str, exponent: &str) -> Option<String> {{
    let exponent_value = exponent.parse::<isize>().ok()?;
    let (sign, body) = if let Some(body) = mantissa.strip_prefix('-') {{
        ("-", body)
    }} else {{
        ("", mantissa)
    }};
    let (integer, fraction) = if let Some((integer, fraction)) = body.split_once('.') {{
        (integer, fraction)
    }} else {{
        (body, "")
    }};
    let digits = format!("{{integer}}{{fraction}}");
    if digits.is_empty() || digits.chars().all(|character| character == '0') {{
        return Some("0".to_string());
    }}
    let decimal_exponent = exponent_value + digits.len() as isize - fraction.len() as isize - 1;
    if !(-6..21).contains(&decimal_exponent) {{
        return None;
    }}
    let scale = exponent_value - fraction.len() as isize;
    if scale >= 0 {{
        return Some(format!("{{sign}}{{digits}}{{}}", "0".repeat(scale as usize)));
    }}
    let decimal_position = digits.len() as isize + scale;
    let fixed = if decimal_position > 0 {{
        let decimal_position = decimal_position as usize;
        format!(
            "{{sign}}{{}}.{{}}",
            &digits[..decimal_position],
            &digits[decimal_position..]
        )
    }} else {{
        format!(
            "{{sign}}0.{{}}{{digits}}",
            "0".repeat(decimal_position.unsigned_abs())
        )
    }};
    Some(trim_decimal_text(&fixed))
}}

fn hex_lower(bytes: &[u8]) -> String {{
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut output = String::with_capacity(bytes.len() * 2);
    for byte in bytes {{
        output.push(HEX[(byte >> 4) as usize] as char);
        output.push(HEX[(byte & 0x0f) as usize] as char);
    }}
    output
}}

fn constant_time_eq(left: &[u8], right: &[u8]) -> bool {{
    if left.len() != right.len() {{
        return false;
    }}
    left.iter()
        .zip(right.iter())
        .fold(0u8, |acc, (left, right)| acc | (left ^ right))
        == 0
}}

#[cfg(test)]
mod tests {{
    use super::*;

    fn vector_report() -> Value {{
        serde_json::from_str(r#"{report}"#).expect("vector report JSON")
    }}

    #[test]
    fn argusverify_accepts_valid_vector_and_rejects_tamper_unsigned_and_revoked() {{
        let mut trust_store = InMemoryVerifierTrustStore::new();
        trust_store.register_key("{C3_ARGUSVERIFY_KEY_ID}", "{C3_ARGUSVERIFY_SECRET}".as_bytes().to_vec());

        let signed = sign_report(
            &vector_report(),
            "{C3_ARGUSVERIFY_KEY_ID}",
            "{C3_ARGUSVERIFY_SECRET}".as_bytes(),
        )
        .expect("sign vector");
        assert_eq!(signed["signature"]["value"], "{expected_signature}");

        let valid = verify_report(&signed, &trust_store);
        assert!(valid.valid);
        assert_eq!(valid.claim_tier.as_deref(), Some("recapitulated-known"));
        assert_eq!(valid.aggregate_passed, Some(true));

        trust_store.register_key("s3-key-v2", "s3-secret-v2".as_bytes().to_vec());
        assert!(verify_report(&signed, &trust_store).valid);
        let signed_v2 = sign_report(
            &vector_report(),
            "s3-key-v2",
            "s3-secret-v2".as_bytes(),
        )
        .expect("sign rotated vector");
        assert_eq!(
            verify_report(&signed_v2, &trust_store).key_id.as_deref(),
            Some("s3-key-v2")
        );

        let mut tampered = signed.clone();
        tampered["aggregate"]["score"] = json!(0.99);
        let tampered_verification = verify_report(&tampered, &trust_store);
        assert!(!tampered_verification.valid);
        assert_eq!(
            tampered_verification.error_code.as_deref(),
            Some("SIGNATURE_INVALID")
        );

        let mut unsigned = signed.clone();
        unsigned.as_object_mut().expect("object").remove("signature");
        let unsigned_verification = verify_report(&unsigned, &trust_store);
        assert!(!unsigned_verification.valid);
        assert_eq!(unsigned_verification.error_code.as_deref(), Some("UNSIGNED"));

        trust_store
            .revoke_key("{C3_ARGUSVERIFY_KEY_ID}")
            .expect("revoke key");
        let revoked_verification = verify_report(&signed, &trust_store);
        assert!(!revoked_verification.valid);
        assert_eq!(revoked_verification.error_code.as_deref(), Some("REVOKED_KEY"));
    }}

    struct DelegatingTrustStore {{
        key: VerifierKey,
        accepted_signature: String,
    }}

    impl VerifierTrustStore for DelegatingTrustStore {{
        fn get_key(&self, key_id: &str) -> Option<&VerifierKey> {{
            if key_id == self.key.key_id {{
                Some(&self.key)
            }} else {{
                None
            }}
        }}

        fn verify_signature_value(
            &self,
            key_id: &str,
            report_with_empty_signature: &Value,
            signature_value: &str,
        ) -> Option<Result<(), String>> {{
            assert_eq!(key_id, self.key.key_id);
            assert_eq!(report_with_empty_signature["signature"]["value"], "");
            if signature_value == self.accepted_signature {{
                Some(Ok(()))
            }} else {{
                Some(Err("signature_invalid".to_string()))
            }}
        }}
    }}

    #[test]
    fn argusverify_delegates_signature_value_for_secretless_trust_store() {{
        let signed = sign_report(
            &vector_report(),
            "{C3_ARGUSVERIFY_KEY_ID}",
            "{C3_ARGUSVERIFY_SECRET}".as_bytes(),
        )
        .expect("sign vector");
        let accepted_signature = signed["signature"]["value"]
            .as_str()
            .expect("signature string")
            .to_string();
        let trust_store = DelegatingTrustStore {{
            key: VerifierKey::new("{C3_ARGUSVERIFY_KEY_ID}", Vec::<u8>::new()),
            accepted_signature,
        }};

        let valid = verify_report(&signed, &trust_store);
        assert!(valid.valid);

        let mut bad_signature = signed.clone();
        bad_signature["signature"]["value"] = Value::String("hmac-sha256:bad".to_string());
        let invalid = verify_report(&bad_signature, &trust_store);
        assert!(!invalid.valid);
        assert_eq!(invalid.error_code.as_deref(), Some("SIGNATURE_INVALID"));
    }}

    struct AbstainingTrustStore {{
        key: VerifierKey,
    }}

    impl VerifierTrustStore for AbstainingTrustStore {{
        fn get_key(&self, key_id: &str) -> Option<&VerifierKey> {{
            if key_id == self.key.key_id {{
                Some(&self.key)
            }} else {{
                None
            }}
        }}

        fn verify_signature_value(
            &self,
            key_id: &str,
            report_with_empty_signature: &Value,
            signature_value: &str,
        ) -> Option<Result<(), String>> {{
            assert_eq!(key_id, self.key.key_id);
            assert_eq!(report_with_empty_signature["signature"]["value"], "");
            assert!(signature_value.starts_with(C3_SIGNATURE_PREFIX));
            None
        }}
    }}

    #[test]
    fn argusverify_abstaining_delegate_falls_back_and_fails_closed() {{
        let signed = sign_report(
            &vector_report(),
            "{C3_ARGUSVERIFY_KEY_ID}",
            "{C3_ARGUSVERIFY_SECRET}".as_bytes(),
        )
        .expect("sign vector");
        let trust_store = AbstainingTrustStore {{
            key: VerifierKey::new("{C3_ARGUSVERIFY_KEY_ID}", Vec::<u8>::new()),
        }};

        let invalid = verify_report(&signed, &trust_store);
        assert!(!invalid.valid);
        assert_eq!(invalid.reason.as_deref(), Some("signature_invalid"));
        assert_eq!(invalid.error_code.as_deref(), Some("SIGNATURE_INVALID"));
    }}
}}
'''


def generated_files() -> dict[Path, str]:
    items = contracts()
    c4 = next(item for item in items if item["id"] == "C4")
    return {
        PYTHON_CONTRACTS: render_python_contracts(items),
        PYTHON_C4: render_python_c4(c4["schema_sha256"]),
        PYTHON_INIT: render_python_init(),
        TYPESCRIPT_PACKAGE: render_typescript_package(),
        TYPESCRIPT_CONTRACTS: render_typescript_contracts(items),
        TYPESCRIPT_C4: render_typescript_c4(c4["schema_sha256"]),
        TYPESCRIPT_ARGUSVERIFY: render_typescript_argusverify(),
        TYPESCRIPT_TSCONFIG: render_typescript_tsconfig(),
        TYPESCRIPT_C4_SMOKE: render_typescript_c4_smoke(c4["schema_sha256"]),
        TYPESCRIPT_ARGUSVERIFY_SMOKE: render_typescript_argusverify_smoke(),
        RUST_MANIFEST: render_rust_manifest(),
        RUST_LIB: render_rust_lib(items),
        RUST_C4: render_rust_c4(c4["schema_sha256"]),
        RUST_ARGUSVERIFY: render_rust_argusverify(),
    }


def write_files(files: dict[Path, str]) -> None:
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def check_files(files: dict[Path, str]) -> int:
    drifted: list[str] = []
    missing: list[str] = []
    for path, expected in files.items():
        if not path.exists():
            missing.append(str(path.relative_to(ROOT)))
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            drifted.append(str(path.relative_to(ROOT)))

    if missing or drifted:
        if missing:
            print("Missing generated bindings:", ", ".join(missing), file=sys.stderr)
        if drifted:
            print("Generated bindings are out of date:", ", ".join(drifted), file=sys.stderr)
        print("Run: python3 scripts/generate_bindings.py --write", file=sys.stderr)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write generated bindings")
    mode.add_argument("--check", action="store_true", help="check generated bindings for drift")
    args = parser.parse_args()

    files = generated_files()
    if args.write:
        write_files(files)
        return 0
    return check_files(files)


if __name__ == "__main__":
    sys.exit(main())
