#!/usr/bin/env python3
"""Generate lightweight contract binding metadata from the schema manifest."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTRACTS_DIR = ROOT / "schemas" / "contracts"
MANIFEST_PATH = CONTRACTS_DIR / "manifest.json"
PYTHON_CONTRACTS = ROOT / "bindings" / "python" / "argus_contracts" / "contracts.py"
PYTHON_INIT = ROOT / "bindings" / "python" / "argus_contracts" / "__init__.py"
TYPESCRIPT_PACKAGE = ROOT / "bindings" / "typescript" / "package.json"
TYPESCRIPT_CONTRACTS = ROOT / "bindings" / "typescript" / "src" / "contracts.ts"
RUST_MANIFEST = ROOT / "bindings" / "rust" / "Cargo.toml"
RUST_LIB = ROOT / "bindings" / "rust" / "src" / "lib.rs"

HEADER = "Generated by scripts/generate_bindings.py; do not edit."


def load_manifest() -> dict:
    with MANIFEST_PATH.open(encoding="utf-8") as handle:
        return json.load(handle)


def contracts() -> list[dict]:
    items = []
    for raw in load_manifest()["contracts"]:
        item = dict(raw)
        item["schema_sha256"] = schema_sha256(CONTRACTS_DIR / item["schema"])
        items.append(item)
    return sorted(items, key=lambda item: item["id"])


def schema_sha256(path: Path) -> str:
    with path.open(encoding="utf-8") as handle:
        value = json.load(handle)
    canonical = json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return "sha256:" + hashlib.sha256(canonical).hexdigest()


def py_repr(value: object) -> str:
    return repr(value).replace("'", '"')


def render_python_contracts(items: list[dict]) -> str:
    rows = []
    for item in items:
        rows.append(
            "    Contract("
            f'id="{item["id"]}", '
            f'name="{item["name"]}", '
            f'owner="{item["owner"]}", '
            f'version="{item["version"]}", '
            f'schema="{item["schema"]}", '
            f'schema_sha256="{item["schema_sha256"]}", '
            f"consumers={py_repr(item['consumers'])}"
            ")"
        )
    return "\n".join(
        [
            f'"""{HEADER}"""',
            "",
            "from __future__ import annotations",
            "",
            "from dataclasses import dataclass",
            "",
            "",
            "@dataclass(frozen=True)",
            "class Contract:",
            "    id: str",
            "    name: str",
            "    owner: str",
            "    version: str",
            "    schema: str",
            "    schema_sha256: str",
            "    consumers: list[str]",
            "",
            "",
            "CONTRACTS: tuple[Contract, ...] = (",
            ",\n".join(rows),
            ")",
            "",
            "CONTRACT_BY_ID: dict[str, Contract] = {contract.id: contract for contract in CONTRACTS}",
            "",
        ]
    )


def render_python_init() -> str:
    return "\n".join(
        [
            f'"""{HEADER}"""',
            "",
            "from .contracts import CONTRACT_BY_ID, CONTRACTS, Contract",
            "",
            '__all__ = ["CONTRACTS", "CONTRACT_BY_ID", "Contract"]',
            "",
        ]
    )


def render_typescript_package() -> str:
    package = {
        "name": "@project-argus/contracts",
        "version": "0.0.0",
        "private": True,
        "type": "module",
        "exports": {
            ".": "./src/contracts.ts"
        }
    }
    return json.dumps(package, indent=2, sort_keys=False) + "\n"


def render_typescript_contracts(items: list[dict]) -> str:
    ids = " | ".join(json.dumps(item["id"]) for item in items)
    payload = json.dumps(items, indent=2)
    return "\n".join(
        [
            f"// {HEADER}",
            "",
            f"export type ContractId = {ids};",
            "",
            "export interface Contract {",
            "  id: ContractId;",
            "  name: string;",
            "  owner: string;",
            "  version: string;",
            "  schema: string;",
            "  schema_sha256: string;",
            "  consumers: readonly string[];",
            "}",
            "",
            f"export const contracts = {payload} as const satisfies readonly Contract[];",
            "",
            "export const contractById = Object.fromEntries(",
            "  contracts.map((contract) => [contract.id, contract]),",
            ") as Record<ContractId, Contract>;",
            "",
        ]
    )


def rust_array(values: list[str]) -> str:
    return "&[" + ", ".join(json.dumps(value) for value in values) + "]"


def render_rust_manifest() -> str:
    return "\n".join(
        [
            "[package]",
            'name = "argus-contracts"',
            'version = "0.0.0"',
            'edition = "2021"',
            'publish = false',
            "",
            "[lib]",
            'path = "src/lib.rs"',
            "",
            "[dependencies]",
            'blake3 = "1"',
            'hmac = "0.13"',
            'postgres = { version = "0.19", features = ["with-serde_json-1"] }',
            'serde_json = "1"',
            'sha2 = "0.11"',
            "",
        ]
    )


def render_rust_lib(items: list[dict]) -> str:
    rows = []
    for item in items:
        rows.append(
            "    Contract { "
            f'id: "{item["id"]}", '
            f'name: "{item["name"]}", '
            f'owner: "{item["owner"]}", '
            f'version: "{item["version"]}", '
            f'schema: "{item["schema"]}", '
            f'schema_sha256: "{item["schema_sha256"]}", '
            f"consumers: {rust_array(item['consumers'])} "
            "},"
        )
    return "\n".join(
        [
            f"// {HEADER}",
            "",
            "pub mod hash;",
            "pub mod ledger;",
            "",
            "pub use hash::{hash_blob, hash_blob_stream, hash_bytes, BlobHasher, HashBlob, HashBlobError, BLAKE3_PREFIX, CANON_VERSION};",
            "pub use ledger::{ArtifactRecordDraft, CheckpointSigner, MerkleCheckpoint, PostgresLedgerWriter};",
            "",
            "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
            "pub struct Contract {",
            "    pub id: &'static str,",
            "    pub name: &'static str,",
            "    pub owner: &'static str,",
            "    pub version: &'static str,",
            "    pub schema: &'static str,",
            "    pub schema_sha256: &'static str,",
            "    pub consumers: &'static [&'static str],",
            "}",
            "",
            "pub const CONTRACTS: &[Contract] = &[",
            "\n".join(rows),
            "];",
            "",
            "pub fn contract_by_id(id: &str) -> Option<&'static Contract> {",
            "    CONTRACTS.iter().find(|contract| contract.id == id)",
            "}",
            "",
        ]
    )


def generated_files() -> dict[Path, str]:
    items = contracts()
    return {
        PYTHON_CONTRACTS: render_python_contracts(items),
        PYTHON_INIT: render_python_init(),
        TYPESCRIPT_PACKAGE: render_typescript_package(),
        TYPESCRIPT_CONTRACTS: render_typescript_contracts(items),
        RUST_MANIFEST: render_rust_manifest(),
        RUST_LIB: render_rust_lib(items),
    }


def write_files(files: dict[Path, str]) -> None:
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def check_files(files: dict[Path, str]) -> int:
    drifted: list[str] = []
    missing: list[str] = []
    for path, expected in files.items():
        if not path.exists():
            missing.append(str(path.relative_to(ROOT)))
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            drifted.append(str(path.relative_to(ROOT)))

    if missing or drifted:
        if missing:
            print("Missing generated bindings:", ", ".join(missing), file=sys.stderr)
        if drifted:
            print("Generated bindings are out of date:", ", ".join(drifted), file=sys.stderr)
        print("Run: python3 scripts/generate_bindings.py --write", file=sys.stderr)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write generated bindings")
    mode.add_argument("--check", action="store_true", help="check generated bindings for drift")
    args = parser.parse_args()

    files = generated_files()
    if args.write:
        write_files(files)
        return 0
    return check_files(files)


if __name__ == "__main__":
    sys.exit(main())
