#!/usr/bin/env python3
"""Generate lightweight contract binding metadata from the schema manifest."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTRACTS_DIR = ROOT / "schemas" / "contracts"
MANIFEST_PATH = CONTRACTS_DIR / "manifest.json"
PYTHON_CONTRACTS = ROOT / "bindings" / "python" / "argus_contracts" / "contracts.py"
PYTHON_C4 = ROOT / "bindings" / "python" / "argus_contracts" / "c4.py"
PYTHON_INIT = ROOT / "bindings" / "python" / "argus_contracts" / "__init__.py"
TYPESCRIPT_PACKAGE = ROOT / "bindings" / "typescript" / "package.json"
TYPESCRIPT_CONTRACTS = ROOT / "bindings" / "typescript" / "src" / "contracts.ts"
TYPESCRIPT_C4 = ROOT / "bindings" / "typescript" / "src" / "c4.ts"
TYPESCRIPT_TSCONFIG = ROOT / "bindings" / "typescript" / "tsconfig.json"
TYPESCRIPT_C4_SMOKE = ROOT / "bindings" / "typescript" / "test" / "c4-smoke.ts"
RUST_MANIFEST = ROOT / "bindings" / "rust" / "Cargo.toml"
RUST_LIB = ROOT / "bindings" / "rust" / "src" / "lib.rs"
RUST_C4 = ROOT / "bindings" / "rust" / "src" / "c4.rs"

HEADER = "Generated by scripts/generate_bindings.py; do not edit."


def load_manifest() -> dict:
    with MANIFEST_PATH.open(encoding="utf-8") as handle:
        return json.load(handle)


def contracts() -> list[dict]:
    items = []
    for raw in load_manifest()["contracts"]:
        item = dict(raw)
        item["schema_sha256"] = schema_sha256(CONTRACTS_DIR / item["schema"])
        items.append(item)
    return sorted(items, key=lambda item: item["id"])


def schema_sha256(path: Path) -> str:
    with path.open(encoding="utf-8") as handle:
        value = json.load(handle)
    canonical = json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return "sha256:" + hashlib.sha256(canonical).hexdigest()


def py_repr(value: object) -> str:
    return repr(value).replace("'", '"')


def render_python_contracts(items: list[dict]) -> str:
    rows = []
    for item in items:
        rows.append(
            "    Contract("
            f'id="{item["id"]}", '
            f'name="{item["name"]}", '
            f'owner="{item["owner"]}", '
            f'version="{item["version"]}", '
            f'schema="{item["schema"]}", '
            f'schema_sha256="{item["schema_sha256"]}", '
            f"consumers={py_repr(item['consumers'])}"
            ")"
        )
    return "\n".join(
        [
            f'"""{HEADER}"""',
            "",
            "from __future__ import annotations",
            "",
            "from dataclasses import dataclass",
            "",
            "",
            "@dataclass(frozen=True)",
            "class Contract:",
            "    id: str",
            "    name: str",
            "    owner: str",
            "    version: str",
            "    schema: str",
            "    schema_sha256: str",
            "    consumers: list[str]",
            "",
            "",
            "CONTRACTS: tuple[Contract, ...] = (",
            ",\n".join(rows),
            ")",
            "",
            "CONTRACT_BY_ID: dict[str, Contract] = {contract.id: contract for contract in CONTRACTS}",
            "",
        ]
    )


def render_python_init() -> str:
    return "\n".join(
        [
            f'"""{HEADER}"""',
            "",
            "from .c4 import (",
            "    ArtifactRecord,",
            "    ArtifactRef,",
            "    C4_SCHEMA_SHA256,",
            "    ClaimTier,",
            "    HashRef,",
            "    Lineage,",
            "    Producer,",
            "    RetentionPolicy,",
            "    validate_artifact_record,",
            ")",
            "from .contracts import CONTRACT_BY_ID, CONTRACTS, Contract",
            "",
            "__all__ = [",
            '    "ArtifactRecord",',
            '    "ArtifactRef",',
            '    "C4_SCHEMA_SHA256",',
            '    "ClaimTier",',
            '    "CONTRACTS",',
            '    "CONTRACT_BY_ID",',
            '    "Contract",',
            '    "HashRef",',
            '    "Lineage",',
            '    "Producer",',
            '    "RetentionPolicy",',
            '    "validate_artifact_record",',
            "]",
            "",
        ]
    )


def render_typescript_package() -> str:
    package = {
        "name": "@project-argus/contracts",
        "version": "0.0.0",
        "private": True,
        "type": "module",
        "scripts": {
            "build": "tsc --project tsconfig.json",
            "test": "npm run build && node dist/test/c4-smoke.js",
        },
        "exports": {
            ".": "./src/contracts.ts",
            "./c4": "./src/c4.ts",
        },
        "dependencies": {
            "@noble/hashes": "1.8.0",
        },
        "devDependencies": {
            "@types/node": "20.10.8",
            "typescript": "6.0.3",
        },
    }
    return json.dumps(package, indent=2, sort_keys=False) + "\n"


def render_typescript_tsconfig() -> str:
    config = {
        "compilerOptions": {
            "target": "ES2022",
            "module": "NodeNext",
            "moduleResolution": "NodeNext",
            "strict": True,
            "noEmitOnError": True,
            "esModuleInterop": True,
            "skipLibCheck": True,
            "types": ["node"],
            "outDir": "dist",
            "rootDir": ".",
        },
        "include": ["src/**/*.ts", "test/**/*.ts"],
    }
    return json.dumps(config, indent=2, sort_keys=False) + "\n"


def render_typescript_contracts(items: list[dict]) -> str:
    ids = " | ".join(json.dumps(item["id"]) for item in items)
    payload = json.dumps(items, indent=2)
    lookup = "\n".join(f"  {json.dumps(item['id'])}: contracts[{index}]," for index, item in enumerate(items))
    return "\n".join(
        [
            f"// {HEADER}",
            "",
            f"export type ContractId = {ids};",
            "",
            "export interface Contract {",
            "  id: ContractId;",
            "  name: string;",
            "  owner: string;",
            "  version: string;",
            "  schema: string;",
            "  schema_sha256: string;",
            "  consumers: readonly string[];",
            "}",
            "",
            f"export const contracts = {payload} as const satisfies readonly Contract[];",
            "",
            "export const contractById = {",
            lookup,
            "} satisfies Record<ContractId, Contract>;",
            "",
        ]
    )


def render_python_c4(c4_schema_sha256: str) -> str:
    return f'''"""{HEADER}"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Any, Literal, Mapping

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


C4_SCHEMA_SHA256 = "{c4_schema_sha256}"

ArtifactRef = Annotated[str, Field(pattern=r"^c4://[A-Za-z0-9._:/-]+$")]
HashRef = Annotated[str, Field(pattern=r"^blake3:[a-f0-9]{{64}}$")]
ClaimTier = Literal["ran-toy", "recapitulated-known", "novel-needs-human"]


class Producer(BaseModel):
    model_config = ConfigDict(extra="forbid")

    subsystem: str = Field(pattern=r"^S\\d+$")
    version: str = Field(pattern=r"^\\d+\\.\\d+\\.\\d+$")


class Lineage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    input_refs: list[ArtifactRef]
    code_ref: str = Field(min_length=1)
    environment_digest: str = Field(min_length=1)
    seeds: list[str]

    @field_validator("input_refs")
    @classmethod
    def _input_refs_are_unique(cls, value: list[str]) -> list[str]:
        if len(value) != len(set(value)):
            raise ValueError("input_refs must be unique")
        return value

    @field_validator("seeds")
    @classmethod
    def _seeds_are_unique(cls, value: list[str]) -> list[str]:
        if len(value) != len(set(value)):
            raise ValueError("seeds must be unique")
        return value


class RetentionPolicy(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    class_: Literal["write_once", "scratch", "hold"] | None = Field(default=None, alias="class")
    retain_until: datetime | None = None
    hold_id: str | None = Field(default=None, min_length=1)


class ArtifactRecord(BaseModel):
    model_config = ConfigDict(extra="forbid")

    artifact_ref: ArtifactRef
    kind: str = Field(min_length=1)
    content_hash: HashRef
    hash_algorithm: Literal["BLAKE3"]
    size_bytes: int = Field(ge=0)
    created_at: datetime
    producer: Producer
    lineage: Lineage
    claim_tier: ClaimTier | None = None
    validation_report_ref: ArtifactRef | None = None
    schema_ref: str | None = None
    retention: RetentionPolicy | None = None

    @model_validator(mode="after")
    def _promoted_tier_requires_validation_report(self) -> ArtifactRecord:
        if self.claim_tier in {{"recapitulated-known", "novel-needs-human"}} and self.validation_report_ref is None:
            raise ValueError("promoted claim_tier requires validation_report_ref")
        return self


def validate_artifact_record(payload: Mapping[str, Any]) -> ArtifactRecord:
    return ArtifactRecord.model_validate(payload)
'''


def render_typescript_c4(c4_schema_sha256: str) -> str:
    return f'''// {HEADER}

import {{ blake3 }} from "@noble/hashes/blake3.js";
import {{ bytesToHex }} from "@noble/hashes/utils.js";

export const C4_SCHEMA_SHA256 = "{c4_schema_sha256}";
export const BLAKE3_PREFIX = "blake3:";
export const CANON_VERSION = "argus-jcs-v1";

export type ArtifactRef = `c4://${{string}}`;
export type HashRef = `blake3:${{string}}`;
export type ClaimTier = "ran-toy" | "recapitulated-known" | "novel-needs-human";

export interface Producer {{
  subsystem: string;
  version: string;
}}

export interface Lineage {{
  input_refs: readonly ArtifactRef[];
  code_ref: string;
  environment_digest: string;
  seeds: readonly string[];
}}

export interface RetentionPolicy {{
  class?: "write_once" | "scratch" | "hold";
  retain_until?: string;
  hold_id?: string;
}}

export interface ArtifactRecord {{
  artifact_ref: ArtifactRef;
  kind: string;
  content_hash: HashRef;
  hash_algorithm: "BLAKE3";
  size_bytes: number;
  created_at: string;
  producer: Producer;
  lineage: Lineage;
  claim_tier?: ClaimTier;
  validation_report_ref?: ArtifactRef;
  schema_ref?: string;
  retention?: RetentionPolicy;
}}

export interface HashBlob {{
  content_hash: HashRef;
  size_bytes: number;
  canon_version: typeof CANON_VERSION;
}}

const artifactRefPattern = /^c4:\\/\\/[A-Za-z0-9._:/-]+$/;
const hashRefPattern = /^blake3:[a-f0-9]{{64}}$/;
const subsystemPattern = /^S\\d+$/;
const versionPattern = /^\\d+\\.\\d+\\.\\d+$/;

export function hashBlob(payload: Uint8Array): HashBlob {{
  return {{
    content_hash: `${{BLAKE3_PREFIX}}${{bytesToHex(blake3(payload))}}` as HashRef,
    size_bytes: payload.byteLength,
    canon_version: CANON_VERSION,
  }};
}}

export function assertArtifactRecord(payload: unknown): asserts payload is ArtifactRecord {{
  const record = assertRecord(payload, "artifact");
  assertKeys(record, [
    "artifact_ref",
    "kind",
    "content_hash",
    "hash_algorithm",
    "size_bytes",
    "created_at",
    "producer",
    "lineage",
    "claim_tier",
    "validation_report_ref",
    "schema_ref",
    "retention",
  ], "artifact");
  assertPattern(record.artifact_ref, artifactRefPattern, "artifact.artifact_ref");
  assertMinString(record.kind, 1, "artifact.kind");
  assertPattern(record.content_hash, hashRefPattern, "artifact.content_hash");
  assertLiteral(record.hash_algorithm, "BLAKE3", "artifact.hash_algorithm");
  assertNonNegativeInteger(record.size_bytes, "artifact.size_bytes");
  assertDateTime(record.created_at, "artifact.created_at");
  assertProducer(record.producer, "artifact.producer");
  assertLineage(record.lineage, "artifact.lineage");

  if (record.claim_tier !== undefined) {{
    assertOneOf(record.claim_tier, ["ran-toy", "recapitulated-known", "novel-needs-human"], "artifact.claim_tier");
  }}
  if (record.validation_report_ref !== undefined) {{
    assertPattern(record.validation_report_ref, artifactRefPattern, "artifact.validation_report_ref");
  }}
  if (record.schema_ref !== undefined) {{
    assertMinString(record.schema_ref, 0, "artifact.schema_ref");
  }}
  if (record.retention !== undefined) {{
    assertRetention(record.retention, "artifact.retention");
  }}
  if (
    (record.claim_tier === "recapitulated-known" || record.claim_tier === "novel-needs-human") &&
    record.validation_report_ref === undefined
  ) {{
    throw new TypeError("artifact.validation_report_ref is required for promoted claim_tier");
  }}
}}

function assertProducer(value: unknown, path: string): asserts value is Producer {{
  const record = assertRecord(value, path);
  assertKeys(record, ["subsystem", "version"], path);
  assertPattern(record.subsystem, subsystemPattern, `${{path}}.subsystem`);
  assertPattern(record.version, versionPattern, `${{path}}.version`);
}}

function assertLineage(value: unknown, path: string): asserts value is Lineage {{
  const record = assertRecord(value, path);
  assertKeys(record, ["input_refs", "code_ref", "environment_digest", "seeds"], path);
  assertStringArray(record.input_refs, `${{path}}.input_refs`, artifactRefPattern);
  assertMinString(record.code_ref, 1, `${{path}}.code_ref`);
  assertMinString(record.environment_digest, 1, `${{path}}.environment_digest`);
  assertStringArray(record.seeds, `${{path}}.seeds`);
}}

function assertRetention(value: unknown, path: string): asserts value is RetentionPolicy {{
  const record = assertRecord(value, path);
  assertKeys(record, ["class", "retain_until", "hold_id"], path);
  if (record.class !== undefined) {{
    assertOneOf(record.class, ["write_once", "scratch", "hold"], `${{path}}.class`);
  }}
  if (record.retain_until !== undefined) {{
    assertDateTime(record.retain_until, `${{path}}.retain_until`);
  }}
  if (record.hold_id !== undefined) {{
    assertMinString(record.hold_id, 1, `${{path}}.hold_id`);
  }}
}}

function assertRecord(value: unknown, path: string): Record<string, unknown> {{
  if (typeof value !== "object" || value === null || Array.isArray(value)) {{
    throw new TypeError(`${{path}} must be an object`);
  }}
  return value as Record<string, unknown>;
}}

function assertKeys(record: Record<string, unknown>, allowedKeys: readonly string[], path: string): void {{
  const allowed = new Set(allowedKeys);
  for (const key of Object.keys(record)) {{
    if (!allowed.has(key)) {{
      throw new TypeError(`${{path}}.${{key}} is not allowed`);
    }}
  }}
  for (const key of allowedKeys) {{
    if (!(key in record) && requiredKeys(path).has(key)) {{
      throw new TypeError(`${{path}}.${{key}} is required`);
    }}
  }}
}}

function requiredKeys(path: string): Set<string> {{
  if (path === "artifact") {{
    return new Set(["artifact_ref", "kind", "content_hash", "hash_algorithm", "size_bytes", "created_at", "producer", "lineage"]);
  }}
  if (path.endsWith(".producer")) {{
    return new Set(["subsystem", "version"]);
  }}
  if (path.endsWith(".lineage")) {{
    return new Set(["input_refs", "code_ref", "environment_digest", "seeds"]);
  }}
  return new Set();
}}

function assertPattern(value: unknown, pattern: RegExp, path: string): asserts value is string {{
  assertMinString(value, 0, path);
  if (!pattern.test(value)) {{
    throw new TypeError(`${{path}} does not match required pattern`);
  }}
}}

function assertMinString(value: unknown, minLength: number, path: string): asserts value is string {{
  if (typeof value !== "string" || value.length < minLength) {{
    throw new TypeError(`${{path}} must be a string with length >= ${{minLength}}`);
  }}
}}

function assertLiteral<T extends string>(value: unknown, expected: T, path: string): asserts value is T {{
  if (value !== expected) {{
    throw new TypeError(`${{path}} must equal ${{expected}}`);
  }}
}}

function assertOneOf<T extends string>(value: unknown, allowed: readonly T[], path: string): asserts value is T {{
  if (typeof value !== "string" || !allowed.includes(value as T)) {{
    throw new TypeError(`${{path}} must be one of ${{allowed.join(", ")}}`);
  }}
}}

function assertNonNegativeInteger(value: unknown, path: string): asserts value is number {{
  if (!Number.isSafeInteger(value) || (value as number) < 0) {{
    throw new TypeError(`${{path}} must be a non-negative integer`);
  }}
}}

function assertDateTime(value: unknown, path: string): asserts value is string {{
  assertMinString(value, 1, path);
  if (Number.isNaN(Date.parse(value))) {{
    throw new TypeError(`${{path}} must be an RFC3339 date-time string`);
  }}
}}

function assertStringArray(value: unknown, path: string, pattern?: RegExp): asserts value is readonly string[] {{
  if (!Array.isArray(value)) {{
    throw new TypeError(`${{path}} must be an array`);
  }}
  const seen = new Set<string>();
  for (const [index, item] of value.entries()) {{
    if (typeof item !== "string") {{
      throw new TypeError(`${{path}}[${{index}}] must be a string`);
    }}
    if (pattern !== undefined && !pattern.test(item)) {{
      throw new TypeError(`${{path}}[${{index}}] does not match required pattern`);
    }}
    if (seen.has(item)) {{
      throw new TypeError(`${{path}} must contain unique values`);
    }}
    seen.add(item);
  }}
}}
'''


def render_typescript_c4_smoke(c4_schema_sha256: str) -> str:
    return f'''// {HEADER}

import assert from "node:assert/strict";

import {{
  ArtifactRecord,
  C4_SCHEMA_SHA256,
  CANON_VERSION,
  assertArtifactRecord,
  hashBlob,
}} from "../src/c4.js";

const emptyHash = "blake3:af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262";
const vectorHash = "blake3:7e2fc64a9cc052211dfe7f54f2432c35588950f43d92bb08c87bbd182823d8d1";

const example: ArtifactRecord = {{
  artifact_ref: "c4://artifact/example",
  kind: "dataset",
  content_hash: emptyHash,
  hash_algorithm: "BLAKE3",
  size_bytes: 0,
  created_at: "2026-01-01T00:00:00Z",
  producer: {{
    subsystem: "S8",
    version: "1.0.0",
  }},
  lineage: {{
    input_refs: [],
    code_ref: "git:project-argus@example",
    environment_digest: "oci:sha256-example",
    seeds: [],
  }},
}};

assert.equal(C4_SCHEMA_SHA256, "{c4_schema_sha256}");
assert.equal(hashBlob(new Uint8Array()).content_hash, emptyHash);
assert.equal(hashBlob(new TextEncoder().encode("argus-s8-binding-vector")).content_hash, vectorHash);
assert.equal(hashBlob(new TextEncoder().encode("argus-s8-binding-vector")).size_bytes, 23);
assert.equal(hashBlob(new Uint8Array()).canon_version, CANON_VERSION);
assert.doesNotThrow(() => assertArtifactRecord(example));

assert.throws(
  () => assertArtifactRecord({{
    ...example,
    lineage: {{
      input_refs: [],
      code_ref: "git:project-argus@example",
      seeds: [],
    }},
  }}),
  /environment_digest/,
);

assert.throws(
  () => assertArtifactRecord({{
    ...example,
    claim_tier: "novel-needs-human",
  }}),
  /validation_report_ref/,
);
'''


def rust_array(values: list[str]) -> str:
    return "&[" + ", ".join(json.dumps(value) for value in values) + "]"


def render_rust_manifest() -> str:
    return "\n".join(
        [
            "[package]",
            'name = "argus-contracts"',
            'version = "0.0.0"',
            'edition = "2021"',
            'publish = false',
            "",
            "[lib]",
            'path = "src/lib.rs"',
            "",
            "[dependencies]",
            'blake3 = "1"',
            'hmac = "0.13"',
            'postgres = { version = "0.19", features = ["with-serde_json-1"] }',
            'serde = { version = "1", features = ["derive"] }',
            'serde_json = "1"',
            'sha2 = "0.11"',
            "",
        ]
    )


def render_rust_lib(items: list[dict]) -> str:
    rows = []
    for item in items:
        rows.append(
            "    Contract { "
            f'id: "{item["id"]}", '
            f'name: "{item["name"]}", '
            f'owner: "{item["owner"]}", '
            f'version: "{item["version"]}", '
            f'schema: "{item["schema"]}", '
            f'schema_sha256: "{item["schema_sha256"]}", '
            f"consumers: {rust_array(item['consumers'])} "
            "},"
        )
    return "\n".join(
        [
            f"// {HEADER}",
            "",
            "pub mod c4;",
            "pub mod hash;",
            "pub mod ledger;",
            "",
            "pub use c4::{ArtifactRecord, ClaimTier, Lineage, Producer, RetentionPolicy, C4_SCHEMA_SHA256};",
            "pub use hash::{hash_blob, hash_blob_stream, hash_bytes, BlobHasher, HashBlob, HashBlobError, BLAKE3_PREFIX, CANON_VERSION};",
            "pub use ledger::{ArtifactRecordDraft, CheckpointSigner, MerkleCheckpoint, PostgresLedgerWriter};",
            "",
            "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
            "pub struct Contract {",
            "    pub id: &'static str,",
            "    pub name: &'static str,",
            "    pub owner: &'static str,",
            "    pub version: &'static str,",
            "    pub schema: &'static str,",
            "    pub schema_sha256: &'static str,",
            "    pub consumers: &'static [&'static str],",
            "}",
            "",
            "pub const CONTRACTS: &[Contract] = &[",
            "\n".join(rows),
            "];",
            "",
            "pub fn contract_by_id(id: &str) -> Option<&'static Contract> {",
            "    CONTRACTS.iter().find(|contract| contract.id == id)",
            "}",
            "",
        ]
    )


def render_rust_c4(c4_schema_sha256: str) -> str:
    return f'''// {HEADER}

use serde::{{Deserialize, Serialize}};

pub const C4_SCHEMA_SHA256: &str = "{c4_schema_sha256}";

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ClaimTier {{
    RanToy,
    RecapitulatedKnown,
    NovelNeedsHuman,
}}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Producer {{
    pub subsystem: String,
    pub version: String,
}}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Lineage {{
    pub input_refs: Vec<String>,
    pub code_ref: String,
    pub environment_digest: String,
    pub seeds: Vec<String>,
}}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RetentionPolicy {{
    #[serde(rename = "class", skip_serializing_if = "Option::is_none")]
    pub class_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub retain_until: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hold_id: Option<String>,
}}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ArtifactRecord {{
    pub artifact_ref: String,
    pub kind: String,
    pub content_hash: String,
    pub hash_algorithm: String,
    pub size_bytes: u64,
    pub created_at: String,
    pub producer: Producer,
    pub lineage: Lineage,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub claim_tier: Option<ClaimTier>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub validation_report_ref: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub schema_ref: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub retention: Option<RetentionPolicy>,
}}

impl ArtifactRecord {{
    pub fn validate_promoted_tier(&self) -> Result<(), &'static str> {{
        if matches!(
            self.claim_tier,
            Some(ClaimTier::RecapitulatedKnown | ClaimTier::NovelNeedsHuman)
        ) && self.validation_report_ref.is_none()
        {{
            return Err("promoted claim_tier requires validation_report_ref");
        }}
        Ok(())
    }}
}}

#[cfg(test)]
mod tests {{
    use super::*;

    fn example_record() -> ArtifactRecord {{
        ArtifactRecord {{
            artifact_ref: "c4://artifact/example".to_string(),
            kind: "dataset".to_string(),
            content_hash: "blake3:af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262".to_string(),
            hash_algorithm: "BLAKE3".to_string(),
            size_bytes: 0,
            created_at: "2026-01-01T00:00:00Z".to_string(),
            producer: Producer {{
                subsystem: "S8".to_string(),
                version: "1.0.0".to_string(),
            }},
            lineage: Lineage {{
                input_refs: Vec::new(),
                code_ref: "git:project-argus@example".to_string(),
                environment_digest: "oci:sha256-example".to_string(),
                seeds: Vec::new(),
            }},
            claim_tier: None,
            validation_report_ref: None,
            schema_ref: None,
            retention: None,
        }}
    }}

    #[test]
    fn c4_schema_digest_is_generated() {{
        assert!(C4_SCHEMA_SHA256.starts_with("sha256:"));
    }}

    #[test]
    fn promoted_tier_requires_validation_report_ref() {{
        let mut record = example_record();
        assert_eq!(record.validate_promoted_tier(), Ok(()));

        record.claim_tier = Some(ClaimTier::NovelNeedsHuman);
        assert_eq!(
            record.validate_promoted_tier(),
            Err("promoted claim_tier requires validation_report_ref")
        );

        record.validation_report_ref = Some("c4://report/example".to_string());
        assert_eq!(record.validate_promoted_tier(), Ok(()));
    }}

    #[test]
    fn serde_round_trips_c4_artifact_record() {{
        let record = example_record();
        let json = serde_json::to_string(&record).expect("serialize record");
        let decoded: ArtifactRecord = serde_json::from_str(&json).expect("deserialize record");

        assert_eq!(decoded, record);
    }}
}}
'''


def generated_files() -> dict[Path, str]:
    items = contracts()
    c4 = next(item for item in items if item["id"] == "C4")
    return {
        PYTHON_CONTRACTS: render_python_contracts(items),
        PYTHON_C4: render_python_c4(c4["schema_sha256"]),
        PYTHON_INIT: render_python_init(),
        TYPESCRIPT_PACKAGE: render_typescript_package(),
        TYPESCRIPT_CONTRACTS: render_typescript_contracts(items),
        TYPESCRIPT_C4: render_typescript_c4(c4["schema_sha256"]),
        TYPESCRIPT_TSCONFIG: render_typescript_tsconfig(),
        TYPESCRIPT_C4_SMOKE: render_typescript_c4_smoke(c4["schema_sha256"]),
        RUST_MANIFEST: render_rust_manifest(),
        RUST_LIB: render_rust_lib(items),
        RUST_C4: render_rust_c4(c4["schema_sha256"]),
    }


def write_files(files: dict[Path, str]) -> None:
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def check_files(files: dict[Path, str]) -> int:
    drifted: list[str] = []
    missing: list[str] = []
    for path, expected in files.items():
        if not path.exists():
            missing.append(str(path.relative_to(ROOT)))
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            drifted.append(str(path.relative_to(ROOT)))

    if missing or drifted:
        if missing:
            print("Missing generated bindings:", ", ".join(missing), file=sys.stderr)
        if drifted:
            print("Generated bindings are out of date:", ", ".join(drifted), file=sys.stderr)
        print("Run: python3 scripts/generate_bindings.py --write", file=sys.stderr)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write generated bindings")
    mode.add_argument("--check", action="store_true", help="check generated bindings for drift")
    args = parser.parse_args()

    files = generated_files()
    if args.write:
        write_files(files)
        return 0
    return check_files(files)


if __name__ == "__main__":
    sys.exit(main())
