// Generated by scripts/generate_bindings.py; do not edit.

import { createHmac, type BinaryLike } from "node:crypto";

export const C3_SIGNATURE_ALGORITHM = "hmac-sha256";
export const C3_SIGNATURE_PREFIX = "hmac-sha256:";

export interface VerifierKey {
  key_id: string;
  secret: Uint8Array | string;
  revoked?: boolean;
}

export interface C3SignatureVerification {
  valid: boolean;
  reason?: string;
  error_code?: string;
  key_id?: string;
  claim_tier?: string;
  aggregate_passed?: boolean;
}

export interface VerifierTrustStore {
  getKey(keyId: string): VerifierKey | undefined;
  verifySignatureValue?(args: {
    key_id: string;
    report_with_empty_signature: Record<string, unknown>;
    signature_value: string;
  }): string | undefined;
}

export class InMemoryVerifierTrustStore implements VerifierTrustStore {
  private readonly keys = new Map<string, VerifierKey>();

  registerKey(keyId: string, secret: Uint8Array | string): void {
    this.keys.set(keyId, { key_id: keyId, secret });
  }

  revokeKey(keyId: string): void {
    const key = this.keys.get(keyId);
    if (key === undefined) {
      throw new Error(`unknown verifier key: ${keyId}`);
    }
    this.keys.set(keyId, { ...key, revoked: true });
  }

  getKey(keyId: string): VerifierKey | undefined {
    return this.keys.get(keyId);
  }
}

const errorCodes: Record<string, string> = {
  signature_missing: "UNSIGNED",
  algorithm_unsupported: "ALGORITHM_UNSUPPORTED",
  key_missing: "KEY_MISSING",
  unknown_key: "UNKNOWN_KEY",
  revoked_key: "REVOKED_KEY",
  signature_value_missing: "SIGNATURE_VALUE_MISSING",
  signature_invalid: "SIGNATURE_INVALID",
};

export function signReport(
  report: Record<string, unknown>,
  options: { keyId: string; secret: Uint8Array | string },
): Record<string, unknown> {
  const signed = cloneJsonObject(report);
  signed.signature = {
    algorithm: C3_SIGNATURE_ALGORITHM,
    key_id: options.keyId,
    value: "",
  };
  (signed.signature as Record<string, unknown>).value = signatureValue(signed, options.secret);
  return signed;
}

export function verifyReport(
  report: Record<string, unknown>,
  trustStore: VerifierTrustStore,
): C3SignatureVerification {
  const signature = report.signature;
  if (!isRecord(signature)) {
    return invalid("signature_missing");
  }
  const algorithm = signature.algorithm;
  const keyId = signature.key_id;
  const value = signature.value;
  if (algorithm !== C3_SIGNATURE_ALGORITHM) {
    return invalid("algorithm_unsupported", typeof keyId === "string" ? keyId : undefined);
  }
  if (typeof keyId !== "string") {
    return invalid("key_missing");
  }
  const key = trustStore.getKey(keyId);
  if (key === undefined) {
    return invalid("unknown_key", keyId);
  }
  if (key.revoked === true) {
    return invalid("revoked_key", keyId);
  }
  if (typeof value !== "string") {
    return invalid("signature_value_missing", keyId);
  }

  const unsigned = cloneJsonObject(report);
  unsigned.signature = {
    algorithm,
    key_id: keyId,
    value: "",
  };
  const delegatedReason = trustStore.verifySignatureValue?.({
    key_id: keyId,
    report_with_empty_signature: unsigned,
    signature_value: value,
  });
  if (delegatedReason !== undefined) {
    return invalid(delegatedReason, keyId);
  }
  if (trustStore.verifySignatureValue === undefined && !constantTimeStringEqual(value, signatureValue(unsigned, key.secret))) {
    return invalid("signature_invalid", keyId);
  }

  return {
    valid: true,
    key_id: keyId,
    claim_tier: typeof report.claim_tier === "string" ? report.claim_tier : undefined,
    aggregate_passed: aggregatePassed(report),
  };
}

function invalid(reason: string, keyId?: string): C3SignatureVerification {
  return {
    valid: false,
    reason,
    error_code: errorCodes[reason] ?? reason.toUpperCase(),
    key_id: keyId,
  };
}

function signatureValue(reportWithEmptySignature: Record<string, unknown>, secret: Uint8Array | string): string {
  const digest = createHmac("sha256", secretBytes(secret) as unknown as BinaryLike)
    .update(canonicalJson(reportWithEmptySignature), "utf8")
    .digest("hex");
  return `${C3_SIGNATURE_PREFIX}${digest}`;
}

function aggregatePassed(report: Record<string, unknown>): boolean | undefined {
  const aggregate = report.aggregate;
  if (!isRecord(aggregate)) {
    return undefined;
  }
  return typeof aggregate.passed === "boolean" ? aggregate.passed : undefined;
}

function canonicalJson(value: unknown): string {
  if (value === null) {
    return "null";
  }
  if (typeof value === "string") {
    return JSON.stringify(value);
  }
  if (typeof value === "number") {
    if (!Number.isFinite(value)) {
      throw new TypeError("canonical JSON rejects non-finite numbers");
    }
    return JSON.stringify(value);
  }
  if (typeof value === "boolean") {
    return value ? "true" : "false";
  }
  if (Array.isArray(value)) {
    return `[${value.map((item) => canonicalJson(item)).join(",")}]`;
  }
  if (isRecord(value)) {
    return `{${Object.keys(value)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`)
      .join(",")}}`;
  }
  throw new TypeError("canonical JSON only accepts JSON-compatible values");
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function cloneJsonObject(value: Record<string, unknown>): Record<string, unknown> {
  return JSON.parse(JSON.stringify(value)) as Record<string, unknown>;
}

function secretBytes(secret: Uint8Array | string): Uint8Array {
  return typeof secret === "string" ? new TextEncoder().encode(secret) : secret;
}

function constantTimeStringEqual(left: string, right: string): boolean {
  const leftBytes = new TextEncoder().encode(left);
  const rightBytes = new TextEncoder().encode(right);
  if (leftBytes.length !== rightBytes.length) {
    return false;
  }
  let diff = 0;
  for (let index = 0; index < leftBytes.length; index += 1) {
    diff |= leftBytes[index] ^ rightBytes[index];
  }
  return diff === 0;
}
