// Generated by scripts/generate_bindings.py; do not edit.

export const C1_SCHEMA_SHA256 = "sha256:bec647eec1f70625af766a1dd67f6bf81990d80d1b414b4c74f4254ca62ff7ab";

export type ArtifactRef = `c4://${string}`;
export type HashRef = `${"blake3" | "c4"}:${string}`;
export type LifecycleState =
  | "REGISTERED"
  | "ACCEPTED"
  | "PLANNING"
  | "BUILDING"
  | "VALIDATING"
  | "REPORTED"
  | "FAILED"
  | "REJECTED"
  | "CANCELLED"
  | "QUARANTINED";
export type LifecycleMethod =
  | "register"
  | "accept"
  | "refuse"
  | "plan"
  | "build"
  | "validate"
  | "report"
  | "heartbeat"
  | "cancel"
  | "fail"
  | "quarantine";
export type AcceptanceReason =
  | "OUT_OF_SCOPE"
  | "MISSING_ADAPTER"
  | "BUDGET_TOO_SMALL"
  | "NO_VERIFIER"
  | "VERSION_UNSUPPORTED"
  | "POLICY";

export interface CostEstimate {
  compute_units?: number;
  gpu_seconds?: number;
  model_tokens?: number;
  cost_usd: number;
}

export interface SubagentEnvelope {
  contract_version: string;
  method: LifecycleMethod;
  job_id: string;
  trace_id: string;
  state: LifecycleState;
  idempotency_key: string;
  capability_descriptor_ref?: ArtifactRef;
  job_envelope_ref?: ArtifactRef;
  payload?: Record<string, unknown>;
}

export interface Acceptance {
  job_id: string;
  accepted: boolean;
  reason?: AcceptanceReason | null;
  state: "ACCEPTED" | "REJECTED";
  estimated_cost?: CostEstimate;
  plan_eta_seconds?: number;
  idempotency_key: string;
}

const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const c4RefPattern = /^c4:\/\/[A-Za-z0-9._:/-]+$/;
const contractVersionPattern = /^1\.\d+\.\d+$/;
const lifecycleMethods = [
  "register",
  "accept",
  "refuse",
  "plan",
  "build",
  "validate",
  "report",
  "heartbeat",
  "cancel",
  "fail",
  "quarantine",
] as const;
const lifecycleStates = [
  "REGISTERED",
  "ACCEPTED",
  "PLANNING",
  "BUILDING",
  "VALIDATING",
  "REPORTED",
  "FAILED",
  "REJECTED",
  "CANCELLED",
  "QUARANTINED",
] as const;
const acceptanceReasons = [
  "OUT_OF_SCOPE",
  "MISSING_ADAPTER",
  "BUDGET_TOO_SMALL",
  "NO_VERIFIER",
  "VERSION_UNSUPPORTED",
  "POLICY",
] as const;

export function assertSubagentEnvelope(payload: unknown): asserts payload is SubagentEnvelope {
  const record = assertRecord(payload, "subagent_envelope");
  assertKeys(record, [
    "contract_version",
    "method",
    "job_id",
    "trace_id",
    "state",
    "idempotency_key",
  ], [
    "contract_version",
    "method",
    "job_id",
    "trace_id",
    "state",
    "idempotency_key",
    "capability_descriptor_ref",
    "job_envelope_ref",
    "payload",
  ], "subagent_envelope");
  assertPattern(record.contract_version, contractVersionPattern, "subagent_envelope.contract_version");
  assertOneOf(record.method, lifecycleMethods, "subagent_envelope.method");
  assertPattern(record.job_id, uuidPattern, "subagent_envelope.job_id");
  assertMinString(record.trace_id, 1, "subagent_envelope.trace_id");
  assertOneOf(record.state, lifecycleStates, "subagent_envelope.state");
  assertMinString(record.idempotency_key, 1, "subagent_envelope.idempotency_key");
  if (record.capability_descriptor_ref !== undefined) {
    assertPattern(record.capability_descriptor_ref, c4RefPattern, "subagent_envelope.capability_descriptor_ref");
  }
  if (record.job_envelope_ref !== undefined) {
    assertPattern(record.job_envelope_ref, c4RefPattern, "subagent_envelope.job_envelope_ref");
  }
  if (record.payload !== undefined) {
    assertRecord(record.payload, "subagent_envelope.payload");
  }
}

export function assertAcceptance(payload: unknown): asserts payload is Acceptance {
  const record = assertRecord(payload, "acceptance");
  assertKeys(record, [
    "job_id",
    "accepted",
    "state",
    "idempotency_key",
  ], [
    "job_id",
    "accepted",
    "reason",
    "state",
    "estimated_cost",
    "plan_eta_seconds",
    "idempotency_key",
  ], "acceptance");
  assertPattern(record.job_id, uuidPattern, "acceptance.job_id");
  assertBoolean(record.accepted, "acceptance.accepted");
  assertOneOf(record.state, ["ACCEPTED", "REJECTED"] as const, "acceptance.state");
  assertMinString(record.idempotency_key, 1, "acceptance.idempotency_key");
  if (record.reason !== undefined && record.reason !== null) {
    assertOneOf(record.reason, acceptanceReasons, "acceptance.reason");
  }
  if (record.estimated_cost !== undefined) {
    assertCostEstimate(record.estimated_cost, "acceptance.estimated_cost");
  }
  if (record.plan_eta_seconds !== undefined) {
    assertNonNegativeInteger(record.plan_eta_seconds, "acceptance.plan_eta_seconds");
  }
  if (record.accepted) {
    if (record.state !== "ACCEPTED" || (record.reason !== undefined && record.reason !== null)) {
      throw new TypeError("accepted Acceptance must have state ACCEPTED and null/absent reason");
    }
  } else if (record.state !== "REJECTED" || record.reason === undefined || record.reason === null) {
    throw new TypeError("refused Acceptance must have state REJECTED and a reason");
  }
}

function assertCostEstimate(value: unknown, path: string): void {
  const record = assertRecord(value, path);
  assertKeys(record, ["cost_usd"], ["compute_units", "gpu_seconds", "model_tokens", "cost_usd"], path);
  for (const key of ["compute_units", "gpu_seconds", "model_tokens", "cost_usd"]) {
    if (record[key] !== undefined) {
      assertNonNegativeNumber(record[key], path + "." + key);
    }
  }
}

function assertRecord(value: unknown, path: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new TypeError(path + " must be an object");
  }
  return value as Record<string, unknown>;
}

function assertKeys(record: Record<string, unknown>, required: readonly string[], allowed: readonly string[], path: string): void {
  const allowedKeys = new Set(allowed);
  for (const key of Object.keys(record)) {
    if (!allowedKeys.has(key)) {
      throw new TypeError(path + "." + key + " is not allowed");
    }
  }
  for (const key of required) {
    if (!(key in record)) {
      throw new TypeError(path + "." + key + " is required");
    }
  }
}

function assertPattern(value: unknown, pattern: RegExp, path: string): asserts value is string {
  assertMinString(value, 0, path);
  if (!pattern.test(value)) {
    throw new TypeError(path + " does not match required pattern");
  }
}

function assertMinString(value: unknown, minLength: number, path: string): asserts value is string {
  if (typeof value !== "string" || value.length < minLength) {
    throw new TypeError(path + " must be a string with length >= " + minLength);
  }
}

function assertBoolean(value: unknown, path: string): asserts value is boolean {
  if (typeof value !== "boolean") {
    throw new TypeError(path + " must be a boolean");
  }
}

function assertOneOf<T extends string>(value: unknown, allowed: readonly T[], path: string): asserts value is T {
  if (typeof value !== "string" || !allowed.includes(value as T)) {
    throw new TypeError(path + " must be one of " + allowed.join(", "));
  }
}

function assertNonNegativeNumber(value: unknown, path: string): asserts value is number {
  if (typeof value !== "number" || !Number.isFinite(value) || value < 0) {
    throw new TypeError(path + " must be a non-negative finite number");
  }
}

function assertNonNegativeInteger(value: unknown, path: string): asserts value is number {
  if (!Number.isSafeInteger(value) || (value as number) < 0) {
    throw new TypeError(path + " must be a non-negative integer");
  }
}
