// Generated by scripts/generate_bindings.py; do not edit.

import { blake3 } from "@noble/hashes/blake3.js";
import { bytesToHex } from "@noble/hashes/utils.js";

export const C4_SCHEMA_SHA256 = "sha256:32d5caf1f5f57b4c1da2eb7dc81e31f7423c834f6945e3839ffc6356fc4d35de";
export const BLAKE3_PREFIX = "blake3:";
export const CANON_VERSION = "argus-jcs-v1";

export type ArtifactRef = `c4://${string}`;
export type HashRef = `blake3:${string}`;
export type ClaimTier = "ran-toy" | "recapitulated-known" | "novel-needs-human";

export interface Producer {
  subsystem: string;
  version: string;
}

export interface Lineage {
  input_refs: readonly ArtifactRef[];
  code_ref: string;
  environment_digest: string;
  seeds: readonly string[];
}

export interface RetentionPolicy {
  class?: "write_once" | "scratch" | "hold";
  retain_until?: string;
  hold_id?: string;
}

export interface ArtifactRecord {
  artifact_ref: ArtifactRef;
  kind: string;
  content_hash: HashRef;
  hash_algorithm: "BLAKE3";
  size_bytes: number;
  created_at: string;
  producer: Producer;
  lineage: Lineage;
  claim_tier?: ClaimTier;
  validation_report_ref?: ArtifactRef;
  schema_ref?: string;
  retention?: RetentionPolicy;
}

export interface HashBlob {
  content_hash: HashRef;
  size_bytes: number;
  canon_version: typeof CANON_VERSION;
}

const artifactRefPattern = /^c4:\/\/[A-Za-z0-9._:/-]+$/;
const hashRefPattern = /^blake3:[a-f0-9]{64}$/;
const subsystemPattern = /^S\d+$/;
const versionPattern = /^\d+\.\d+\.\d+$/;

export function hashBlob(payload: Uint8Array): HashBlob {
  return {
    content_hash: `${BLAKE3_PREFIX}${bytesToHex(blake3(payload))}` as HashRef,
    size_bytes: payload.byteLength,
    canon_version: CANON_VERSION,
  };
}

export function assertArtifactRecord(payload: unknown): asserts payload is ArtifactRecord {
  const record = assertRecord(payload, "artifact");
  assertKeys(record, [
    "artifact_ref",
    "kind",
    "content_hash",
    "hash_algorithm",
    "size_bytes",
    "created_at",
    "producer",
    "lineage",
    "claim_tier",
    "validation_report_ref",
    "schema_ref",
    "retention",
  ], "artifact");
  assertPattern(record.artifact_ref, artifactRefPattern, "artifact.artifact_ref");
  assertMinString(record.kind, 1, "artifact.kind");
  assertPattern(record.content_hash, hashRefPattern, "artifact.content_hash");
  assertLiteral(record.hash_algorithm, "BLAKE3", "artifact.hash_algorithm");
  assertNonNegativeInteger(record.size_bytes, "artifact.size_bytes");
  assertDateTime(record.created_at, "artifact.created_at");
  assertProducer(record.producer, "artifact.producer");
  assertLineage(record.lineage, "artifact.lineage");

  if (record.claim_tier !== undefined) {
    assertOneOf(record.claim_tier, ["ran-toy", "recapitulated-known", "novel-needs-human"], "artifact.claim_tier");
  }
  if (record.validation_report_ref !== undefined) {
    assertPattern(record.validation_report_ref, artifactRefPattern, "artifact.validation_report_ref");
  }
  if (record.schema_ref !== undefined) {
    assertMinString(record.schema_ref, 0, "artifact.schema_ref");
  }
  if (record.retention !== undefined) {
    assertRetention(record.retention, "artifact.retention");
  }
  if (
    (record.claim_tier === "recapitulated-known" || record.claim_tier === "novel-needs-human") &&
    record.validation_report_ref === undefined
  ) {
    throw new TypeError("artifact.validation_report_ref is required for promoted claim_tier");
  }
}

function assertProducer(value: unknown, path: string): asserts value is Producer {
  const record = assertRecord(value, path);
  assertKeys(record, ["subsystem", "version"], path);
  assertPattern(record.subsystem, subsystemPattern, `${path}.subsystem`);
  assertPattern(record.version, versionPattern, `${path}.version`);
}

function assertLineage(value: unknown, path: string): asserts value is Lineage {
  const record = assertRecord(value, path);
  assertKeys(record, ["input_refs", "code_ref", "environment_digest", "seeds"], path);
  assertStringArray(record.input_refs, `${path}.input_refs`, artifactRefPattern);
  assertMinString(record.code_ref, 1, `${path}.code_ref`);
  assertMinString(record.environment_digest, 1, `${path}.environment_digest`);
  assertStringArray(record.seeds, `${path}.seeds`);
}

function assertRetention(value: unknown, path: string): asserts value is RetentionPolicy {
  const record = assertRecord(value, path);
  assertKeys(record, ["class", "retain_until", "hold_id"], path);
  if (record.class !== undefined) {
    assertOneOf(record.class, ["write_once", "scratch", "hold"], `${path}.class`);
  }
  if (record.retain_until !== undefined) {
    assertDateTime(record.retain_until, `${path}.retain_until`);
  }
  if (record.hold_id !== undefined) {
    assertMinString(record.hold_id, 1, `${path}.hold_id`);
  }
}

function assertRecord(value: unknown, path: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new TypeError(`${path} must be an object`);
  }
  return value as Record<string, unknown>;
}

function assertKeys(record: Record<string, unknown>, allowedKeys: readonly string[], path: string): void {
  const allowed = new Set(allowedKeys);
  for (const key of Object.keys(record)) {
    if (!allowed.has(key)) {
      throw new TypeError(`${path}.${key} is not allowed`);
    }
  }
  for (const key of allowedKeys) {
    if (!(key in record) && requiredKeys(path).has(key)) {
      throw new TypeError(`${path}.${key} is required`);
    }
  }
}

function requiredKeys(path: string): Set<string> {
  if (path === "artifact") {
    return new Set(["artifact_ref", "kind", "content_hash", "hash_algorithm", "size_bytes", "created_at", "producer", "lineage"]);
  }
  if (path.endsWith(".producer")) {
    return new Set(["subsystem", "version"]);
  }
  if (path.endsWith(".lineage")) {
    return new Set(["input_refs", "code_ref", "environment_digest", "seeds"]);
  }
  return new Set();
}

function assertPattern(value: unknown, pattern: RegExp, path: string): asserts value is string {
  assertMinString(value, 0, path);
  if (!pattern.test(value)) {
    throw new TypeError(`${path} does not match required pattern`);
  }
}

function assertMinString(value: unknown, minLength: number, path: string): asserts value is string {
  if (typeof value !== "string" || value.length < minLength) {
    throw new TypeError(`${path} must be a string with length >= ${minLength}`);
  }
}

function assertLiteral<T extends string>(value: unknown, expected: T, path: string): asserts value is T {
  if (value !== expected) {
    throw new TypeError(`${path} must equal ${expected}`);
  }
}

function assertOneOf<T extends string>(value: unknown, allowed: readonly T[], path: string): asserts value is T {
  if (typeof value !== "string" || !allowed.includes(value as T)) {
    throw new TypeError(`${path} must be one of ${allowed.join(", ")}`);
  }
}

function assertNonNegativeInteger(value: unknown, path: string): asserts value is number {
  if (!Number.isSafeInteger(value) || (value as number) < 0) {
    throw new TypeError(`${path} must be a non-negative integer`);
  }
}

function assertDateTime(value: unknown, path: string): asserts value is string {
  assertMinString(value, 1, path);
  if (Number.isNaN(Date.parse(value))) {
    throw new TypeError(`${path} must be an RFC3339 date-time string`);
  }
}

function assertStringArray(value: unknown, path: string, pattern?: RegExp): asserts value is readonly string[] {
  if (!Array.isArray(value)) {
    throw new TypeError(`${path} must be an array`);
  }
  const seen = new Set<string>();
  for (const [index, item] of value.entries()) {
    if (typeof item !== "string") {
      throw new TypeError(`${path}[${index}] must be a string`);
    }
    if (pattern !== undefined && !pattern.test(item)) {
      throw new TypeError(`${path}[${index}] does not match required pattern`);
    }
    if (seen.has(item)) {
      throw new TypeError(`${path} must contain unique values`);
    }
    seen.add(item);
  }
}
