// Generated by scripts/generate_bindings.py; do not edit.

export type ContractId = "C1" | "C10" | "C2" | "C3" | "C4" | "C5" | "C6";

export interface Contract {
  id: ContractId;
  name: string;
  owner: string;
  version: string;
  schema: string;
  schema_sha256: string;
  consumers: readonly string[];
}

export const contracts = [
  {
    "id": "C1",
    "name": "Subagent Contract",
    "owner": "S1",
    "version": "1.0.0",
    "schema": "c1.subagent.schema.json",
    "consumers": [
      "S2",
      "S3",
      "S4",
      "S5",
      "S11",
      "S12"
    ],
    "schema_sha256": "sha256:70de039b4c9687e9ce83ed5dc0ff444c681dd068cf79b8c1d6138bfd9c4b56d5"
  },
  {
    "id": "C10",
    "name": "S10 Runtime Wire Models",
    "owner": "S10",
    "version": "4.0.0",
    "schema": "c10.s10-runtime.schema.json",
    "consumers": [
      "S1",
      "S2",
      "S3",
      "S4",
      "S5",
      "S6",
      "S7",
      "S8",
      "S9",
      "S11",
      "S12"
    ],
    "schema_sha256": "sha256:44d35c3706762b4b6d1aa7d83598d6dceacaa0e6ee14c940ef92b582f9353523"
  },
  {
    "id": "C2",
    "name": "Task Job Envelope",
    "owner": "S5",
    "version": "1.0.0",
    "schema": "c2.job-envelope.schema.json",
    "consumers": [
      "S1",
      "S2",
      "S3",
      "S4",
      "S7",
      "S9",
      "S10",
      "S11",
      "S12"
    ],
    "schema_sha256": "sha256:62695e9f6e4cda8ab9f9089d595f36ca3cf395e0f40100be35938a838b334360"
  },
  {
    "id": "C3",
    "name": "Verifier Interface and Validation Report",
    "owner": "S3",
    "version": "2.0.0",
    "schema": "c3.validation-report.schema.json",
    "consumers": [
      "S1",
      "S2",
      "S4",
      "S5",
      "S7",
      "S8",
      "S9",
      "S11",
      "S12"
    ],
    "schema_sha256": "sha256:ffcf9e88f2d4f2d481cca9cd4e4abca740e6ee519c0b7f5aec1abccc70a88769"
  },
  {
    "id": "C4",
    "name": "Artifact and Provenance Record",
    "owner": "S8",
    "version": "1.0.0",
    "schema": "c4.artifact-record.schema.json",
    "consumers": [
      "S1",
      "S2",
      "S3",
      "S4",
      "S5",
      "S6",
      "S7",
      "S9",
      "S10",
      "S11",
      "S12"
    ],
    "schema_sha256": "sha256:32d5caf1f5f57b4c1da2eb7dc81e31f7423c834f6945e3839ffc6356fc4d35de"
  },
  {
    "id": "C5",
    "name": "Registry Capability Descriptor",
    "owner": "S6/S12",
    "version": "1.0.0",
    "schema": "c5.capability-descriptor.schema.json",
    "consumers": [
      "S1",
      "S2",
      "S3",
      "S4",
      "S5",
      "S7",
      "S9",
      "S10",
      "S11"
    ],
    "schema_sha256": "sha256:250713686bbebeb2ee5b146678a97bfabf9170b953a3368209f5cc40c2bef2c8"
  },
  {
    "id": "C6",
    "name": "Compute Adapter Tool Interface",
    "owner": "S7",
    "version": "1.0.0",
    "schema": "c6.compute-adapter.schema.json",
    "consumers": [
      "S1",
      "S2",
      "S3",
      "S5",
      "S6",
      "S10",
      "S11",
      "S12"
    ],
    "schema_sha256": "sha256:f8146179c942b7c4c7b984785c32b2cb2f896eed71207ea19fcf3424bdd8f102"
  }
] as const satisfies readonly Contract[];

export const contractById = {
  "C1": contracts[0],
  "C10": contracts[1],
  "C2": contracts[2],
  "C3": contracts[3],
  "C4": contracts[4],
  "C5": contracts[5],
  "C6": contracts[6],
} satisfies Record<ContractId, Contract>;
