// Generated by scripts/generate_bindings.py; do not edit.

export type ContractId = "C1" | "C2" | "C3" | "C4" | "C5" | "C6";

export interface Contract {
  id: ContractId;
  name: string;
  owner: string;
  version: string;
  schema: string;
  schema_sha256: string;
  consumers: readonly string[];
}

export const contracts = [
  {
    "id": "C1",
    "name": "Subagent Contract",
    "owner": "S1",
    "version": "1.0.0",
    "schema": "c1.subagent.schema.json",
    "consumers": [
      "S2",
      "S3",
      "S4",
      "S5",
      "S11",
      "S12"
    ],
    "schema_sha256": "sha256:bec647eec1f70625af766a1dd67f6bf81990d80d1b414b4c74f4254ca62ff7ab"
  },
  {
    "id": "C2",
    "name": "Task Job Envelope",
    "owner": "S5",
    "version": "1.0.0",
    "schema": "c2.job-envelope.schema.json",
    "consumers": [
      "S1",
      "S2",
      "S3",
      "S4",
      "S7",
      "S9",
      "S10",
      "S11",
      "S12"
    ],
    "schema_sha256": "sha256:62695e9f6e4cda8ab9f9089d595f36ca3cf395e0f40100be35938a838b334360"
  },
  {
    "id": "C3",
    "name": "Verifier Interface and Validation Report",
    "owner": "S3",
    "version": "1.1.0",
    "schema": "c3.validation-report.schema.json",
    "consumers": [
      "S1",
      "S2",
      "S4",
      "S5",
      "S7",
      "S8",
      "S9",
      "S11",
      "S12"
    ],
    "schema_sha256": "sha256:e0c8cd14a6bf287c75c5fb5999b425b76e020569ef47da4a0991043737bfd123"
  },
  {
    "id": "C4",
    "name": "Artifact and Provenance Record",
    "owner": "S8",
    "version": "1.0.0",
    "schema": "c4.artifact-record.schema.json",
    "consumers": [
      "S1",
      "S2",
      "S3",
      "S4",
      "S5",
      "S6",
      "S7",
      "S9",
      "S10",
      "S11",
      "S12"
    ],
    "schema_sha256": "sha256:0bda7896cbe41192da3a5d995414ed64cd3f00b78f7a162b808ac4f621c8d985"
  },
  {
    "id": "C5",
    "name": "Registry Capability Descriptor",
    "owner": "S6/S12",
    "version": "1.0.0",
    "schema": "c5.capability-descriptor.schema.json",
    "consumers": [
      "S1",
      "S2",
      "S3",
      "S4",
      "S5",
      "S7",
      "S9",
      "S10",
      "S11"
    ],
    "schema_sha256": "sha256:250713686bbebeb2ee5b146678a97bfabf9170b953a3368209f5cc40c2bef2c8"
  },
  {
    "id": "C6",
    "name": "Compute Adapter Tool Interface",
    "owner": "S7",
    "version": "1.0.0",
    "schema": "c6.compute-adapter.schema.json",
    "consumers": [
      "S1",
      "S2",
      "S3",
      "S5",
      "S6",
      "S10",
      "S11",
      "S12"
    ],
    "schema_sha256": "sha256:6291976b487382ae1652dcd6166d2252f6b1aa00234b89f373a83b67639d406c"
  }
] as const satisfies readonly Contract[];

export const contractById = Object.fromEntries(
  contracts.map((contract) => [contract.id, contract]),
) as Record<ContractId, Contract>;
