// Generated by scripts/generate_bindings.py; do not edit.

export const C10_SCHEMA_SHA256 = "sha256:44d35c3706762b4b6d1aa7d83598d6dceacaa0e6ee14c940ef92b582f9353523";

export type RuntimeClass = "auto" | "gvisor" | "firecracker" | "docker";
export type RiskClass = "standard" | "federated" | "high";
export type SandboxState =
  | "ADMITTED"
  | "RUNNING"
  | "SUCCEEDED"
  | "FAILED"
  | "TIMED_OUT"
  | "FROZEN"
  | "TERMINATED"
  | "QUARANTINED";

export interface BudgetCaps {
  max_compute_units: number;
  max_gpu_seconds: number;
  max_model_tokens: number;
  max_wallclock_s: number;
  max_cost_usd: number;
}

export interface BudgetUsage {
  compute_units: number;
  gpu_seconds: number;
  model_tokens: number;
  wallclock_s: number;
  cost_usd: number;
}

export interface EgressRule {
  host: string;
  port: number;
  proto: "https" | "grpc" | "tcp";
}

export interface ScopeGrant {
  allowed_adapters: readonly string[];
  allowed_datasets: readonly string[];
  egress_allowlist: readonly EgressRule[];
  broker_audiences: readonly string[];
  capabilities: readonly string[];
  producer_subsystems: readonly string[];
  sandbox_risk_class: RiskClass;
  disallowed_actions: readonly string[];
}

export interface BudgetToken {
  budget_id: string;
  job_id: string;
  root_request_id: string;
  budget_epoch: number;
  caps: BudgetCaps;
  risk_class: RiskClass;
  issued_at: number;
  expires_at: number;
  ttl_s: number;
  parent_budget_id: string | null;
  signer_key_id: string;
  signature: string;
}

export interface ScopeToken {
  scope_id: string;
  job_id: string;
  scopes: ScopeGrant;
  issued_at: number;
  expires_at: number;
  ttl_s: number;
  parent_scope_id: string | null;
  signer_key_id: string;
  signature: string;
}

export interface ResourceCeilings {
  cpu_m: number;
  mem_bytes: number;
  gpu_count: number;
  wallclock_s: number;
  max_cost_usd: number;
}

export interface PolicyBundle {
  bundle_version: string;
  egress_allowlist: readonly EgressRule[];
  resource_ceilings: ResourceCeilings;
  risk_to_runtime: Record<string, RuntimeClass>;
  seccomp_profile_hash: string;
  signer_key_id: string;
  signature: string;
}

export interface LaunchEnvelope {
  cpu_m: number;
  mem_bytes: number;
  gpu_count: number;
  wallclock_s: number;
  scratch_bytes: number;
  pids: number;
  estimated_cost_usd: number;
}

export interface LaunchRequest {
  job_id: string;
  subagent_id: string;
  trace_id: string;
  budget_token: BudgetToken;
  scope_token: ScopeToken;
  image: string;
  entrypoint: readonly string[];
  args: readonly string[];
  env: Record<string, string>;
  env_allowlist: readonly string[];
  requested_envelope: LaunchEnvelope;
  runtime_class_hint: RuntimeClass;
  policy_pin: string | null;
}

export interface PolicyVerdict {
  allowed: boolean;
  runtime_class: RuntimeClass | null;
  egress_acl: readonly EgressRule[];
  deny_reason: string | null;
}

export interface SandboxHandle {
  sandbox_id: string;
  job_id: string;
  runtime_class: RuntimeClass;
  budget_epoch: number;
  policy_bundle_version: string;
  state: SandboxState;
  launch_provenance_ref: string | null;
}

export interface SandboxPartialResult {
  reason: string;
  stdout: string;
  stderr: string;
  captured_after_freeze: boolean;
  freeze_succeeded: boolean;
  terminate_succeeded: boolean;
  stdout_bytes: number;
  stderr_bytes: number;
  log_capture_limit_bytes: number;
  logs_truncated: boolean;
  frozen_state: "FROZEN";
  terminated_state: "TERMINATED";
  capture_error: string | null;
}

export interface SandboxExecutionResult {
  handle: SandboxHandle;
  exit_code: number | null;
  stdout: string;
  stderr: string;
  timed_out: boolean;
  duration_s: number;
  budget_usage: BudgetUsage;
  partial_result: SandboxPartialResult | null;
}

export interface QuotaState {
  caps: BudgetCaps;
  reserved: BudgetUsage;
  actual: BudgetUsage;
  halted: boolean;
}

export interface AuditEvent {
  sequence: number;
  event_type: string;
  payload: Record<string, unknown>;
  previous_hash: string;
  event_hash: string;
}

export interface EgressDecision {
  allowed: boolean;
  reason: string;
}

export interface StoreBrokerHandle {
  handle_id: string;
  scope_id: string;
  expires_at: number;
}

export interface S8CheckpointSignature {
  sequence: number;
  root: string;
  signature: string;
  signer_key_id: string;
}

const hashRefPattern = /^blake3:[a-f0-9]{64}$/;
const signaturePattern = /^hmac-sha256:[a-f0-9]{64}$/;
const tokenSignaturePattern = /^(?:hmac-sha256:[a-f0-9]{64}|ed25519:[a-f0-9]{128})$/;
const artifactRefPattern = /^c4:\/\/[A-Za-z0-9._:/-]+$/;
const semverPattern = /^\d+\.\d+\.\d+$/;
const imagePattern = /^(?:[^\s@]+@)?sha256:[0-9a-f]{64}$/;
const envKeyPattern = /^[A-Z_][A-Z0-9_]*$/;
const subsystemPattern = /^S\d+$/;
const brokerAudiencePattern = /^(store|model|adapter:[A-Za-z0-9._:-]+)$/;
const capabilityPattern = /^[A-Za-z0-9._:-]+$/;
const runtimeClasses = ["auto", "gvisor", "firecracker", "docker"] as const;
const riskClasses = ["standard", "federated", "high"] as const;

export function assertBudgetToken(payload: unknown): asserts payload is BudgetToken {
  const record = assertRecord(payload, "budget_token");
  assertKeys(record, [
    "budget_id",
    "job_id",
    "root_request_id",
    "budget_epoch",
    "caps",
    "risk_class",
    "issued_at",
    "expires_at",
    "ttl_s",
    "parent_budget_id",
    "signer_key_id",
    "signature",
  ], "budget_token");
  assertMinString(record.budget_id, 1, "budget_token.budget_id");
  assertMinString(record.job_id, 1, "budget_token.job_id");
  assertMinString(record.root_request_id, 1, "budget_token.root_request_id");
  assertPositiveInteger(record.budget_epoch, "budget_token.budget_epoch");
  assertBudgetCaps(record.caps, "budget_token.caps");
  assertOneOf(record.risk_class, riskClasses, "budget_token.risk_class");
  assertNonNegativeInteger(record.issued_at, "budget_token.issued_at");
  assertNonNegativeInteger(record.expires_at, "budget_token.expires_at");
  assertPositiveInteger(record.ttl_s, "budget_token.ttl_s");
  assertStringOrNull(record.parent_budget_id, "budget_token.parent_budget_id");
  assertMinString(record.signer_key_id, 1, "budget_token.signer_key_id");
  assertPattern(record.signature, tokenSignaturePattern, "budget_token.signature");
}

export function assertScopeToken(payload: unknown): asserts payload is ScopeToken {
  const record = assertRecord(payload, "scope_token");
  assertKeys(record, [
    "scope_id",
    "job_id",
    "scopes",
    "issued_at",
    "expires_at",
    "ttl_s",
    "parent_scope_id",
    "signer_key_id",
    "signature",
  ], "scope_token");
  assertMinString(record.scope_id, 1, "scope_token.scope_id");
  assertMinString(record.job_id, 1, "scope_token.job_id");
  assertScopeGrant(record.scopes, "scope_token.scopes");
  assertNonNegativeInteger(record.issued_at, "scope_token.issued_at");
  assertNonNegativeInteger(record.expires_at, "scope_token.expires_at");
  assertPositiveInteger(record.ttl_s, "scope_token.ttl_s");
  assertStringOrNull(record.parent_scope_id, "scope_token.parent_scope_id");
  assertMinString(record.signer_key_id, 1, "scope_token.signer_key_id");
  assertPattern(record.signature, tokenSignaturePattern, "scope_token.signature");
}

export function assertPolicyBundle(payload: unknown): asserts payload is PolicyBundle {
  const record = assertRecord(payload, "policy_bundle");
  assertKeys(record, [
    "bundle_version",
    "egress_allowlist",
    "resource_ceilings",
    "risk_to_runtime",
    "seccomp_profile_hash",
    "signer_key_id",
    "signature",
  ], "policy_bundle");
  assertPattern(record.bundle_version, semverPattern, "policy_bundle.bundle_version");
  assertEgressRuleArray(record.egress_allowlist, "policy_bundle.egress_allowlist");
  assertResourceCeilings(record.resource_ceilings, "policy_bundle.resource_ceilings");
  assertRuntimeMapping(record.risk_to_runtime, "policy_bundle.risk_to_runtime");
  assertPattern(record.seccomp_profile_hash, hashRefPattern, "policy_bundle.seccomp_profile_hash");
  assertMinString(record.signer_key_id, 1, "policy_bundle.signer_key_id");
  assertPattern(record.signature, signaturePattern, "policy_bundle.signature");
}

export function assertLaunchRequest(payload: unknown): asserts payload is LaunchRequest {
  const record = assertRecord(payload, "launch_request");
  assertKeys(record, [
    "job_id",
    "subagent_id",
    "trace_id",
    "budget_token",
    "scope_token",
    "image",
    "entrypoint",
    "args",
    "env",
    "env_allowlist",
    "requested_envelope",
    "runtime_class_hint",
    "policy_pin",
  ], "launch_request");
  assertMinString(record.job_id, 1, "launch_request.job_id");
  assertMinString(record.subagent_id, 1, "launch_request.subagent_id");
  assertMinString(record.trace_id, 1, "launch_request.trace_id");
  assertBudgetToken(record.budget_token);
  assertScopeToken(record.scope_token);
  assertPattern(record.image, imagePattern, "launch_request.image");
  assertStringArray(record.entrypoint, "launch_request.entrypoint");
  assertStringArray(record.args, "launch_request.args");
  assertStringMap(record.env, "launch_request.env");
  assertStringArray(record.env_allowlist, "launch_request.env_allowlist", envKeyPattern);
  assertLaunchEnvelope(record.requested_envelope, "launch_request.requested_envelope");
  assertOneOf(record.runtime_class_hint, runtimeClasses, "launch_request.runtime_class_hint");
  assertStringOrNull(record.policy_pin, "launch_request.policy_pin");
}

function assertBudgetCaps(value: unknown, path: string): void {
  const record = assertRecord(value, path);
  assertKeys(record, ["max_compute_units", "max_gpu_seconds", "max_model_tokens", "max_wallclock_s", "max_cost_usd"], path);
  for (const key of ["max_compute_units", "max_gpu_seconds", "max_model_tokens", "max_wallclock_s", "max_cost_usd"]) {
    assertNonNegativeNumber(record[key], path + "." + key);
  }
}

function assertScopeGrant(value: unknown, path: string): void {
  const record = assertRecord(value, path);
  assertKeys(record, [
    "allowed_adapters",
    "allowed_datasets",
    "egress_allowlist",
    "broker_audiences",
    "capabilities",
    "producer_subsystems",
    "sandbox_risk_class",
    "disallowed_actions",
  ], path);
  assertStringArray(record.allowed_adapters, path + ".allowed_adapters");
  assertStringArray(record.allowed_datasets, path + ".allowed_datasets", artifactRefPattern);
  assertEgressRuleArray(record.egress_allowlist, path + ".egress_allowlist");
  assertStringArray(record.broker_audiences, path + ".broker_audiences", brokerAudiencePattern);
  assertStringArray(record.capabilities, path + ".capabilities", capabilityPattern);
  assertStringArray(record.producer_subsystems, path + ".producer_subsystems", subsystemPattern);
  assertOneOf(record.sandbox_risk_class, riskClasses, path + ".sandbox_risk_class");
  assertStringArray(record.disallowed_actions, path + ".disallowed_actions");
}

function assertResourceCeilings(value: unknown, path: string): void {
  const record = assertRecord(value, path);
  assertKeys(record, ["cpu_m", "mem_bytes", "gpu_count", "wallclock_s", "max_cost_usd"], path);
  assertPositiveInteger(record.cpu_m, path + ".cpu_m");
  assertPositiveInteger(record.mem_bytes, path + ".mem_bytes");
  assertNonNegativeInteger(record.gpu_count, path + ".gpu_count");
  assertPositiveInteger(record.wallclock_s, path + ".wallclock_s");
  assertNonNegativeNumber(record.max_cost_usd, path + ".max_cost_usd");
}

function assertRuntimeMapping(value: unknown, path: string): void {
  const record = assertRecord(value, path);
  if (Object.keys(record).length === 0) {
    throw new TypeError(path + " must not be empty");
  }
  for (const [key, runtimeClass] of Object.entries(record)) {
    assertMinString(key, 1, path + ".key");
    assertOneOf(runtimeClass, runtimeClasses, path + "." + key);
  }
}

function assertLaunchEnvelope(value: unknown, path: string): void {
  const record = assertRecord(value, path);
  assertKeys(record, ["cpu_m", "mem_bytes", "gpu_count", "wallclock_s", "scratch_bytes", "pids", "estimated_cost_usd"], path);
  assertPositiveInteger(record.cpu_m, path + ".cpu_m");
  assertPositiveInteger(record.mem_bytes, path + ".mem_bytes");
  assertNonNegativeInteger(record.gpu_count, path + ".gpu_count");
  assertPositiveInteger(record.wallclock_s, path + ".wallclock_s");
  assertNonNegativeInteger(record.scratch_bytes, path + ".scratch_bytes");
  assertPositiveInteger(record.pids, path + ".pids");
  assertNonNegativeNumber(record.estimated_cost_usd, path + ".estimated_cost_usd");
}

function assertEgressRuleArray(value: unknown, path: string): void {
  if (!Array.isArray(value)) {
    throw new TypeError(path + " must be an array");
  }
  const seen = new Set<string>();
  for (const [index, item] of value.entries()) {
    assertEgressRule(item, path + "[" + index + "]");
    const key = JSON.stringify(item);
    if (seen.has(key)) {
      throw new TypeError(path + " must contain unique values");
    }
    seen.add(key);
  }
}

function assertEgressRule(value: unknown, path: string): void {
  const record = assertRecord(value, path);
  assertKeys(record, ["host", "port", "proto"], path);
  assertMinString(record.host, 1, path + ".host");
  assertPositiveInteger(record.port, path + ".port");
  if ((record.port as number) > 65535) {
    throw new TypeError(path + ".port must be <= 65535");
  }
  assertOneOf(record.proto, ["https", "grpc", "tcp"] as const, path + ".proto");
}

function assertRecord(value: unknown, path: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new TypeError(path + " must be an object");
  }
  return value as Record<string, unknown>;
}

function assertKeys(record: Record<string, unknown>, required: readonly string[], path: string): void {
  const allowed = new Set(required);
  for (const key of Object.keys(record)) {
    if (!allowed.has(key)) {
      throw new TypeError(path + "." + key + " is not allowed");
    }
  }
  for (const key of required) {
    if (!(key in record)) {
      throw new TypeError(path + "." + key + " is required");
    }
  }
}

function assertMinString(value: unknown, minLength: number, path: string): asserts value is string {
  if (typeof value !== "string" || value.length < minLength) {
    throw new TypeError(path + " must be a string with length >= " + minLength);
  }
}

function assertStringOrNull(value: unknown, path: string): void {
  if (value !== null) {
    assertMinString(value, 1, path);
  }
}

function assertPattern(value: unknown, pattern: RegExp, path: string): asserts value is string {
  assertMinString(value, 0, path);
  if (!pattern.test(value)) {
    throw new TypeError(path + " does not match required pattern");
  }
}

function assertOneOf<T extends string>(value: unknown, allowed: readonly T[], path: string): asserts value is T {
  if (typeof value !== "string" || !allowed.includes(value as T)) {
    throw new TypeError(path + " must be one of " + allowed.join(", "));
  }
}

function assertNonNegativeNumber(value: unknown, path: string): asserts value is number {
  if (typeof value !== "number" || !Number.isFinite(value) || value < 0) {
    throw new TypeError(path + " must be a non-negative finite number");
  }
}

function assertNonNegativeInteger(value: unknown, path: string): asserts value is number {
  if (!Number.isSafeInteger(value) || (value as number) < 0) {
    throw new TypeError(path + " must be a non-negative integer");
  }
}

function assertPositiveInteger(value: unknown, path: string): asserts value is number {
  if (!Number.isSafeInteger(value) || (value as number) < 1) {
    throw new TypeError(path + " must be a positive integer");
  }
}

function assertStringArray(value: unknown, path: string, pattern?: RegExp): asserts value is readonly string[] {
  if (!Array.isArray(value)) {
    throw new TypeError(path + " must be an array");
  }
  const seen = new Set<string>();
  for (const [index, item] of value.entries()) {
    if (typeof item !== "string") {
      throw new TypeError(path + "[" + index + "] must be a string");
    }
    if (pattern !== undefined && !pattern.test(item)) {
      throw new TypeError(path + "[" + index + "] does not match required pattern");
    }
    if (seen.has(item)) {
      throw new TypeError(path + " must contain unique values");
    }
    seen.add(item);
  }
}

function assertStringMap(value: unknown, path: string): void {
  const record = assertRecord(value, path);
  for (const [key, item] of Object.entries(record)) {
    assertMinString(key, 1, path + ".key");
    assertMinString(item, 0, path + "." + key);
  }
}
